[AN-FEAT] 특성 ViewModel Test
woowacourse-teams/2024-pokerogue-helper pull request #126
Opened 2024-08-01 07:17 UTC by kkosang

- closed #121 
## 작업 영상
영상은 패스~

## 작업한 내용
- 특성 페이지 `FakeRepository & ViewModel Test`
- 특성 상세 페이지  `ViewModel test`

## PR 포인트
- 해당 페이지 작업할 때 같이 했어야 하는데 지금 올립니다..!

## 🚀Next Feature
가로 화면 대응 !!

2024-08-01 07:47 UTC, murjune requested changes
테스트하느라 고생하셨습니다 꼬오상 👍  

원래 테스트는 리뷰 잘 안하지만..  
테스트 밖에 없는 PR 이라 리뷰해보았어요 ㅋㅋ

2024-08-01 07:47 UTC, murjune commented on android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeAbilityRepository.kt
> +    override suspend fun abilityDetail(id: Long): AbilityDetail = ABILITIES_DETAIL
잘못된 id를 넣었을 때 예외를 발생시키는 등 실제 레포지토리처럼 구현하면 더 좋을 것 같습니다!!

2024-08-01 07:47 UTC, murjune commented on android/testing/src/test/java/poke/rogue/helper/testing/data/repository/FakeAbilityRepositoryTest.kt
> +            actualAbilities shouldBe expectedAbilities
현재 해당 테스트는 기존에 있는 코드를 그대로 호출하고 있습니다!

하드 코딩해주는건 어떨까요?

https://jojoldu.tistory.com/615

2024-08-01 07:47 UTC, murjune commented on android/testing/src/test/java/poke/rogue/helper/testing/data/repository/FakeAbilityRepositoryTest.kt
> +            val query = "타오르는불꽃"
expect 는 then 문으로 가야합니다!

2024-08-01 07:47 UTC, murjune commented on android/testing/src/test/java/poke/rogue/helper/testing/data/repository/FakeAbilityRepositoryTest.kt
> +            ability.find { it.title == query }?.title shouldBe query
```suggestion
// then
val actual = ability.find { it.title == query }?.title
val expect = "타오르는 불꽃"

actual shouldBe expect
```

이렇게 해볼 수도 있곘습니다!

2024-08-01 07:47 UTC, murjune commented on android/app/src/test/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewModelTest.kt
> +            val detail = (abilityDetail as AbilityDetailUiState.Success).data.toUi()
detail 은 actual 이기에 when에 들어가는것이 적절해보입니다!

2024-08-01 07:47 UTC, murjune commented on android/app/src/test/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewModelTest.kt
> +            val actualId = viewModel.navigationToPokemonDetailEvent.first()
이 또한 when이 맞을 것 같네요!

2024-08-01 07:47 UTC, murjune commented on android/app/src/test/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewModelTest.kt
> +            }
```suggestion
viewModel.navigateToPokemonDetail(pokemonId)
```

launch 는 없어도 될 것 같네요

2024-08-01 07:47 UTC, murjune commented
/noti

2024-08-01 08:08 UTC, kkosang commented on android/app/src/test/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewModelTest.kt
> +            }
navigateToPokemonDetail(pokemonId) 에서 sharedFlow의 값을 다루고 있습니다

launch를 제거하면 
```
kotlinx.coroutines.test.UncompletedCoroutinesError: After waiting for 10s, the test coroutine is not completing
```
코루틴이 끝나지 않는다는 에러가 발생합니다..
찾아보니 launch를 이용해서 테스트하라고 그랬었는데 lauch 없이 테스트하는 방법이 있나요 ?!

2024-08-01 08:18 UTC, kkosang commented on android/testing/src/test/java/poke/rogue/helper/testing/data/repository/FakeAbilityRepositoryTest.kt
> +            val query = "타오르는불꽃"
query는 given이자 expect라고 생각해서 given에 넣었습니다 ! when문에서 쿼리를 하기 위해 필요한 것 같아서요

2024-08-01 08:47 UTC, kkosang commented on android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeAbilityRepository.kt
> +    override suspend fun abilityDetail(id: Long): AbilityDetail = ABILITIES_DETAIL
예외를 발생시키도록 수정하고 테스트코드도 추가했습니다 !

2024-08-01 08:58 UTC, sh1mj1 reviewed
보는 중에 코드가 바뀌네요 ㅋㅋㅋ

수정 완료하시면 다시 볼게요~

2024-08-01 08:58 UTC, sh1mj1 commented on android/testing/src/test/java/poke/rogue/helper/testing/data/repository/FakeAbilityRepositoryTest.kt
> +            val query = "타오르는불꽃"
변수명이 수정된건가요?
저는 expected 가 안 보이네요

2024-08-01 08:58 UTC, sh1mj1 commented on android/testing/src/test/java/poke/rogue/helper/testing/data/repository/FakeAbilityRepositoryTest.kt
> +            actualAbilities shouldBe expectedAbilities
동감이에요~

2024-08-01 08:58 UTC, sh1mj1 commented on android/testing/src/main/java/poke/rogue/helper/testing/data/repository/FakeAbilityRepository.kt
> +            ability.title.has(query)
아 여기서 stringmatcher 모듈의 메서드를 쓰고 있군요~

2024-08-02 01:40 UTC, sh1mj1 commented on android/app/src/test/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewModelTest.kt
> +            }
[꼬상이 참고했다는 글](https://roomedia.tistory.com/entry/Turbine-%EC%97%86%EC%9D%B4-kotest%EC%97%90%EC%84%9C-StateFlow-SharedFlow-%ED%85%8C%EC%8A%A4%ED%8A%B8-%ED%95%98%EA%B8%B0-Unit-Test) 입니다.

2024-08-02 05:30 UTC, murjune commented on android/app/src/test/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewModelTest.kt
> +            }
오둥둥 퀴즈를 참고해주세요!

2024-08-02 05:39 UTC, JoYehyun99 approved these changes
굳굳~ 앞에서 많이 리뷰가 달려서 저는 바로 approve 하겠슴당
수고하셨어용~

2024-08-02 06:00 UTC, kkosang commented on android/testing/src/test/java/poke/rogue/helper/testing/data/repository/FakeAbilityRepositoryTest.kt
> +            val query = "타오르는불꽃"
변수명이 expected로 되어 있는건 없긴 했어요 !

2024-08-02 06:02 UTC, kkosang commented on android/app/src/test/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewModelTest.kt
> +            }
<img width="432" alt="스크린샷 2024-08-02 오후 3 01 48" src="https://github.com/user-attachments/assets/5019e0f4-ce13-4eb7-9c23-7ed38c7b9a7a">

2024-08-02 06:23 UTC, murjune approved these changes

2024-08-02 06:35 UTC, sh1mj1 approved these changes
고생하셨습니다!
코루틴, flow 테스트가 참 어려운 점이 많네요

2024-08-02 15:12 UTC, merged