[BE-REFACTOR] PokemonAbility 쿼리 개선
woowacourse-teams/2024-pokerogue-helper pull request #131
Opened 2024-08-02 08:54 UTC by jinchiim

## 🍄 PR 확인 사항
PR이 다음 요구 사항을 충족하는지 확인하세요. :

- [x] API 명세서가 업데이트 혹은 작성이 되어 있나요?

## 현재 작업은 어떤 이슈를 해결한 것인지 설명해주세요.
> Issue Number: #125 

- [x] `findAll`의 쿼리를 확인하고 개선한다.
- [x] `findByIdWithPokemonMappings` 의 쿼리를 확인하고 개선한다.
- [x] 각 개선 사항의 통계치를 만들어둔다.

## 기존 코드에서 변경된 점이 있다면 설명해주세요. (추가 X)

- [x] 있음
- [ ] 없음

```
`findByIdWithPokemonMappings`를 `fetch Join` 하여 포켓몬 당 한번의 쿼리가 아닌,
해당 `ability`에 해당하는 값들을 전부 영속성 컨텍스트에 저장하도록 수정
```

### 통계

![KakaoTalk_Photo_2024-08-02-17-49-47](https://github.com/user-attachments/assets/c07342f1-8068-4cea-9f39-0da14c03cfb3)
![KakaoTalk_Photo_2024-08-02-17-49-52](https://github.com/user-attachments/assets/384f76d1-6647-41a6-86a6-250a71df02df)

유저가 1000명, 5번씩 동시에 요청하는 경우 (해당 `ability`에 해당하는 포켓몬이 49마리)
인 경우 약 7배의 차이가 생김

2024-08-03 06:06 UTC, unifolio0 requested changes
가벼운 질문 하나 남겼어요!

구현 수고하셨습니다 🐳🐳

2024-08-03 06:46 UTC, jongmee reviewed
고생하셨습니다 🤍 리뷰 조금 남겨놨어요 ☺️

2024-08-03 06:46 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/repository/PokemonAbilityRepository.java
>      Optional<PokemonAbility> findByIdWithPokemonMappings(@NonNull @Param("id") Long id);
직접 쓴 쿼리이니 테스트가 있으면 좋을 것 같아요 🙋🏻‍♀️ !!

2024-08-03 06:46 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
> +                                .collect(Collectors.toList())
이 친구도 `.toList()`로 바꿔도 될 것 같아요 !!

2024-08-03 10:56 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/domain/PokemonAbility.java
> +    private Set<PokemonAbilityMapping> pokemonAbilityMappings;
`JPA` 에서는 `@OneToMany` 관계인 경우 중복 결과가 발생할 수 있다는 이유로 `List`인 경우 `Fetch Join`이 되지 않습니다!
그렇지만 이를 `Set`으로 바꾸면 특성상 중복을 허용하지 않으니 `Fetch Join`이 가능해집니다!

해당 부분의 경우 중복되는 `PokemonAbilityMapping`이 생길 수 없으니 바꿔주었어요!

2024-08-03 10:56 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
> +                                .collect(Collectors.toList())
헉 그렇네요! 좋습니다!

2024-08-03 10:57 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/repository/PokemonAbilityRepository.java
>      Optional<PokemonAbility> findByIdWithPokemonMappings(@NonNull @Param("id") Long id);
아이고 테스트를 놓쳤군요 🥹 
감사합니다!

2024-08-04 01:55 UTC, unifolio0 approved these changes
구현 수고하셨습니다~ 🐳🐳

2024-08-04 02:07 UTC, dwax1324 approved these changes
고생하셨습니다 👏👏
개선 전과 개선 후의 차이가 명확히 보이니 좋네요 !!
미아 말대로 쿼리에 대한 테스트 추가만 하면 될 것 같습니다!  🚀
(7배라니..🤩)

2024-08-05 06:04 UTC, jongmee approved these changes
고생하셨어요 👍

2024-08-05 06:04 UTC, jongmee commented on backend/pokerogue/src/test/java/com/pokerogue/helper/ability/service/PokemonAbilityServiceTest.java
> +        assertThatThrownBy(() -> pokemonAbilityService.findAbilityDetails(Long.MAX_VALUE))
`Long.MAX_VALUE` LGTM ✨

2024-08-05 06:05 UTC, merged