[BE-REFACTOR] Batch Insert를 통한 성능 개선 #122
woowacourse-teams/2024-pokerogue-helper pull request #132
Opened 2024-08-02 09:11 UTC by unifolio0

## 🍄 PR 확인 사항 PR이 다음 요구 사항을 충족하는지 확인하세요. : 
- [x] API 명세서가 업데이트 혹은 작성이 되어 있나요? 

## 현재 작업은 어떤 이슈를 해결한 것인지 설명해주세요. > Issue Number: #122 

- [x] DataSettingService의 save기능에 Batch Insert 도입

## 기존 코드에서 변경된 점이 있다면 설명해주세요. (추가 X) 
- [x] 있음 
- [ ] 없음 

Map을 통한 캐시 기능추가로 성능 개선
batch insert를 테스트 할수있는 api들 추가

2024-08-03 08:11 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataSettingService.java
> +        Map<String, PokemonType> pokemonTypeMap = pokemonTypeRepository.findAll().stream()
얘가 캐싱 역할을 하는 군요!

`pokemonTypeMap` 보다 `pokemonTypeCacheByName`이라는 네이밍 어떨까요 ? ☺️ key가 String이어서 변수명에 명시해주면 이해가 쉬울 것 같아요 👍

2024-08-03 09:07 UTC, jongmee requested changes
고생하셨습니다 👍  "조금 더 실험해보고 삭제할 예정"이라고 해서 `DataSettingService`를 위주로 코멘트 달았어요 ! 만약 유지한다면 `DataSettingService` 내용을 `DataBatchInsertService`로 변경한다고 보면 될까요 ?? (그래서 DataBatchInsertService 네이밍 등은 고려하지 않고 리뷰 달았어요~!)

2024-08-03 09:07 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataBatchInsertService.java
> +    private final JDBCPokemonRepository jdbcPokemonRepository;
PR 내용을 보니 없어질 수 있다고 하지만 혹시나 해서 달아놓겠습니다 ☺️

Pokemon과 관련된 쿼리메소드들은 PokemonRepository 한 곳에서 관리하는게 좋을 것 같습니다. 의존성도 적어지고 관리도 이 편이 쉬울 것 같아서요! JDBC 레포지토리도 인터페이스로 빼서 관리하는건 어떨까요 ? 아래처럼 구성할 수 있습니다.

```java
public interface PokemonRepository extends JpaRepository<Pokemon, Long>,  JDBCPokemonRepository {

public interface JDBCPokemonRepository {
    void batchInsertPokemon(List<Pokemon> pokemons);
}

@RequiredArgsConstructor
public class JDBCPokemonRepositoryImpl implements JDBCPokemonRepository {


```

2024-08-04 08:08 UTC, jinchiim requested changes
비토 너무 수고 많으셨어요! ☺️
몇가지 코멘트를 남겼으니 확인 부탁드려요!!

2024-08-04 08:08 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataSettingService.java
> +            image = s3Service.postImageToS3(image1);
어떤 이미지인지 변수 이름을 더 상세화 해주면 좋을 것 같아요! ☺️

2024-08-04 08:08 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataSettingService.java
> +            }
밑의 메서드와 함께 `Stream`으로 변경 가능하지 않을까요? ☺️

2024-08-04 08:08 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/controller/PokemonController.java
> +    }
개인적으로는 실제 프론트에서 사용하는 `PokemonAPI` 와 헷갈릴 것 같습니다.
저는 따로 구분하는 것은 어떨까 싶은데 다른 분들은 어떻게 생각하실까요? ☺️

또, 테스트가 아닌 `API`로 테스트를 구축하신 이유가 궁금합니다! (내가 못들었나 싶어서..)

2024-08-04 08:08 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/controller/PokemonController.java
> +    }
그리고 로그와 관련해서, 테스트용 `API`의 경우에는 시작을 하지 못하거나 `setDataBatch`가 끝났으나 `API Response` 에 잘못 담길 가능성이 없으니, 

로그는 빠져도 좋을 것 같다는 생각이 들어요! ☺️
오히려 `external` 쪽에 로그가 더 필요해 보입니다!

2024-08-04 10:20 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/controller/PokemonController.java
> +    }
이건 제가 설명이 부족했던 것 같아요😭😭

위 `/pre` , `/batch`로 되어있는 `API`들은 각각 `saveAll`과 `batchUpdate`가 얼마나 성능상의 차이가 있는지 확인하기 위해 잠깐 만들어 놓은 `API`에요. 해당 `API`들은 어느 쪽을 택할 지 결정하면 전부 삭제할 예정입니다!

2024-08-04 10:48 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/controller/PokemonController.java
> +    }
오 좋습니다! 😄

2024-08-04 11:43 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataSettingService.java
> +            image = s3Service.postImageToS3(image1);
저번에 s3관련 설정을 잘못해서 이미지 저장에 계속 오류가 나던 걸 디버깅 해본다고 따로 변수로 추출한 걸 깜빡하고 그대로 놔뒀네요😭😭
`image = s3Service.postImageToS3(pokeClient.getImage(id));`로 수정했습니다!

2024-08-04 12:22 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataBatchInsertService.java
> +            }
수정했습니다! ☺️☺️

2024-08-04 12:23 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataSettingService.java
> +            }
수정했습니다! ☺️☺️

2024-08-04 12:30 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataBatchInsertService.java
> +    }
수정했습니다! ☺️☺️

2024-08-05 05:35 UTC, dwax1324 approved these changes
🚀 LGTM 🚀

2024-08-05 05:49 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataSettingService.java
> +        Map<String, PokemonType> pokemonTypeMap = pokemonTypeRepository.findAll().stream()
네이밍을 `000CacheByName`과 같은 형식으로 변경했습니다!☺️☺️
추가로 캐싱할 때 `saveAll`의 반환값을 사용하도록 수정했습니다!☺️☺️

2024-08-05 05:51 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataBatchInsertService.java
> +    private final JDBCPokemonRepository jdbcPokemonRepository;
BatchInsert를 사용 안 하게 되면서 해당 클래스들은 전부 삭제했습니다!☺️☺️

이후에 BatchInsert를 사용하는 걸로 변경되면 위와 같이 관리하겠습니다! ☺️☺️

2024-08-05 05:53 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataSettingService.java
>          List<PokemonType> allPokemonTypes = pokemonTypeRepository.findAll();
수정했습니다! ☺️☺️

2024-08-05 05:56 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataBatchInsertService.java
> +            PokemonType pokemonType = pokemonTypeRepository.findByName(dataUrl.name()).orElseThrow();
수정했습니다! ☺️☺️

2024-08-05 06:04 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataSettingService.java
> +            PokemonType fromPokemonType = pokemonTypeRepository.findByName(dataUrl.name()).orElseThrow();
수정했습니다!☺️☺️

2024-08-05 06:05 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataBatchInsertService.java
> +    private final JDBCPokemonRepository jdbcPokemonRepository;
최고 ! 👍

2024-08-06 00:48 UTC, jinchiim approved these changes

2024-08-06 00:49 UTC, merged