[BE-FEAT] 포켓몬 정보를 불러오는 API
woowacourse-teams/2024-pokerogue-helper pull request #230
Opened 2024-08-14 10:50 UTC by dwax1324

## 🍄 PR 확인 사항
PR이 다음 요구 사항을 충족하는지 확인하세요. :

- [x] API 명세서가 업데이트 혹은 작성이 되어 있나요?

## 현재 작업은 어떤 이슈를 해결한 것인지 설명해주세요.
> Issue Number: #229 

- [x] 모든 포켓몬 정보를 불러오는 API
- [x] 단일 포켓몬 정보를 불러오는 상세 API

## 기존 코드에서 변경된 점이 있다면 설명해주세요. (추가 X)

- [ ] 있음
- [x] 없음

다음 순위로 리펙터링할 생각입니다

1. 응답하지 못하고 있는 세세한 정보 (로고, 이미지 URL... 더미데이터 제거)
2. 코드 리펙터링, 패키지 분리

### all

```json
{
  "message": "포켓몬 리스트 불러오기에 성공했습니다.",
  "data": [
    {
      "generation": 1,
      "image": "todo:imageLink",
      "pokedexNumber": 1,
      "hp": 45,
      "speed": 45,
      "totalStats": 318,
      "specialDefense": 65,
      "defense": 49,
      "attack": 49,
      "name": "이상해씨",
      "id": "이상해씨",
      "specialAttack": 65,
      "pokemonTypeResponse": [
        {
          "pokemonTypeName": "풀",
          "pokemonTypeLogo": "todo:logo"
        },
        {
          "pokemonTypeName": "독",
          "pokemonTypeLogo": "todo:logo"
        }
      ]
    },
    ...
    ]

```

### single

```json
{
  "message": "포켓몬 정보 불러오기에 성공했습니다.",
  "data": {
    "pokemonAbilityResponses": [
      {
        "id": "그래스메이커",
        "name": "그래스메이커",
        "description": "description",
        "passive": true,
        "hidden": false
      },
      {
        "id": "심록",
        "name": "심록",
        "description": "description",
        "passive": false,
        "hidden": false
      },
      {
        "id": "심록",
        "name": "심록",
        "description": "description",
        "passive": false,
        "hidden": false
      },
      {
        "id": "엽록소",
        "name": "엽록소",
        "description": "description",
        "passive": false,
        "hidden": true
      }
    ],
    "biomes": [
      {
        "id": "풀숲",
        "name": "풀숲"
      }
    ],
    "hp": 45,
    "weight": 6.9,
    "mythical": false,
    "subLegendary": false,
    "speed": 45,
    "pokeDexNumber": 1,
    "totalStats": 318,
    "eggMoves": [
      {
        "id": "기가드레인",
        "name": "기가드레인"
      },
      {
        "id": "오물폭탄",
        "name": "오물폭탄"
      },
      {
        "id": "대지의힘",
        "name": "대지의힘"
      },
      {
        "id": "쑥쑥봄버",
        "name": "쑥쑥봄버"
      }
    ],
    "specialDefense": 65,
    "defense": 49,
    "attack": 49,
    "legendary": false,
    "moves": [
      {
        "name": "몸통박치기",
        "level": 1,
        "power": 40,
        "accuracy": 100,
        "type": "노말",
        "category": "PHYSICAL"
      },
      {
        "name": "울음소리",
        "level": 1,
        "power": -1,
        "accuracy": 100,
        "type": "노말",
        "category": "STATUS"
      },
      {
        "name": "덩굴채찍",
        "level": 3,
        "power": 45,
        "accuracy": 100,
        "type": "풀",
        "category": "PHYSICAL"
      },
      {
        "name": "성장",
        "level": 6,
        "power": -1,
        "accuracy": -1,
        "type": "노말",
        "category": "STATUS"
      },
      {
        "name": "씨뿌리기",
        "level": 9,
        "power": -1,
        "accuracy": 90,
        "type": "풀",
        "category": "STATUS"
      },
      {
        "name": "잎날가르기",
        "level": 12,
        "power": 55,
        "accuracy": 95,
        "type": "풀",
        "category": "PHYSICAL"
      },
      {
        "name": "독가루",
        "level": 15,
        "power": -1,
        "accuracy": 75,
        "type": "독",
        "category": "STATUS"
      },
      {
        "name": "수면가루",
        "level": 15,
        "power": -1,
        "accuracy": 75,
        "type": "풀",
        "category": "STATUS"
      },
      {
        "name": "씨폭탄",
        "level": 18,
        "power": 80,
        "accuracy": 100,
        "type": "풀",
        "category": "PHYSICAL"
      },
      {
        "[name](https://en.dict.naver.com/#/search?query=name)": "돌진",
        "level": 21,
        "power": 90,
        "accuracy": 85,
        "type": "노말",
        "category": "PHYSICAL"
      },
      {
        "name": "달콤한향기",
        "level": 24,
        "power": -1,
        "accuracy": 100,
        "type": "노말",
        "category": "STATUS"
      },
      {
        "name": "광합성",
        "level": 27,
        "power": -1,
        "accuracy": -1,
        "type": "풀",
        "category": "STATUS"
      },
      {
        "name": "고민씨",
        "level": 30,
        "power": -1,
        "accuracy": 100,
        "type": "풀",
        "category": "STATUS"
      },
      {
        "name": "파워휩",
        "level": 33,
        "power": 120,
        "accuracy": 85,
        "type": "풀",
        "category": "PHYSICAL"
      },
      {
        "name": "솔라빔",
        "level": 36,
        "power": 120,
        "accuracy": 100,
        "type": "풀",
        "category": "SPECIAL"
      }
    ],
    "pokemonTypeResponses": [
      {
        "pokemonTypeName": "풀",
        "pokemonTypeLogo": "dummy-logo"
      },
      {
        "pokemonTypeName": "독",
        "pokemonTypeLogo": "dummy-logo"
      }
    ],
    "name": "이상해씨",
    "id": "이상해씨",
    "evolutions": [
      {
        "pokemonName": "이상해풀",
        "level": 16
      },
      {
        "pokemonName": "이상해꽃",
        "level": 32
      }
    ],
    "pokemonImage": "dummy-image",
    "specialAttack": 65,
    "canChangeForm": false,
    "height": 0.7
  }
}
```

2024-08-15 08:10 UTC, jongmee requested changes
고생하셨습니다 ⚡️ 컨벤션적인 것보다, 당장 베타 버전에 배포할 때 문제가 생길 수 있을 것 같은 부분이나 추후 리팩토링할 때 필요할 것 같은 부분들만 리뷰 남겼어요 ! 

++ 서브모듈 커밋 히스토리에 변경 사항이 있는데 서브모듈 레포를 보니까 추가 커밋은 없더라고요! 이 부분 변경사항은 삭제해주세요 !

2024-08-15 08:10 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/Pokemon2Service.java
> +package com.pokerogue.helper.pokemon2;
빠르게 진행한 이유는 바뀐 기능을 (AN와)빨리 연동하기 위해서였죠 ! DataIntiailizer나 서비스 로직에 대한 테스트가 없다면 CI가 제대로 이루어지지 않을텐데 이대로 배포해도 괜찮을까요 ? 🥲

2024-08-15 08:10 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/Pokemon2Service.java
> +    private void initFindByIdCache() {
저희의 레포지토리 자체가 저장과 캐싱 역할을 해주는데 서비스 로직에서 캐싱할 필요가 있을까요 ?? ApplicationRunner에서 integer parsing 등을 해주고, 레포지토리에 저장해야 되는 것 아닐까요 ?? 😙

2024-08-15 08:10 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/Pokemon2Repository.java
> +    private final Map<String, Map<String, String>> data = new TreeMap<>();
레포지토리에 캐싱한다면, 객체로 저장하는게 추후 리팩토링할 때도 더 좋지 않을까요 ?? ☺️

2024-08-15 08:54 UTC, unifolio0 reviewed
우선 로직보다는 서로 얘기해야 될 부분이 있는 것 같아 그 부분에 의견만 달아놨습니다!

구현 수고하셨습니다! 🐳🐳

2024-08-15 08:54 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/Pokemon2Repository.java
> +    private final Map<String, Map<String, String>> data = new TreeMap<>();
저도 미아 의견에 동의합니다! 저도 비슷하게 String으로 저장했는데 오히려 이후에 정보들을 결합할 때 더 힘들었던 것 같아요... 추후를 대비한다면 객체를 하나 만들어서 처음 파싱에서 고생하는게 더 좋을 거라 생각합니다!

2024-08-16 00:51 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/global/config/DatabaseInitializer.java
> -        List<Pokemon> pokemons = pokemonRepository.saveAll(List.of(
나중에 바꾼다는 게 깜빡했네요 👀

2024-08-16 00:52 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/global/exception/PokemonExceptionHandler.java
> +        log.error("error message : {}", e);
에러가 발생해서 원인을 찾아보려고 했는데 `e.getStackTrace()[0]`으로만 출력되니 디버깅하기가 쉽지 않더라고요.
다시 바꿔놓겠습니다.
이에 대해 나중에 다같이 얘기해보면 좋을 것 같습니다.

2024-08-16 00:54 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/Pokemon2Controller.java
> +    @GetMapping("/api/v1/pokemon2/{stringId}")
요것도 에러가 계속 발생해서 이것저것 바꿔보다가 다시 복구를 안해놨네요 ㅠㅠ

2024-08-16 00:56 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/Pokemon2Service.java
> +package com.pokerogue.helper.pokemon2;
`DataIntiailizer나 서비스 로직에 대한 테스트`에 대한 필요성은 공감하지만 일단은 우선순위가 아니라고 생각했어요.

2024-08-16 00:57 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/Pokemon2Service.java
> +    private void initFindByIdCache() {
맞습니다.

2024-08-16 00:57 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/Pokemon2Repository.java
> +    private final Map<String, Map<String, String>> data = new TreeMap<>();
공감합니다!

2024-08-16 00:58 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/Pokemon2Repository.java
> +    private final Map<String, Map<String, String>> data = new TreeMap<>();
저도 동의합니다!

2024-08-16 11:54 UTC, unifolio0 approved these changes
이후에 리팩토링을 하기로 했으니 일단 approve 합니다.

구현 수고하셨습니다! 👍 👍

2024-08-16 13:04 UTC, jongmee approved these changes

2024-08-17 01:07 UTC, jongmee commented
/noti

머지를 기다려요 🍎

2024-08-17 01:15 UTC, jinchiim commented
/noti 알람!

2024-08-19 04:06 UTC, merged