[BE-FEAT] 바이옴 리스트를 불러오는 API
woowacourse-teams/2024-pokerogue-helper pull request #231
Opened 2024-08-14 13:04 UTC by unifolio0

## 🍄 PR 확인 사항
PR이 다음 요구 사항을 충족하는지 확인하세요. :

- [x] API 명세서가 업데이트 혹은 작성이 되어 있나요?

## 현재 작업은 어떤 이슈를 해결한 것인지 설명해주세요.
> Issue Number: #221 

- [x] 바이옴 리스트를 불러온다

## 기존 코드에서 변경된 점이 있다면 설명해주세요. (추가 X)

- [ ] 있음
- [x] 없음

2024-08-15 08:33 UTC, jongmee requested changes
고생하셨읍니다 🚀 컨벤션이나 코드 구조, 세세한 부분보다는 큰 그림을 생각하며(당장 배포될 것을 생각하며) 리뷰 남겼습니다 !! 참고해주셔요 😉

2024-08-15 08:33 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/config/BiomeDatabaseInitializer.java
> +                "C:\\Users\\s_osang0731\\precourse\\2024-pokerogue-helper\\backend\\pokerogue\\src\\main\\java\\com\\pokerogue\\helper\\biome\\config\\biome.txt")
배포 환경은 비토 컴퓨터가 아니니 상대경로로 지정해주세요 ! 😉

2024-08-15 08:33 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/config/BiomeDatabaseInitializer.java
> +package com.pokerogue.helper.biome.config;
빠르게 진행한 이유는 바뀐 기능을 (AN와)빨리 연동하기 위해서였죠 ! DataIntiailizer나 서비스 로직에 대한 테스트가 없다면 CI가 제대로 이루어지지 않을텐데 이대로 배포해도 괜찮을까요 ? 🥲

2024-08-15 08:33 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/repository/BiomeRepository.java
> +                    pokemons.addAll(List.of(biomeInforms[3].split(",")));
데이터를 파싱하는건 저장소(Repository)보다 BiomeDataInitializer에서 하는게 좋을 것 같아요 ! ☺️

2024-08-15 08:33 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/repository/BiomeRepository.java
> +    private final Map<String, Map<String, Map<String, List<String>>>> biomes;
다음에 각 기능에서 중복되는 데이터들을 함께 관리할 텐데 각 기능에서 필요한 데이터들을 원활하게 체크 하려면 객체로 저장하는게 좋지 않을까요 ?? 😊

2024-08-15 08:33 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/repository/BiomeRepository.java
> +@Repository
우리가 저장하는 데이터는 DB에 영속화되지 않고, `DataAccessException`도 필요하지 않을텐데 `@Component`가 맞지 않을까요?! ☺️

2024-08-15 09:43 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/repository/BiomeRepository.java
> +@Repository
개인적인 의견으로는 평소에 `@Repository`를 어떤 의미에서 썼냐에 따라 달라질 수 있겠다고 생각해요.
제가 알기로는 두가지의 의미가 있는 것으로 압니다.

1. 해당 클래스는 `DDD` 에서 파생된, 데이터에 접근하여 조회, 수정, 생성 등의 행위를 하는 객체의 컬렉션 클래스 이다.
2.  `PersistenceExceptionTranslationPostProcessor` 를 주입받아 `DataAccessException`을 던질 수 있는 클래스이다.

다른분들은 어떻게 하셨는지 모르겠지만 저는 사실 해당 어노테이션을 사용할 때 딱히 `ersistenceExceptionTranslationPostProcessor` 를 주입하거나 `Bean`으로 등록하지 않았었습니다.

그래서 첫번째 의미로 많이 사용했었어서 그런지 명시적으로 `@Repository`를 사용하는 것에 거부감이 없는 것 같아요.

그렇지만, `@Repository` 라는 개념 자체도 미아가 말씀하신 대로 영속화와 도메인을 분리하기 위한 아키텍처에서 비롯되어서 미아의 의견에도 어느정도 동의하게 되는 듯 합니다.

개인적으로 저는 `@Component`를 쓰는것 조차 안좋아하긴 해요 ㅋㅋㅋㅋㅋ
굳이 `Bean`으로 등록할 필요가 없어도 되는데 습관적으로 붙이는 느낌..? 나중에는 결국 해당 어노테이션에 의존하게 되어서
`@SpringBootTest`를 쓸 수 밖에 없게 되더라고요.

아무튼 이 얘기는 뭔가 각자의 평소 취향과 생각에 따라서 달라질 것 같은데 한번 얘기해보는 것도 좋은 시간이 될 것 같아요 ☺️
저는 두가지 다 괜찮습니다! 

라고 꼽사리 껴봅니다

2024-08-15 10:21 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/repository/BiomeRepository.java
> +@Repository
저는 `@Repository`를 명시적인 용도로 사용하는 것 같아요. `@Service`와 `@Component`와 기능상으로 아무런 차이점이 없지만 서비스 계층에선 `@Service`를 사용하는 것처럼 말이죠.☺️☺️

그래서 저는 DDD는 잘 모르지만 구조 상 컨트롤러, 서비스, 레포지토리에 해당하는 클래스를 제외한 나머지 클래스에만 `@Component`를 붙이고 있습니다!

2024-08-15 13:57 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/repository/BiomeRepository.java
> +@Repository
인지적으로 도움을 주기 위해 사용하시는 군요 ! 다함께 얘기해서 통일해봅시다 !

저는 항상 JDBC나 DataJPA와 함께 `@Repository`를 사용했어서 `persistenceExceptionTranslationPostProcessor `를 자동으로 주입해서 사용해왔습니다 :)

2024-08-15 14:59 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/repository/BiomeRepository.java
> +@Repository
`DataAccessException`으로 자동 변환해주는 것을 중요하게 여겼다면 확실히 그럴 수 있을 것 같아요! 
제가 아직 자동 변환의 이점을 못느낀걸수도 있겠네요 😮

확실히 `Hibernate`와 함께 붙은 `@Repository`가 단순히 `@Component` 보다 많은 역할을 해주긴 했다보니 
고민이 드는 문제 같아요.
내일 많이 얘기해봅시다! 둘 다 좋은 방향 같아요 👍🏻 (내일은 나갈수 있기를... 🥹)

2024-08-16 01:28 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/repository/BiomeRepository.java
> +                    pokemons.addAll(List.of(biomeInforms[3].split(",")));
파싱하는 역할을 따로 클래스로 만들도록 수정했습니다!☺️☺️

지금 방식에 대해선 어떻게 생각하시나요?

2024-08-16 01:28 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/repository/BiomeRepository.java
> +    private final Map<String, Map<String, Map<String, List<String>>>> biomes;
객체로 수정했습니다! ☺️☺️

2024-08-16 01:53 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/config/BiomeDatabaseInitializer.java
> +package com.pokerogue.helper.biome.config;
테스트 작성했습니다! ☺️☺️

2024-08-16 03:19 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/config/BiomeDatabaseInitializer.java
> +package com.pokerogue.helper.biome.config;
오 !! 굿 👍 너무 좋습니다. 간단한 테스트라도 있는게 좋을 것 같아요 😉

2024-08-16 03:37 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/config/BiomeDatabaseInitializer.java
> +        bufferedReader = new BufferedReader(new FileReader(
IO 자원은 반납해주어야 합니다 !!

현재 IOException을 그냥 던져주고, Reader들에 대한 자원을 반납하고 있지 않은데, `try-with-resource`문으로 자동 자원 반납 및 예외 처리를 할 수 있습니당 ☺️ 우선 제 로컬에 있는 코드를 예시로 가져와봤습니다
```java
    private void saveData(String path, Consumer<List<String>> createAndSaveOperation) {
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            int lineCount = 0;
            String line;
            while ((line = br.readLine()) != null) {
                lineCount++;
                if (lineCount < FIRST_LINE) {
                    continue;
                }
                List<String> fields = splitFields(line);
                createAndSaveOperation.accept(fields);
            }
        } catch (IOException e) {
            log.error("error message : {}", e.getStackTrace()[0]);
        }
    }
```

자원을 제때 반납해주지 않으면 메모리 부족, 파일 핸들링 관련 자원 부족, 성능 저하 등등의 문제가 발생할 수 있습니다

2024-08-16 03:38 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/config/BiomeDatabaseInitializer.java
> +        );
IO 자원은 반납해주어야 합니다 !!

현재 IOException을 그냥 던져주고, Reader들에 대한 자원을 반납하고 있지 않은데, `try-with-resource`문으로 자동 자원 반납 및 예외 처리를 할 수 있습니당 ☺️ 우선 제 로컬에 있는 코드를 예시로 가져와봤습니다
```java
    private void saveData(String path, Consumer<List<String>> createAndSaveOperation) {
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            int lineCount = 0;
            String line;
            while ((line = br.readLine()) != null) {
                lineCount++;
                if (lineCount < FIRST_LINE) {
                    continue;
                }
                List<String> fields = splitFields(line);
                createAndSaveOperation.accept(fields);
            }
        } catch (IOException e) {
            log.error("error message : {}", e.getStackTrace()[0]);
        }
    }
```

자원을 제때 반납해주지 않으면 메모리 부족, 파일 핸들링 관련 자원 부족, 성능 저하 등등의 문제가 발생할 수 있습니다 🥲 꽤 중요한 부분인 것 같아서 리뷰 남겨놔요 !

2024-08-16 03:42 UTC, jongmee requested changes
와우 열심히 수정해주셨군요 👍 추가 리뷰 몇 개 더 남겨봤습니다 !

2024-08-16 03:42 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/config/BiomeDatabaseInitializer.java
> +        bufferedReader = new BufferedReader(new FileReader(
IO 자원은 반납해주어야 합니다 !!

현재 IOException을 그냥 던져주고, Reader들에 대한 자원을 반납하고 있지 않은데, `try-with-resource`문으로 자동 자원 반납 및 예외 처리를 할 수 있습니당 ☺️ 우선 제 로컬에 있는 코드를 예시로 가져와봤습니다
```java
    private void saveData(String path, Consumer<List<String>> createAndSaveOperation) {
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            int lineCount = 0;
            String line;
            while ((line = br.readLine()) != null) {
                lineCount++;
                if (lineCount < FIRST_LINE) {
                    continue;
                }
                List<String> fields = splitFields(line);
                createAndSaveOperation.accept(fields);
            }
        } catch (IOException e) {
            log.error("error message : {}", e.getStackTrace()[0]);
        }
    }
```

자원을 제때 반납해주지 않으면 메모리 부족, 파일 핸들링 관련 자원 부족, 성능 저하 등등의 문제가 발생할 수 있습니다 🥲 꽤 중요한 부분인 것 같아서 리뷰 남겨놔요 !

2024-08-16 03:42 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/repository/BiomeRepository.java
> +                    pokemons.addAll(List.of(biomeInforms[3].split(",")));
레포지토리에서 파싱하지 않도록 수정됐군요 !! 좋습니다

(추가 리뷰) 비토 패키지 구조를 보면 domain에 레포지토리에 저장되는 클래스와 파싱하는 클래스가 존재하는데, 다른 팀원이 클래스들을 구분하기 어려울 것 같다는 생각이 듭니다 🥲 또 제 생각에는 두 클래스 모두 `도메인`은 아닌 것 같다는 생각이 듭니다. 저는 레포지토리에 저장되는 클래스는 `data`, 파싱하는 클래스는 `util` 패키지에 두는게 더 자연스럽다고 생각하는데 어떠신지요 ? 😊

(플러스 알파) 파싱하는 클래스들은 public 메소드 혹은 생성자가 있으니 테스트할 수 있을 것 같아요 ! 물론 시간이 없다면 지금은 생략해도 어쩔 수 없지만요 ☺️

2024-08-16 04:13 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/repository/BiomeRepository.java
> +                    pokemons.addAll(List.of(biomeInforms[3].split(",")));
> (추가 리뷰) 비토 패키지 구조를 보면 domain에 레포지토리에 저장되는 클래스와 파싱하는 클래스가 존재하는데, 다른 팀원이 클래스들을 구분하기 어려울 것 같다는 생각이 듭니다 🥲 또 제 생각에는 두 클래스 모두 `도메인`은 아닌 것 같다는 생각이 듭니다. 저는 레포지토리에 저장되는 클래스는 `data`, 파싱하는 클래스는 `util` 패키지에 두는게 더 자연스럽다고 생각하는데 어떠신지요 ? 😊

우선 `data`는 좋다고 생각합니다! 😊😊
하지만 저는 `util`은 좀 더 범용적으로 쓸 수 있는 클래스가 담긴 패키지로 이해하고 있어요. 현재 저희 `util`패키지에 있는 `ApiResponse`처럼 한 범위에만 국한되어 사용할 수 있는 게 아닌 넓은 범위를 아우를 수 있는 클래스처럼 말이에요.

현재 미아가 `util`에 두는 게 어떻냐고 한 클래스들은 전부 특정 정보가 특정 형식으로 구성되어 있는 txt파일만 파싱할 수 있는 클래스라서 `util`에 두기엔 너무 사용할 수 있는 범위가 좁지 않나라는 생각이 들어요.

그래서 해당 클래스들도 txt파일의 정보들을 저장하고 있다고 판단해서 `data` 폴더에 같이 위치시켰는데 미아는 어떻게 생각하시나요?

2024-08-16 04:19 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/config/BiomeDatabaseInitializer.java
> +        bufferedReader = new BufferedReader(new FileReader(
수정했습니다!☺️☺️

2024-08-16 05:19 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/repository/BiomeRepository.java
> +                    pokemons.addAll(List.of(biomeInforms[3].split(",")));
> (플러스 알파) 파싱하는 클래스들은 public 메소드 혹은 생성자가 있으니 테스트할 수 있을 것 같아요 ! 물론 시간이 없다면 지금은 생략해도 어쩔 수 없지만요 ☺️

해당 부분은 추후 작성하겠습니다!

2024-08-16 05:30 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/repository/BiomeRepository.java
> +                    pokemons.addAll(List.of(biomeInforms[3].split(",")));
오호 좋습니다. 오늘까지 배포해야 되니 패키지는 다음에 또 얘기해봅시다 👍

2024-08-16 05:31 UTC, jongmee approved these changes

2024-08-16 05:31 UTC, dwax1324 approved these changes

2024-08-16 05:47 UTC, jinchiim approved these changes

2024-08-16 08:05 UTC, merged