[BE-FEAT] 포켓몬의 기술 리스트 불러오는 API
woowacourse-teams/2024-pokerogue-helper pull request #237
Opened 2024-08-16 11:14 UTC by jongmee

## 🍄 PR 확인 사항
PR이 다음 요구 사항을 충족하는지 확인하세요. :

- [x] API 명세서가 업데이트 혹은 작성이 되어 있나요?

## 현재 작업은 어떤 이슈를 해결한 것인지 설명해주세요.
> Issue Number: #219

- [x] 포켓몬 기술 데이터 세팅
- [x] 포켓몬의 기술 리스트 조회 api 구현

## 기존 코드에서 변경된 점이 있다면 설명해주세요. (추가 X)

- [ ] 있음
- [x] 없음

가지고 있는 포켓몬 파일에서 자력 기술, 알 기술을 추출해야 되는데 아직 기술 id(integer)가 아닌 이름으로 저장되어 있어 id를 일단 한글 이름으로 저장했습니다. 추후 바뀔 예정입니다. (참고로 기술은 중복되는 이름이 있지만 아직 포켓로그에 구현이 되지 않은 dummy data입니다.)

포켓몬 도감 번호에 대해서 TM으로 배울 수 있는 기술, 자력 기술, 알 기술을 모두 불러오도록 구현했습니다.

2024-08-16 12:27 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/global/config/DatabaseInitializer.java
>          ));
ci를 위해서 넣어주었습니다 😅

2024-08-16 13:47 UTC, unifolio0 approved these changes
우선 파싱하는 부분을 제외한 나머지 부분만 확인했어요!
코멘트 1개 달았긴 한데, 필수적인 부분은 아니니 바로 approve합니다!

구현 수고하셨습니다! 👍 👍

2024-08-16 13:47 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
> +    }
사진 관련은 S3Service를 사용하는 건 어떤가요?☺☺

2024-08-16 13:47 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/MoveRepository.java
> +    }
오! 참고해갑니다~ ☺☺

2024-08-17 01:03 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
> +    }
포켓몬 타입 같은 경우는 BattlePokemonTypeRepository를 생성해서 이미지를 S3Service로 넣어두었고 (DataInitiaiizer에 코드 있읍니다) 기술 카테고리는 세 개 밖에 없어서 따로 enum을 생성해주었습니다! 서비스에 static으로 image url 두는 것보다 데이터 클래스를 만드는게 좋아 보이네요 😊

(BattlePokemonTypeRepository 이름은 기존에 존재하는 PokemonTypeRepository와 헷갈릴까봐 앞에 battle을 붙였습니다)

2024-08-17 07:00 UTC, jinchiim requested changes
빨리 머지시키는게 중요할 것 같아 컨벤션 정도만 훑어 봤습니다!
정말 고생하셨어요!! ☺️

2024-08-19 04:04 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
> +        return moves.stream()
개행 추가했습니다 :)

2024-08-19 04:04 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/MoveCategory.java
> +    ;
방금 얘기한대로 비토벤션에 맞췄습니다 !!

2024-08-19 04:07 UTC, jinchiim approved these changes

2024-08-19 04:15 UTC, dwax1324 approved these changes

2024-08-19 04:15 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
> +                .toList();
데이터가 추가되거나 삭제될 일이 없기 때문에 한번 계산한 결과는 캐싱해두는 것이 어떨까요?👍

2024-08-19 04:54 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
> +                .toList();
화면에 보여지는 모든 요소들을 다 캐싱해야 할까요 ?? 저는 현재 인메모리 레포지토리로도 충분하다고 생각합니다 ☺️

2024-08-19 05:17 UTC, merged