[BE-FEAT] 바이옴 세부 정보를 불러오는 API
woowacourse-teams/2024-pokerogue-helper pull request #253
Opened 2024-08-19 06:22 UTC by unifolio0

## 🍄 PR 확인 사항
PR이 다음 요구 사항을 충족하는지 확인하세요. :

- [x] API 명세서가 업데이트 혹은 작성이 되어 있나요?

## 현재 작업은 어떤 이슈를 해결한 것인지 설명해주세요.
> Issue Number: #236 

- [x] 바이옴 세부 정보를 불러온다

## 기존 코드에서 변경된 점이 있다면 설명해주세요. (추가 X)

- [x] 있음
- [ ] 없음

txt데이터 형식 변경, 이미지 url 반환하도록 변경, 일부 클래스 필드 타입 변경

2024-08-19 11:25 UTC, jongmee requested changes
빠르고, 여러 객체를 사용해서 잘 구현해주셨네요 👍 굿이예요

2024-08-19 11:25 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +        return BiomeDetailResponse.of(
저도 맨날 까먹는데.. return 전에 개행 !! ☺️

2024-08-19 11:25 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +                    System.out.println(biomePokemon);
실수 포착 sout 발견 👀

2024-08-19 11:25 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +                        "포켓몬 이미지",
요 이미지는 의도된 걸까요 ??

2024-08-19 11:25 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +                        s3Service.getTrainerImageFromS3(trainer.getId()),
매번 s3에서 이미지를 가져오는 것보다 repository에 이미지 url을 저장하는게 어떨까요 ?? data initializer에서 할 수 있을 것 같네요 !

2024-08-19 11:25 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +                        s3Service.getTrainerImageFromS3(trainer.getId()),
요것도 비용이 들 것 같아서 🙈

2024-08-19 12:36 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +        return BiomeDetailResponse.of(
수정했습니다! ☺️☺️

2024-08-19 12:46 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +                        "포켓몬 이미지",
아직 포켓몬 이미지의 이름이 1, 2, 3, ... 과 같은 숫자로 저장되어 있어 우선 더미를 넣어놨습니다.
지금 현재 저장되어 있는 방식인 숫자로 아이디를 만들어 진행할 지, 아니면 지금 정해진 방식인 영어로 아이디를 만들어 우선 없는 사진 url이라도 넣을지 고민하다가 후자의 방식으로 해놨습니다!

2024-08-19 13:30 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +                        s3Service.getTrainerImageFromS3(trainer.getId()),
수정했습니다! ☺️☺️
이왕이면 `S3Service`를 `BiomeService`와 `BiomeDatabaseInitializer` 둘 중 한 곳에서만 사용하고 싶어서 `BiomePokemonTypeImageRepository`를 만들어서 타입 이미지 url도 저장하도록 했는데 이에 대해선 어떻게 생각하시나요?

2024-08-19 16:47 UTC, jinchiim requested changes
빠른 머지를 위해 최대한 간단한 것들만 해봤어요!
빠른 구현 수고하셨어요! ☺️

2024-08-19 16:47 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/PokemonByBiome.java
> +        this.type2 = pokemonByBiomeInforms[3];
마음이 매우 편해졌어요 ^^ 😊

2024-08-19 16:47 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/Tier.java
> +    }
`Boss`가 아니면 `wild` 일텐데 메서드는 둘 중 하나만 있어도 되지 않을까요?

2024-08-19 23:31 UTC, dwax1324 approved these changes
비토 고생하셨습니다👍👍

2024-08-19 23:31 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/dto/BiomeDetailResponse.java
> +        List<NextBiomeResponse> map
제안입니다🙂
```suggestion
    List<BiomeAllPokemonResponse> wildPokemons,
        List<BiomeAllPokemonResponse> bossPokemons,
        List<TrainerPokemonResponse> trainerPokemons,
        List<NextBiomeResponse> nextBiomes
```

2024-08-19 23:31 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/Tier.java
> +    }
명시적으로 알 수 있어서 저는 둘 다 있는게 나아보이네요~!

2024-08-19 23:31 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/config/BiomeDatabaseInitializer.java
> +    private boolean isExistTrainer(List<TrainerType> trainerTypes, String trainerName) {
메서드명 제안) `isTrainerExist`

2024-08-20 01:13 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/Tier.java
> +    }
@jinchiim 

> Boss가 아니면 wild 일텐데 메서드는 둘 중 하나만 있어도 되지 않을까요?

이후에 어떻게 변화해서 다른 범위의 포켓몬이 나올 수도 있고
`!`을 왠만하면 사용하기 싫어서 메서드를 둘로 나눴습니다.

폴라는 어떻게 생각하시나요? 😊😊

2024-08-20 01:18 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/external/s3/service/S3Service.java
> +    }
@jinchiim 

개인적으로 저는 메서드로 따로 빼기보다 
```
public String getBiomeImageFromS3(String biomeId) {
        String key = BIOME_IMAGE_FOLDER + biomeId + PNG_EXTENSION;
        return s3ImageClient.getFileUrl(key);
    }
```

이런식으로 같은 메서드 안에 두는게 더 명확한 것 같아요! 만약 새로 저장하는 파일의 이름을 만드는 거라면 모를까 가져올 파일의 이름을 만드는 로직은 클래스를 분리하면 너무 역할이 분리되어 있다는 생각이 들어요.🤔

폴라는 어떻게 생각하시나요?

2024-08-20 01:20 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/dto/BiomeDetailResponse.java
> +        List<NextBiomeResponse> map
더 명확한 이름이네요! api문서와 같이 수정했습니다! 😊😊

2024-08-20 01:29 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/config/BiomeDatabaseInitializer.java
> +    private boolean isExistTrainer(List<TrainerType> trainerTypes, String trainerName) {
@dwax1324 

고민하다가 JPA형식을 따라 `existsByTrainerName`으로 네이밍했는데 어떻게 생각하시나요?

2024-08-20 02:28 UTC, jinchiim approved these changes

2024-08-20 02:28 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/Tier.java
> +    }
나쁘지 않다고 생각해요!
좀 더 좋은 방법은 있을 것 같은데, 우선 넘어가죠!

2024-08-20 02:28 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/external/s3/service/S3Service.java
> +    }
좀 더 얘기해보아요! 우선 지금은 머지가 시급하니 오늘 회의 때 더 나누어보죠!

2024-08-20 07:01 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +                        s3Service.getTrainerImageFromS3(trainer.getId()),
좋습니다~!~!~ 굿

2024-08-20 07:01 UTC, jongmee approved these changes
굿!!!!

2024-08-20 07:02 UTC, merged