[BE-REFACTOR] 같은 정보를 담고 있는 파일들 합치기
woowacourse-teams/2024-pokerogue-helper pull request #311
Opened 2024-09-08 08:01 UTC by unifolio0

## 🍄 PR 확인 사항
PR이 다음 요구 사항을 충족하는지 확인하세요. :

- [x] API 명세서가 업데이트 혹은 작성이 되어 있나요?

## 현재 작업은 어떤 이슈를 해결한 것인지 설명해주세요.
> Issue Number: #302 

- [x] 중복 정보를 가지고 있는 파일들 통합

## 기존 코드에서 변경된 점이 있다면 설명해주세요. (추가 X)

- [x] 있음
- [ ] 없음

각각의 코드들을 살펴보며 리팩토링까지 진행하는 건 리소스가 많이 들 것 같아 우선 파일들만 지우고 PR보냅니다. 파일을 지우면서 오류가 나는 부분만 수정하고 그 외 기존의 코드를 크게 수정한 건 없습니다.

1. 각종 중복 정보를 가지고 있는 파일들을 지우고 각각 구현했던 도메인들 중 중복되는 도메인을 지우고 하나의 도메인만 참조하도록 수정했습니다.
2. 포켓몬 도감 상세 페이지에 타입 이미지도 같이 전달하도록 수정했습니다.
3. 배틀에서 기술 목록을 전달할 때 중복을 제거하여 전달하도록 수정했습니다.

2024-09-09 04:48 UTC, jongmee requested changes
먼저 상의하고 싶은 부분들을 리뷰로 남겨놨습니다 ! 가장 빨리 PR 날리셨네요 😊 최고~!

2024-09-09 04:48 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
> +        System.out.println(rivalPokemon.type1() + " : " + rivalPokemon.type2());
!!

2024-09-09 04:48 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
> +        }
이 부분을 보고 든 생각: Pokemon에 저장되는 기술들은 `Move`라는 객체로 저장되는게 좋지 않을까요 ?! 🤔 데이터가 저장된 형식에 구애받는 것 같아요 !

2024-09-09 04:48 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
> +            types.add(Type.findByEngName(rivalPokemon.type1()).orElseThrow());
`.orElseThrow()` 대신 커스텀 예외를 던져주면 좋을 것 같아요 ☺️

2024-09-09 04:56 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
> +        }
다시 생각해보니 리팩토링 때로 넘기는게 좋을 것 같네요.....! 보류!

2024-09-09 07:17 UTC, dwax1324 reviewed
비토 안녕하세요 
레벨4 첫 PR👍👍
코멘트 확인하시고 재요청 주세요~

2024-09-09 07:17 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/service/Pokemon2Service.java
> +                .map(r -> battleMoveRepository.findById(r).orElseThrow(IllegalArgumentException::new))
다음번에 제가 리펙토링할 때 에러메시지를 넣기 위해 `orElseThrow(() -> new IllegalArgumentException()))`를 적은 것인데 람다 표현식으로 바꾸셨네요.
다시 바꿔주실 수 있을까요?

2024-09-09 07:17 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +        if (!type2.getName().isEmpty() && !type2.getName().equals("Unknown")) {
이넘을 사용할 땐 이넘의 이름을 가져와서 비교하지 말고 이넘 그대로 비교하는게 어떨까요?

2024-09-09 07:17 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/config/Pokemon2DatabaseInitializer.java
> +        saveAbility();
93, 94줄처럼 일관성을 맞추어 보는 것이 어떨까요?

2024-09-09 07:25 UTC, dwax1324 requested changes
리뷰할 때 변경된 파일이 85개라서 놀랐는데요.
이렇게 큰 변화는 미리 공유를 해주시면 좋을 것 같습니다.

Sytem.out.prinln같은 디버깅은 리뷰요청 전에 확인 한번 해주시면 좋을 것 같아요.

그리고 삭제된 파일이 많아 리뷰하기가 힘들었는데요
다른 리뷰어분들 좌상단 `file filter`에 `deleted file` 체크하면 삭제된 파일은 리뷰할 때 제외됩니다.

2024-09-09 08:34 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/config/Pokemon2DatabaseInitializer.java
> +    private Map<String, List<String>> saveTms(String path) {
`Tms`는 쓰이긴 하지만... 너무 줄임말 같아서 전체를 작성해도 좋을 것 같네요! ☺️

2024-09-09 08:37 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/config/Pokemon2DatabaseInitializer.java
> +    }
이거 나중에 `Field` 자체를 감싸면 더 편하겠네요 `isEmptyField` 이런걸 만들어도 좋을 것 같습니다! ☺️

2024-09-09 08:41 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/service/Pokemon2Service.java
해당 클래스에서 `OrElseThrow()` 전부 이왕이면 작성해두는게 리팩토링때도 편할 것 같아요 ☺️

2024-09-09 08:47 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability2/service/AbilityService.java
> +                        getAbilityTypeResponses(abilityPokemon.type1(), abilityPokemon.type2())
사소하신 한데 이런거 그냥 필드 이름을 firstType, secondType으로 해줘도 괜찮겠네요. 🤔
1, 2 이런게 돌아다니니까 약간 저는 한눈에 안들어오는 느낌이라

얘를 감싸는 무언가가 생기더라도 `getPokemonType1` 보다는 `getPokemonFirstType` 이 가독성이 좋게 느껴져요
기분 탓일수도 있으니 다른 분들도 답글 달아주시면 굿입니당

2024-09-09 08:47 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
> +        }
지금 다 객체로 감싸버리고 싶음

2024-09-09 08:49 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/data/Pokemon.java
>  public record Pokemon(
Pokemon은 왜 `record`일까요?

2024-09-09 10:27 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/data/Pokemon.java
>  public record Pokemon(
@dwax1324 
저도 궁금해요! 알려주세요. 종이~

2024-09-09 12:40 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/data/Pokemon.java
>  public record Pokemon(
특별한 이유가 없다면 행동 하나라도 하는 객체들은 `class`로 리팩토링때 바꿔도 좋을것 같아요 ☺️

2024-09-11 01:58 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
> +        System.out.println(rivalPokemon.type1() + " : " + rivalPokemon.type2());
수정했습니다! 😊😊

2024-09-11 02:04 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
> +            types.add(Type.findByEngName(rivalPokemon.type1()).orElseThrow());
수정했습니다! ☺️☺️

2024-09-11 02:05 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/BiomePokemonType.java
> +        System.out.println(id);
수정했습니다! ☺️☺️

2024-09-11 02:05 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/service/Pokemon2Service.java
> +        //System.out.println(pokemon.abilityPassive() + " " + pokemon.abilityHidden() + " " + pokemon.ability1() + " " + pokemon.ability2());
수정했습니다! ☺️☺️

2024-09-11 02:12 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/service/Pokemon2Service.java
> +                if (abilityRepository.findById(ret.get(i).id()).orElseThrow() == hidden) {
수정했습니다! ☺️☺️

2024-09-11 02:13 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/service/Pokemon2Service.java
> +                .map(r -> battleMoveRepository.findById(r).orElseThrow(IllegalArgumentException::new))
https://github.com/woowacourse-teams/2024-pokerogue-helper/pull/311#discussion_r1749608523
위의 리뷰 반영하면서 제가 에러메시지 넣었습니다☺️☺️

2024-09-11 02:14 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/service/Pokemon2Service.java
수정했습니다! ☺️☺️

2024-09-11 02:16 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/service/Pokemon2Service.java
> +                                return new BiomeResponse("", "", "", List.of(), List.of());
아르세우스 같은 신화 포켓몬은 알로만 얻을 수 있고 바이옴에는 출현하지 않아서 포켓몬 정보에서 출현 바이옴이 없습니다☺️☺️

2024-09-11 02:26 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability2/service/AbilityService.java
> +                        getAbilityTypeResponses(abilityPokemon.type1(), abilityPokemon.type2())
타입 필드 이름만 수정했습니다! ☺️☺️

2024-09-11 02:31 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/config/Pokemon2DatabaseInitializer.java
> +    private Map<String, List<String>> saveTms(String path) {
수정했습니다! ☺️☺️

2024-09-11 04:00 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +        if (!type1.getName().isEmpty() && !type1.getName().equals("Unknown")) {
지금 타입을 각자가 구현하면서 타입 관련 클래스가 3개가 있어서 일단 러프하게 구현하다보니 위와 같이 나온 것 같습니다. 타입 관련 문제들은 이후에 mongo로 바꾸면서 해결될 것 같아 수정하지는 않았습니다! 밑에 타입 관련 리뷰들에는 이모지만 남기겠습니다.

2024-09-11 04:04 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/BattleService.java
> +        Pokemon myPokemon = pokemon2Repository.findById(myPokemonId)
수정했습니다! ☺️☺️

2024-09-11 04:09 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +        if (!type2.getName().isEmpty() && !type2.getName().equals("Unknown")) {
수정했습니다! ☺️☺️

2024-09-11 04:13 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/service/Pokemon2Service.java
> +                                    createTypeResponse(biome.getTrainerTypes())
dto가 바뀌면 안 된다고 해서 관련 코드 삭제했습니다!
근데 제가 보기엔 타입 정보를 전달하는 dto라는 역할이 일치해서 같이 써도 될 것 같은데 아마 이름 때문에 역할이 다르다고 보이는 것 같네요.
이후에 리팩토링할 때 타입 관련 dto는 하나로 통일하는 것도 괜찮을 것 같습니다.☺️☺️

2024-09-11 04:15 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/service/Pokemon2Service.java
> +                .filter(type -> !type.isEmpty())
왠진 모르겠는데 확인해보니 이미 enum으로 비교중이네요.🤔
아무튼 수정했습니다!

2024-09-11 04:17 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/config/BiomeDatabaseInitializer.java
> +        try (InputStream inputStream = getClass().getClassLoader().getResourceAsStream("data/biome/biome-pokemons.txt");
바이옴 아이디를 저장한 파일 기준으로 매핑했습니다! ☺️☺️

2024-09-11 04:25 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/service/Pokemon2Service.java
> +            Ability hidden = abilityRepository.findById(pokemon.abilityHidden()).orElseThrow();
리뷰를 보고 `be/develop` 브랜치를 확인해봤는데 종이가 말한 것과 관련된 코드가 없는 것 같습니다...
```
if (hidden != Ability.EMPTY) {
            ret.add(new PokemonAbilityResponse(pokemon.abilityHidden(), hidden.getName(), hidden.getDescription(),
                    false,
                    true));

            for (int i = 1; i < ret.size() - 1; i++) {
                if (Ability.findById(ret.get(i).id()) == hidden) {
                    ret.remove(i);
                    break;
                }
            }

        }
```

2024-09-11 04:27 UTC, jongmee approved these changes
굿!! 고생하셨습니다 ☺️

2024-09-11 04:29 UTC, unifolio0 commented
/noti

리뷰 반영 끝났습니다~ 
👀 이모지 단 것 중에 이건 반영하는 게 맞다 싶은 건 알려주세요

2024-09-12 02:04 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/service/Pokemon2Service.java
> +            Ability hidden = abilityRepository.findById(pokemon.abilityHidden()).orElseThrow();
`        if (hidden != Ability.EMPTY) {`
타입 이넘에서 해당하는 타입이 없을 때 `EMPTY` 객체를 반환했던 이유가 에러를 발생시키지 않기 위해서였습니다. 
다시 보니 이 코드가 어색해보였던 이유가 `Optional`을 사용하고 있는데 `pokemon.abilityHidden().isEmpty()`를 사용해서 검사를 하고 있습니다. 이러면 `Optional`을 사용할 이유가 없지 않을까요?

2024-09-12 02:10 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/service/Pokemon2Service.java
> +                                return new BiomeResponse("", "", "", List.of(), List.of());
네 그렇군요 없는 데이터가 `isEmpty()`가 이해하기 좀 힘든거 같아요

2024-09-12 02:28 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/service/Pokemon2Service.java
> +                                    createTypeResponse(biome.getTrainerTypes())
> dto가 바뀌면 안 된다고 해서 관련 코드 삭제했습니다!

이거와 관련해서 머지만 안하면 문제 없다고 하지 않으셨나요?
왜 제가 이걸 리뷰했는지 모르겠네요. 미리 삭제해주셨으면 안됐을까요?
 다른 팀원의 입장도 생각해주셨으면 좋겠습니다~

2024-09-12 02:42 UTC, dwax1324 approved these changes
고생하셨습니다

2024-09-12 02:55 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon2/service/Pokemon2Service.java
> +                                    createTypeResponse(biome.getTrainerTypes())
그 뒤에 mongo로 바꾸기로 정했고 나중에 merge시키기엔 api 수정요청도 들어왔고 제가 디스코드에 공유했습니다. 지금 올린 코드 위에 리팩토링한다고 들어서 수정한건데 대화 이후의 상황에 의해 당연히 수정되는게 맞는 것 같아요.

2024-09-12 12:13 UTC, jinchiim approved these changes
고생하셨습니다! 😋

2024-09-12 12:31 UTC, merged