[1.1.0/AN_FEAT] 배틀 선택 데이터 저장
woowacourse-teams/2024-pokerogue-helper pull request #324
Opened 2024-09-19 04:12 UTC by JoYehyun99

- closed #323
## 작업 영상
- PASS

## 작업한 내용
- 내 포켓몬, 기술, 상대 포켓몬 선택 데이터 저장 기능 구현
- `Datastore`을 사용하여 해당 데이터들을 저장했습니다.
- 현재 skill ID 값으로 해당 skill 데이터를 불러오는 API 는 따로 없어서 일단 이 전에 불러왔던 skill들을 map 형식으로 캐싱해두고, 나중에 find를 활용하여 해당하는 Skill 데이터를 찾을 수 있도록 설정했습니다.
- `Dex Repository` 에서도 포켓몬 ID를 넘기면 해당 `Pokemon` 을 반환해주는 메서드도 추가했습니다!
   -  기존에 있던 부분은 Detail을 반환하기 때문

## 🚀Next Feature

2024-09-20 05:20 UTC, sh1mj1 approved these changes
[안드로이드 공식 문서 코드랩](https://developer.android.com/codelabs/basic-android-kotlin-training-preferences-datastore?hl=ko#4) 의 예시 코드와 비슷하게 작성하셨군요~

날씨는 따로 저장하지 않아도 될지에 대해 리뷰 남겨두었습니다.
고생 많으셨습니다!!!!

2024-09-20 05:20 UTC, sh1mj1 commented on android/data/src/main/java/poke/rogue/helper/data/datasource/LocalBattleDataSource.kt
> +        battleDataStore.savePokemonWithSkill(pokemonId, skillId)
날씨는 따로 저장하지 않아도 될까요?

2024-09-20 06:37 UTC, JoYehyun99 commented on android/data/src/main/java/poke/rogue/helper/data/datasource/LocalBattleDataSource.kt
> +        battleDataStore.savePokemonWithSkill(pokemonId, skillId)
고민 중입니다,,,🥲 일단 그렇게 크리티컬한 부분은 아닌 것 같아서 저장 로직에서 제외하기는 했는데, 어떻게 생각하시나요 다들!!!!

2024-09-20 06:42 UTC, JoYehyun99 commented on android/data/src/main/java/poke/rogue/helper/data/model/PokemonWithSkillIds.kt
> +fun SavedPokemonWithSkill.toData() = PokemonWithSkillIds(pokemonId, skillId)
맞습니다!!!
Datastore 에 저장되는 객체 네이밍을 `XXEntity` 로 설정해도 되런지 ,,, 모르겠네요,,,!!!!

2024-09-20 06:44 UTC, JoYehyun99 commented on android/data/src/main/java/poke/rogue/helper/data/datasource/LocalBattleDataSource.kt
> +        battleDataStore.savePokemonWithSkill(pokemonId, skillId)
고민 중입니다,,,🥲 
일단 그렇게 크리티컬한 부분은 아닌 것 같아서 저장 로직에서 제외하기는 했는데,,,
어떻게 생각하시나요 다들!!!!

2024-09-20 07:41 UTC, kkosang approved these changes
이제 정말 포켓로그 하면서 사용할 수 있겠다 !!
고생하셨습니다 조대리님. 😁

2024-09-20 07:41 UTC, kkosang commented on android/data/src/main/java/poke/rogue/helper/data/datasource/LocalBattleDataSource.kt
> +        battleDataStore.savePokemonWithSkill(pokemonId, skillId)
날씨를 자주 선택하는 케이스가 적을 것 같긴한데..! 
선택했다가 날씨만 저장이 되지 않으면 😳할 것 같긴해요..

2024-09-22 11:58 UTC, murjune requested changes
고생하셨습니다 예니 👍  
코드 리뷰가 좀 늦어 미안합니다..  

몇 가지 논의해볼게 있는거 같아요!

2024-09-22 11:58 UTC, murjune commented on android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt
> +    private val cachedSkills: HashMap<Long, List<BattleSkill>> = hashMapOf()
여기서 MutableMap 이 아닌 HashMap 을 사용하신 이유가 있으실까용? 

> 참고) mutableMapOf() 를 사용하면 내부적으로 LinkedHashMap()을 사용합니당

2024-09-22 11:58 UTC, murjune commented on android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt
> +        }
캐시를 사용하신다면 AnalyticsLogger 도 연동 부탁드립니당!!

2024-09-22 11:58 UTC, murjune commented on android/local/src/main/java/poke/rogue/helper/local/datastore/BattleDataStore.kt
> +data class SavedPokemonWithSkill(val pokemonId: String, val skillId: String)
String id 2개면 띠로 저장하는 방식도 좋을 것 같아요!

2024-09-22 11:58 UTC, murjune commented
/noti 예니 코리 남겼습니다 한 번 봐주소~

2024-09-24 06:40 UTC, JoYehyun99 commented on android/data/src/main/java/poke/rogue/helper/data/datasource/LocalBattleDataSource.kt
> +    suspend fun savePokemon(pokemonId: String) = battleDataStore.savePokemon(pokemonId)
실수임당 ,, ㅎㅎ

2024-09-24 06:56 UTC, JoYehyun99 commented on android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt
> +        }
해당 부분은 포켓몬에 해당 하는 모든 스킬 리스트들을 캐싱하는데, 어떤식으로 로깅을 달아야하는지 모르겠어요 🥲
기존에 있는 `포켓몬, 스킬 선택에 대한 로깅`이 해당 캐싱에 영향을 받지는 않고 있습니다!

2024-09-24 06:57 UTC, JoYehyun99 commented on android/local/src/main/java/poke/rogue/helper/local/datastore/BattleDataStore.kt
> +data class SavedPokemonWithSkill(val pokemonId: String, val skillId: String)
오! 저장은 따로 해도 좋을 것 같네요 👀

2024-09-24 07:10 UTC, JoYehyun99 commented on android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt
> +    private val cachedSkills: HashMap<Long, List<BattleSkill>> = hashMapOf()
딱히 어떤 이유는 없고 그냥 습관(?) 입니다,,,ㅎㅎㅎ
주입 순서 저장의 차이라고만 알고 있습니다만 🤔

2024-09-24 08:17 UTC, kkosang commented on android/app/src/main/java/poke/rogue/helper/presentation/battle/selection/skill/SkillSelectionFragment.kt
> +            DefaultBattleRepository.instance(requireContext()),
오홍 화면 회전시에도 상태가 남아있는 객체는 Application Context로 관리하는군요.. 메모 📝

2024-09-24 11:32 UTC, JoYehyun99 commented
/noti 
날씨 저장 빼고 나머지 부분 반영했으요
스피너 못하겠다 🥲

2024-09-24 17:07 UTC, sh1mj1 approved these changes
LGTM~
날씨 저장  관련해서 너무 막히는가 싶으면 어떤 부분에서 막히는지 같이 이야기해봅시당~

2024-09-24 17:07 UTC, sh1mj1 commented on android/local/src/main/java/poke/rogue/helper/local/datastore/BattleDataStore.kt
> +        }
포켓몬과 스킬을 DataStore 에 저장할 때 하나의 객체로 묶어서 저장하지 않으니
`Json.encodeToString(data)`  코드가 없어져서 보기 좋네요~

2024-09-25 01:12 UTC, JoYehyun99 commented on android/local/src/main/java/poke/rogue/helper/local/datastore/BattleDataStore.kt
> +        val PAIR_SKILL_SELECTION_KEY = stringPreferencesKey("pair_skill_selection")
포켓몬 + 스킬, 포켓몬 을 구분하기 위함,,,입니다,,,,ㅎ

2024-09-25 10:23 UTC, kkosang commented
/noti
굿 리뷰 반영 확인했습니다 👍

2024-09-25 15:38 UTC, murjune requested changes
고생하셨습니다 예니~~  
데모데이 때 스킬 저장부분 어려웠던거 어필해봅시다 ㅋㅋㅋ

2024-09-25 15:38 UTC, murjune commented on android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt
> +    private val cachedSkills: HashMap<Long, List<BattleSkill>> = hashMapOf()
@JoYehyun99 반드시 적용할 내용은 아니지만 저는 `MutableMap`으로 변경하는 것을 제안드립니다.

```suggestion
    private val cachedSkills: MutableMap<Long, List<BattleSkill>> = hashMapOf()
```

반드시 적용할 내용은 아니지만 `MutableMap` 바꿔주셨으면 좋겠습니다!  

이유 1) 구현체 타입보다는 인터페이스 타입인 `MutableMap`으로 추상화하는 것이 추후 ConcurrentHashMap 이나 다른 LinkedHashMap 으로 바뀔 경우 더 유연하게 바꿀 수 있을 것입니다!  

---

참고) LinkedHashMap 가 필요한 경우가 뭐가 있을까 생각해보았는데, 아마 이를 활용해서 [LRU 캐시](https://velog.io/@haero_kim/LRU-Cache-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0)를 구현할 때 사용할 수 있을 것 같습니다.(쉽게 말해 가장 오래 사용안한 데이터 부터 삭제하는 캐시 전략입니다)

LinkedHashMap 은 `accessOrder` 라는 옵션과 사이즈 크기의 limit 를 지정해줄 수 있어 LRU 캐시를 구현할 수 있습니다.

2024-09-25 15:38 UTC, murjune commented on android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt
> +        }
로깅을 Activity 에서 찍고 있는 거라면 상관 없긴 합니다! 맞나용?

2024-09-25 15:38 UTC, murjune approved these changes
실수로 request changed 보냄..

2024-09-25 16:07 UTC, murjune commented
/noti 날씨 저장 해결했습니다~ 이건 따로 PR 분리해야 보기 편하실 거 같아서 예니 머지되면 올릴게요

2024-09-26 00:54 UTC, JoYehyun99 commented on android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt
> +        }
맞슴돠~

2024-09-26 01:03 UTC, merged