[BE-REFACTOR] Biome, Move 정보 MongoDB 사용하도록 리팩토링
woowacourse-teams/2024-pokerogue-helper pull request #335
Opened 2024-09-25 10:55 UTC by unifolio0

## 🍄 PR 확인 사항
PR이 다음 요구 사항을 충족하는지 확인하세요. :

- [x] API 명세서가 업데이트 혹은 작성이 되어 있나요?

## 현재 작업은 어떤 이슈를 해결한 것인지 설명해주세요.
> Issue Number: #332 

## 기존 코드에서 변경된 점이 있다면 설명해주세요. (추가 X)

- [x] 있음
- [ ] 없음

biome 및 move 전부 mongo로 작동하도록 수정

2024-09-25 11:23 UTC, unifolio0 commented
/noti

ci까지 통과했습니다!

2024-09-25 13:41 UTC, jongmee requested changes
고생하셨습니다!!! 👍 최고!!! 리뷰 좀 남겨봤어요 🕊️

(포켓몬 패키지가 좀 변경되었던데 종이 작업에서 충돌날까봐 살짝 걱정되네요 🥺)

2024-09-25 13:41 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/NativePokemon.java
> +        return !tier.contains("보스");
상수화해도 좋을 것 같습니다!

2024-09-25 13:41 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +                        .orElseThrow(() -> new GlobalCustomException(ErrorMessage.POKEMON_NOT_FOUND))
Stream 돌면서 id로 하나씩 조회하는 것보다 `ListCrudRepository`의 `findAllById`를 사용하는 게 더 효율적일 것 같아요! 

```java
 List<T> findAllById(Iterable<ID> ids);
```

2024-09-25 13:41 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +                    Biome nextBiome = biomeRepository.findById(nextBiomeInfo.getName())
여기도 `findAllById` 쓸 수 있을 것 같아요!

2024-09-25 13:41 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/controller/MoveController.java
> +        return new ApiResponse<>("포켓몬의 기술 리스트 불러오기에 성공했습니다.", moveService.findMove(id));
`포켓몬의 기술 불러오기에 성공했습니다.`가 더 어울리겠네요!

2024-09-25 13:41 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/service/MoveService.java
> +    private Map<Integer, List<MoveResponse>> findByDexnumberCache = new HashMap<>();
포켓로그 게임 업데이트에 맞춰 DB에 있는 데이터를 바꾼다면 캐시와 불일치하지 않을까요?? 🤔

그리고 인메모리에서는 `Map`으로 관리해서 id 말고 pokedexNumber로 조회하려면 또 다른 자료구조가 불가피했지만 지금은 MoveRepository에서 findByPokedexNumber로 조회할 수 있을 것 같아요!

2024-09-25 13:41 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/service/MoveService.java
> +    private Move findMoveById(String id) {
위에 있는 메소드와 밑에 있는 메소드에서 두 번 사용되는 것 같은데 요런 공통 사용 private 메소드는 맨 밑에 두기로 했던 것 같아요!

2024-09-25 13:41 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/PokemonMoveResponse.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.MOVE_CATEGORY_NOT_FOUND));
제가 저번에 짠 코드 같은데요 😅 이 상황에서(`MoveCategory.findByEngName`)에서 발생하는 예외는 백엔드 로직 혹은 데이터 문제 때문에 발생하는데, `404` 상태코드보다 `500`이 어울리는 것 같습니다 🥲 

(뭔가 내 이전 코드라서 머쓱) 어떻게생각하시나요?

2024-09-25 13:41 UTC, jongmee commented on backend/pokerogue/src/test/java/com/pokerogue/helper/battle/BattleServiceTest.java
>      @Test
메인 코드와 마찬가지로 테스트 코드도 이전이 필요할 것 같아요! MoveServiceTest에 들어가면 되지 않을까요?

2024-09-25 16:37 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/PokemonMoveResponse.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.MOVE_CATEGORY_NOT_FOUND));
요거 저는 의견 종이 코멘트에 달았습니다!

2024-09-26 04:12 UTC, jinchiim requested changes
안녕하세요 비토! 수고 많으셨습니다!

리팩토링도 함께 가져가기로 했으니 보이는 부분 전부 리뷰해봤어요!
확인 부탁드려요! ☺️

2024-09-26 04:12 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/service/MoveService.java
> +        return MoveResponse.from(findMoveById(id));
이왕이면 파라미터 안에 메서드는 `controller` 반환이 아니라면 분리해주시면 좋을 것 같아요!
파라미터가 어떤 값인지 알기가 어려워 흐름으로 읽기가 힘든것 같아요 🤔

```suggestion
    public MoveResponse findMove(String id) {
        Move move = findMoveById(id);
        return MoveResponse.from(move);
```

2024-09-26 04:12 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
>                  getTrainerPokemons(biome),
`biome`이 존재하지 않는 경우 에러 발생 테스트가 필요해보입니다.  🤔

2024-09-26 04:12 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/service/MoveService.java
해당 클래스 변화가 많고 캐싱을 하는 것 같은데, 캐싱을 유지할지와는 별개로
캐시가 목적이라면 정말 캐싱하는지 테스트가 필요하지 않나요?? 🤔

없는 경우 새로운 것을 만들고 있는 경우 캐싱된 객체를 가져오는지에 대한 확인이 필요해보여요!

2024-09-26 04:12 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/service/MoveService.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.MOVE_NOT_FOUND));
정말 없는 경우 에러를 서비스에서 발생시키는 지 확인하는 테스트가 필요해 보입니다! ☺️

2024-09-26 09:38 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/BiomePokemonType.java
>                  .findFirst()
반영했습니다! ☺️☺️

2024-09-26 09:39 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/NativePokemon.java
> +        return !tier.contains("보스");
반영했습니다! ☺️☺️

2024-09-26 09:41 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/controller/MoveController.java
> +        return new ApiResponse<>("포켓몬의 기술 리스트 불러오기에 성공했습니다.", moveService.findMove(id));
수정했습니다! ☺️☺️

2024-09-26 09:56 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +                        .orElseThrow(() -> new GlobalCustomException(ErrorMessage.POKEMON_NOT_FOUND))
해당 메소드를 확인하고 적용해 봤는데 해당 메소드는 존재하지 않는 값에 대해 에러 처리를 하는 것이 아닌 그냥 제외하는 것 같아요.
차라리 예외를 발생시키는 게 더 적절하다고 판단해 변경을 하진 않았는데 미아는 어떻게 생각하나요?

2024-09-26 09:59 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +                    Biome nextBiome = biomeRepository.findById(nextBiomeInfo.getName())
https://github.com/woowacourse-teams/2024-pokerogue-helper/pull/335#discussion_r1776754560

여기에 의견 달았습니다!☺️☺️

2024-09-26 10:01 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/NativePokemon.java
> +@AllArgsConstructor
수정했습니다! ☺️☺️

2024-09-26 10:01 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/NextBiome.java
> +@AllArgsConstructor
수정했습니다! ☺️☺️

2024-09-26 10:01 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/Trainer.java
> +@AllArgsConstructor
수정했습니다! ☺️☺️

2024-09-26 10:02 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/data/Move.java
> +@AllArgsConstructor
수정했습니다! ☺️☺️

2024-09-26 10:07 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/controller/MoveController.java
> +    public ApiResponse<List<MoveResponse>> moveByPokemonList(@RequestParam("pokedex-number") Integer pokedexNumber) {
수정했습니다! ☺️☺️

2024-09-26 10:11 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/controller/MoveController.java
> +        log.info("---- URI : {}, Param : {}", "/api/v1/move/{id}", id);
수정했습니다! ☺️☺️

2024-09-26 10:13 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/service/MoveService.java
> +        return MoveResponse.from(findMoveById(id));
수정했습니다! ☺️☺️

2024-09-26 10:17 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/service/MoveService.java
> +    private Move findMoveById(String id) {
수정했습니다!

2024-09-26 10:30 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/service/MoveService.java
> +    private Map<Integer, List<MoveResponse>> findByDexnumberCache = new HashMap<>();
`PokedexNumber`가 중복되는 포켓몬들이 있어서 에러 터질 줄 알았는데 아니라고 하네요😅😅

수정했습니다! ☺️☺️

2024-09-26 10:32 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/service/MoveService.java
> +    private void initFindByDexnumberCache() {
해당 메소드 삭제했습니다! ☺️☺️

2024-09-26 10:32 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/service/MoveService.java
캐싱 삭제했습니다! ☺️☺️

2024-09-26 10:57 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/service/MoveService.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.MOVE_NOT_FOUND));
작성했습니다! ☺️☺️

2024-09-26 10:58 UTC, unifolio0 commented on backend/pokerogue/src/test/java/com/pokerogue/helper/battle/BattleServiceTest.java
>      @Test
관련 테스트 코드 작성했습니다! ☺️☺️

2024-09-26 11:01 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
>                  getTrainerPokemons(biome),
작성했습니다! ☺️☺️

2024-09-26 11:06 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/PokemonMoveResponse.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.MOVE_CATEGORY_NOT_FOUND));
확실히 저희 서비스 특성상 500이 더 어울릴 것 같아요! 수정했습니다! ☺️☺️

2024-09-26 11:38 UTC, jongmee requested changes
비토 고생하셨습니다!! 리뷰 아주 조금 달았어요 ㅎㅎ..

2024-09-26 11:38 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/NativePokemon.java
> +    private static final String BOSS = "보스";
여기 밑에 개행이 빠진 것 같아요!

2024-09-26 11:38 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +                        .orElseThrow(() -> new GlobalCustomException(ErrorMessage.POKEMON_NOT_FOUND))
저는 그런 경우에 조회된 데이터 개수(여기에서는 포켓몬 개수)와 id 개수(포켓몬 id 개수)가 같은지 비교합니다! 이 방법은 어떤가요? 개수가 다를 때 예외를 던지면 예외처리도 던질 수 있어요 😊

2024-09-26 11:38 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/service/MoveService.java
> +    private Map<Integer, List<MoveResponse>> findByDexnumberCache = new HashMap<>();
Move에서는 `PokedexNumber`가 중복되지 않아요! 👍

2024-09-26 11:39 UTC, jongmee commented
/noti 비토! 리뷰 달았어요 ☺️ 노티 기능 정말 편하네..

2024-09-26 11:43 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/data/NativePokemon.java
> +    private static final String BOSS = "보스";
수정했습니다! ☺️☺️

2024-09-26 11:55 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +                        .orElseThrow(() -> new GlobalCustomException(ErrorMessage.POKEMON_NOT_FOUND))
수정했습니다! 😊😊

2024-09-26 12:01 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +                    Biome nextBiome = biomeRepository.findById(nextBiomeInfo.getName())
여기는 오히려 쓰면 더 복잡해질 것 같아요...
`biome`에서 `nextBiome`을 뽑아온 것을 `name`만 뽑아서 `List<String>`으로 만들어 준 뒤 `findAllById`로 얻어온 리스트를 다시 도는데 `NextBiomeResponse`를 만들기 위해선 `nextBiome`에 있는 `percentage`가 필요해요.

잘 설명했는진 모르겠는데 제가 보기엔 더 복잡해질 것 같아요...😢😢

2024-09-26 12:03 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +                        s3Service.getPokerogueTypeImageFromS3(type),
생각해보니 그게 더 좋을 것 같아요! 그런데 미아가 언급했던 충돌이 발생할 수도 있으니 지금 작업이 끝나고 리팩토링 할 때 하는 게 좋을 것 같아요!

2024-09-26 12:04 UTC, unifolio0 commented
/noti

미아랑 폴라 리뷰 반영 완료

2024-09-26 12:10 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +                    Biome nextBiome = biomeRepository.findById(nextBiomeInfo.getName())
오호 그렇군요 다음 바이옴은 숫자도 많지 않아서 괜찮을 거 같네요!

2024-09-26 12:10 UTC, jongmee approved these changes
어프룹! 🎉

2024-09-27 00:22 UTC, dwax1324 approved these changes

2024-09-27 00:22 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/service/MoveService.java
> +        return makeMoveResponse(pokemons.get(0));
없는 도감번호라면 예외가 발생할거 같아요🪶
리턴전에 개행!

2024-09-27 00:22 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/PokemonDetailResponse.java
> +        List<PokemonMoveResponse> eggPokemonMoveRespons,
오타🐠

2024-09-27 00:23 UTC, dwax1324 commented
비토 고생하셨습니다🦎
이미 리펙터링이 많이 진행된거 같아서 짧게 남겨요

2024-09-27 01:26 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/PokemonDetailResponse.java
> +        List<PokemonMoveResponse> eggPokemonMoveRespons,
수정했습니다! ☺️☺️

2024-09-27 01:27 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/service/MoveService.java
> +        return makeMoveResponse(pokemons.get(0));
수정했습니다! ☺️☺️

2024-09-27 02:08 UTC, jinchiim approved these changes
Approve 했습니다!

2024-09-27 02:45 UTC, merged