[BE-REFACTOR] 포켓몬 정보 MongoDB 리팩토링
woowacourse-teams/2024-pokerogue-helper pull request #336
Opened 2024-09-25 13:17 UTC by dwax1324

## 🍄 PR 확인 사항
PR이 다음 요구 사항을 충족하는지 확인하세요. :

- [x] API 명세서가 업데이트 혹은 작성이 되어 있나요?

## 현재 작업은 어떤 이슈를 해결한 것인지 설명해주세요.
> Issue Number: 

## 기존 코드에서 변경된 점이 있다면 설명해주세요. (추가 X)

- [x] 있음
- [ ] 없음

- 포켓몬 레포지토리만 몽고디비 적용
- 데이터 기본 생성자 추가, 연관 데이터 클래스 필드 추가
- `Type`은 바이옴에서 사용하고 있어서 지우지 않음
- 포케 덱스 넘버가 DTO에서 기존에 Long이어서 일단 Integer에서 업캐스팅함
- `MongoConfiguration` 추가, 타입컨버터와 아이템 컨버터 `MongoConfiguration`에 추가
- 업데이트된 진화 아이템, 폼 변환 아이템 `EvolutionItem`이넘에 추가

2024-09-25 16:02 UTC, jongmee requested changes
종이 고생하셨습니다!! 리뷰 남겨놨어요 😊 화이팅!!!

그리고 테스트 코드가 없는데 정말 단순한 로직이 아니라면 테스트 코드가 필요할 것 같아요~!

2024-09-25 16:02 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +                )
PokemonService는 전체적으로 메소드 길이가 길어서 다른 클래스로 분리하는 것도 좋을 것 같아요!

2024-09-25 16:32 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/MoveResponse.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.TYPE_MATCHING_ERROR));
개인적으로 상태코드는 저희끼리 정하면 된다는 파라서 저는 자원이 없는 경우에는 명시적으로 NOT_FOUND를 선호하긴 합니다!
`500` 은 너무 많아서 메시지로 구분해야하니 좀 불편하다 느껴져요 🤔

2024-09-25 16:33 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/data/EvolutionItem.java
> +    public static Optional<EvolutionItem> findById(String id) {
해당 부분을 저도 사용하고 있는데, 결국은 이름을 `Id`로써 사용하게 될 것 같아 저도 `Id` 라는 명칭을 넣어 사용했는데
별로일까요?? 

아이템 도감의 개발은 이미 정해진 부분이라 오히려 `id` 가 전 좀더 어울린다고 생각했어요!

2024-09-25 16:33 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/config/ReadItemConverter.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.EVOLUTION_NOT_FOUND));
요거 저희끼리 정해야겠네요

2024-09-25 16:35 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +                        createTypeResponse(pokemon)))
> 이미지 url 자체를 코드에 넣기 보다 캐싱하는게

요거 혹시 이해를 못해서 자세한 설명이 가능할까요?? ☺️

2024-09-26 01:11 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/MoveResponse.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.TYPE_MATCHING_ERROR));
에러 로깅할 때, 통계할 때나 클라이언트가 이해할 때 404면 오해할 수 있지 않을까요??

이 에러는 서버 원인으로 발생하는 에러니 500으로 간주하고 에러 로그로 원인을 파악해야 한다고 생각합니다 ☺️ 404로 한다면 다른 404와 구별해서 저희가 빠르게 원인을 파악할 수 있을까요?? 디테일한 대처를 대비하면 그것도 괜찮다고 생각합니다!

2024-09-26 01:13 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/data/EvolutionItem.java
> +    public static Optional<EvolutionItem> findById(String id) {
> 아이템 도감의 개발은 이미 정해진 부분

오 여기까지 생각하지 못했네요 🤔 일단 `findById` 로 남기는게 좋을 것 같네요!!

2024-09-26 01:14 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/data/EvolutionItem.java
> +    public static Optional<EvolutionItem> findById(String id) {
resolve 누르고 싶지만 다른 사람들이 읽기 불편할 것 같아 남겨둘게용

2024-09-26 01:14 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/config/ReadItemConverter.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.EVOLUTION_NOT_FOUND));
좋아유

2024-09-26 01:24 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +                        createTypeResponse(pokemon)))
전자는 '상수로 관리하자'가 맞습니다! 풀어서 써볼게요

### 이미지 URL을 상수로 관리
상수로 이미지 URL prefix를 두고 postfix를 데이터 + id를 조합해서 쓴다.
그런데 생각해보니 enum에 박아 놓는게 아니라면 캐싱이 더 아름답다고 생각했습니다 🤔

### 캐싱
S3ImageClient로부터 이미지 한꺼번에 받아오고 어플리케이션에서 캐싱해서 쓴다.

이미지 URL은 변경되지 않는다고 가정했고 S3ImageClient를 통해 url을 매 요청마다 받아오는 것보다 이게 더 좋지 않을까? 해서 제안해봤습니다! (CDN을 쓰지만 이미지 URL이 항상 똑같으니까..)

> Prefix를 만들어주는 애만 따로 만들어서 관리

폴라가 언급한건 제가 말한 어플리케이션 캐싱을 하지 않아도 추후 도입하면 좋을 만한 리팩토링 사항이네요! 굿

2024-09-26 04:29 UTC, jinchiim requested changes
안녕하세요 종이!

코드 잘 확인했고 고생하셨습니다!
전반적으로 리팩토링을 하기로 했기 때문에 그런 부분들과 테스트 보강을 위주로 작성했어요! 

확인해주세요! ☺️

2024-09-26 04:29 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +                        .orElseThrow(() -> new GlobalCustomException(ErrorMessage.POKEMON_NOT_FOUND))
`biomePokemon`이 없는 경우 서비스에서 에러를 발생하는지 확인하는 테스트가 필요해보입니다! ☺️

2024-09-26 04:29 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/config/MongoConfiguration.java
> +        mongoConverter.setMapKeyDotReplacement("#DOT#");
상수 선언 해주면 좋겠네요! ☺️

2024-09-26 04:29 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/config/ReadTypeConverter.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.POKEMON_TYPE_NOT_FOUND));
엇... 이거 왜 만드셧죠

2024-09-26 04:29 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/data/FormChange.java
> +@AllArgsConstructor
`@AllArgsConstructor` 가 언제 필요할까요?? 비토도 그렇고 두분 다 쓰셔서 궁금하네요 ☺️

2024-09-26 04:29 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/data/Pokemon.java
> +@AllArgsConstructor
dito

2024-09-26 04:29 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/MoveResponse.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.TYPE_MATCHING_ERROR));
오 서버 원인이니 500이라는 접근도 나쁘지 않네요 🤔
디테일한 대처를 원한 것이긴 한데 해당 접근도 나쁘지 않아보입니다

2024-09-26 04:29 UTC, jinchiim commented on backend/pokerogue/src/test/java/com/pokerogue/helper/battle/BattleServiceTest.java
> +//    @DisplayName("배틀 예상 결과를 계산한다.")
필요없으면 주석 처리말고 그냥 지워주셔도 될 듯 합니다! ☺️

2024-09-26 04:29 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +        for (int depth = 0; depth < evolutions.size(); depth++) {
`depth`가 깊이를 의미하는 것 같은데 정확히 무엇인지 잘 모르겠습니다.. 🥹
더 명확한 이름이 없을까요?

2024-09-26 04:29 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +                        false))
해당 부분이 반복되는 것 처럼 보이는데 정적 팩토리 메서드 만들어도 좋아보입니다! ☺️

2024-09-26 04:29 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +
밑에 사용하지 않는 개행이 있네요!

2024-09-26 04:29 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +        List<PokemonBiomeResponse> biomeResponse = createBiomeResponse(pokemon.getBiomeIds());
전반적으로 해당 클래스에서 이왕이면 메서드 안에 메서드는 분리하는 것이 좋아보입니다! 
흐름대로 코드를 읽는 편인데 어떤 값을 받고 어떤 값을 만들어내는지가 보이지 않아 개인적으로 흐름이 끊기네요ㅜ 🥹

코드가 짧아진다는 장점은 있겠지만 읽기는 더 불편한 것 같아요 
다른 분들도 의견 주세요! ☺️

2024-09-26 04:29 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +                            return new MoveResponse(
`return` 전에 개행! 🐕

2024-09-26 05:54 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/config/MongoConfiguration.java
> +public class MongoConfiguration {
컨버터는 머지 후에 한번에 정리하는게 낫지 않을까요? ✨

2024-09-26 05:54 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/config/MongoConfiguration.java
> +        mongoConverter.setMapKeyDotReplacement("#DOT#");
넹✨

2024-09-26 05:54 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/config/ReadItemConverter.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.EVOLUTION_NOT_FOUND));
500이 괜찮겠네요 ✨

2024-09-26 05:54 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/config/ReadTypeConverter.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.POKEMON_TYPE_NOT_FOUND));
데이터가 안불러와져서요✨

2024-09-26 05:54 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/data/EvolutionItem.java
> +    ABOMASITE("눈설왕나이트"),
진화 아이템이랑 폼변환 아이템이랑 다르게 쓰이는 곳이 있나요?
있으면 이넘을 Item으로 바꾸고 두번째 필드로 evolution, form 요런식으로 구분해도 되거 같고
없으면 굳이 구분할 필요가 없을 거 같네요 ✨

2024-09-26 05:54 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/MoveResponse.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.TYPE_MATCHING_ERROR));
500으로 가시죠 ✨

2024-09-26 05:54 UTC, dwax1324 commented on backend/pokerogue/src/test/java/com/pokerogue/helper/battle/BattleServiceTest.java
> +//    @DisplayName("배틀 예상 결과를 계산한다.")
믿고 지웁니다✨

2024-09-26 05:54 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +                        .orElseThrow(() -> new GlobalCustomException(ErrorMessage.POKEMON_NOT_FOUND))
에공 여긴 바이옴이라 커밋되면 안된는건데✨ 푸쉬가 잘못됐네요

2024-09-26 05:54 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/global/exception/ErrorMessage.java
> -
플러그인 `Save Actions Tool`이 고장났어요 ㅠ✨

2024-09-26 05:54 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/data/FormChange.java
> +@AllArgsConstructor
필요가 없네요 지웠어요✨

2024-09-26 05:54 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/data/Pokemon.java
> +@AllArgsConstructor
otid

2024-09-26 05:54 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/dto/MoveResponse.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.TYPE_MATCHING_ERROR));
사용자 입력이 없기 때문에 URL 잘못 입력 아니면 모든 NOTFOUND는 500이겠네요

2024-09-26 05:55 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/config/PokemonDatabaseInitializer.java
> -package com.pokerogue.helper.pokemon.config;
삭제했습ㄴ디ㅏ

2024-09-26 05:56 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> -
복구했습니다✨

2024-09-26 05:57 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +        for (int depth = 0; depth < evolutions.size(); depth++) {
추천해주세요

2024-09-26 05:58 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +                        false))
괜찮겠네요✨

2024-09-26 05:58 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +
삭제했습니다✨

2024-09-26 06:02 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +        List<PokemonBiomeResponse> biomeResponse = createBiomeResponse(pokemon.getBiomeIds());
매개변수로 메서드를 직접 대입하지 말자는 얘기 맞겠죠?

2024-09-26 06:03 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +                            return new MoveResponse(
개행했습니다✨

2024-09-26 06:21 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +                        createTypeResponse(pokemon)))
저도 항상 저 긴문자열을 군덴군데써야할까 생각하긴했습니다만

S3 URL이 바뀔 수 없나요?
바뀔 일이 없으면 상수로 빼는게 나을듯합니다 ✨

2024-09-26 06:22 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +                )
네 분리해볼게요

2024-09-26 09:34 UTC, unifolio0 approved these changes
폴라랑 미아가 열심히 달아줘서 간단한 것만 달았기에 approve합니다!

구현 수고하셨습니다! 👍

2024-09-26 09:34 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +        ).orElse(PokemonBiomeResponse.EMPTY);
현재 바이옴이 없으면 빈 배열을 받기 때문에 이 부분에서 `Empty`를 보내주는게 아니라 예외 처리를 해야 될 것 같아요!☺️☺️

2024-09-26 12:01 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +        List<PokemonBiomeResponse> biomeResponse = createBiomeResponse(pokemon.getBiomeIds());
다른 분들은 어떻게 생각하실까요?? 의견 주시면 감사합니다!

2024-09-26 12:02 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/config/ReadTypeConverter.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.POKEMON_TYPE_NOT_FOUND));
요거 제가 만들어서 머지 되고 없애면 되겠네요 🤔

2024-09-26 12:02 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/BiomeService.java
> +                        .orElseThrow(() -> new GlobalCustomException(ErrorMessage.POKEMON_NOT_FOUND))
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 좋습니다

2024-09-26 12:02 UTC, jinchiim commented on backend/pokerogue/src/test/java/com/pokerogue/helper/battle/BattleServiceTest.java
> +//    @DisplayName("배틀 예상 결과를 계산한다.")
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-09-26 12:03 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +        for (int depth = 0; depth < evolutions.size(); depth++) {
무엇인지 모르겠어서 추천이 어렵습니다 🥹
해당하는 변수가 정확히 무슨 이유로 사용되어지고 있는 것일까요??

2024-09-26 12:09 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +        List<PokemonBiomeResponse> biomeResponse = createBiomeResponse(pokemon.getBiomeIds());
코드 길게 만들어.

2024-09-26 12:10 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +        for (int depth = 0; depth < evolutions.size(); depth++) {
다시 하면 굿~

2024-09-26 18:55 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +                .orElse(0);
진화로직은 데이터가 바뀌어서 작업 전이라고 미리 적어놨어야 했네요~😇

2024-10-07 14:17 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/data/Evolution.java
> +    private String item;
아이템 도감 추가하면서 합치면 좋을거같네요!

2024-10-07 14:42 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +                        createTypeResponse(pokemon)))
인메모리 캐시를 삭제했습니다!

2024-10-07 14:43 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +                .orElse(0);
전반적인 진화 리펙터링을 하였습니다.

2024-10-07 14:45 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +                )
현재 서비스가 클래스가 매핑 작업밖에 하는 것이 없어서..
비교적 복잡한 진화는 따로 만들었습니다!

2024-10-07 14:45 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +        ).orElse(PokemonBiomeResponse.EMPTY);
예외처리로 변경했습니다!

2024-10-07 14:46 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/data/EvolutionItem.java
> +    ABOMASITE("눈설왕나이트"),
아이템 도감이 생기니 그 때 논의해봐도 좋을 것 같습니다

2024-10-08 01:26 UTC, dwax1324 commented
/noti
리뷰 반영 완료했습니다
늦어서 정말 죄송합니다 😢

## `PokemonValidator` 포켓몬 데이터 검증 클래스 추가 
- 데이터에 대한 메타정보를 갖고 있음 (예: 포켓몬의 총 개수)
- `PokemonValidatorTest`에선 검증 로직에 관한 예외 발생 테스트를 한다.
   - 테스트 계속 추가 예정..
- `PokemonDataTest`에선 실제 데이터에 대한 테스트가 통과되는지 검사한다.
    - 잘못된 데이터 때문에 통과하지 못하고 있는 테스트는 `Disabled`처리.
    
# 진화 관련

포켓몬에 대한 진화 배열이 주어졌을 때 각 포켓몬에 대한 `Depth`만 구하는 것으로 단순화 시킴.
`Depth`란 진화를 표현한 트리가 있을 때 진화 깊이를 뜻함. (예: 이상해씨=0 -> 이상해풀=1 -> 이상해꽃=2)


## `EvolutionService`
## `EvolutionContext`
## `BufferedQueue`
## `TreeDepthCalculator`

##   테스트, 에러메시지 추가
- 잘못된 데이터로 인한 상태코드는 모두 500으로 변경

## `ImageUrl` 간단한 이미지 상수 저장 이넘
- 논의가 되지 않아서 일단 대충 구현

2024-10-10 01:20 UTC, jinchiim requested changes
개행🐶 이랑  접근제어자만 한번 봐주세요! 😋

2024-10-10 01:20 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/config/ImageUrl.java
> +    BASE_URL("https://dl70s9ccojnge.cloudfront.net/pokerogue-helper/pokerogue"),
개행 해주세요! ☺️

2024-10-10 01:20 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/data/PokemonValidator.java
> +    private static final int POKEMON_SIZE = 1446;
개행! 🐕

2024-10-10 01:20 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/data/PokemonValidator.java
> +    static void validatePokemonSize(int pokemonCount) {
`default` 고민 해봅시다 🤔

2024-10-10 01:20 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/BufferedQueue.java
> +    private final Queue<T> value;
개행~!

2024-10-10 01:20 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/EvolutionContext.java
> +    private final List<Evolution> evolutions;
개행~!

2024-10-10 01:20 UTC, jinchiim commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/data/FakeEvolution.java
> +    private String from;
개행~!

2024-10-10 01:20 UTC, jinchiim commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/data/FakePokemon.java
> +    private FakePokemon(){
개행~!

2024-10-10 01:20 UTC, jinchiim commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/service/BufferedQueueTest.java
> +class BufferedQueueTest {
`public` 돌려줘~

2024-10-10 01:20 UTC, jinchiim commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/service/EvolutionContextTest.java
> +class EvolutionContextTest {
`public` 돌려줘~

2024-10-10 01:25 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +                )
너무 깔끔해졌네요!!!!!!!!!! 굿

2024-10-10 01:25 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +                .orElse(0);
따봉 백 개 입니다. 👍

2024-10-10 04:52 UTC, jongmee requested changes
종이!!! 서비스 코드가 정말 깔끔해졌고 데이터 테스트도 완벽하네요 😊👍 저번 리뷰들은 다 resolve 처리했습니다! 추가 리뷰 몇 개 달아놨어요 😉

2024-10-10 04:52 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/TreeDepthCalculator.java
> +                    .forEach(bufferedQueue::add);
👍👍👍 너무 이해하기 쉽네요!!! 최고

2024-10-10 04:52 UTC, jongmee commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/data/FakeEvolution.java
> +public class FakeEvolution extends Evolution {
저번에 잠깐 얘기했던 대로 Fake 객체를 일일이 만드는 것보다 Collection(여기에서는 Evolution)에 생성자 등을 추가하는게 더 좋을 것 같아요 ☺️

2024-10-10 04:52 UTC, jongmee commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/data/FakeEvolution.java
> +public class FakeEvolution extends Evolution {
Evolution이 변경되면(메소드 추가 등) Fake 객체를 항상 일관되게 맞춰줘야 하는데 놓치기 쉬울 것 같아서요!

2024-10-10 04:52 UTC, jongmee commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/PokeomonControllerTest.java
> +
요런 테스트들을 `package com.pokerogue.helper.data`에 넣으면 좋을 것 같아요!

2024-10-10 04:52 UTC, jongmee commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/data/PokemonDataTest.java
> +}
오 이 테스트들도 `package com.pokerogue.helper.data` 패키지에 넣는게 적절해보이네요 🙈

2024-10-10 04:52 UTC, jongmee commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/service/EvolutionContextTest.java
> +        Assertions.assertThat(context.getDepthOf("E")).isEqualTo(4);
`assertAll`을 사용한다면 테스트 결과 확인이 쉬워질 것 같아요!

2024-10-10 12:58 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/config/ImageUrl.java
> +    BASE_URL("https://dl70s9ccojnge.cloudfront.net/pokerogue-helper/pokerogue"),
수정했습니다!

2024-10-10 12:58 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/data/PokemonValidator.java
> +    private static final int POKEMON_SIZE = 1446;
수정했습니다!

2024-10-10 12:59 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/BufferedQueue.java
> +    private final Queue<T> value;
수정했습니다!

2024-10-10 12:59 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/EvolutionContext.java
> +    private final List<Evolution> evolutions;
수정했습니다!

2024-10-10 12:59 UTC, dwax1324 commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/data/FakeEvolution.java
> +    private String from;
수정했습니다!

2024-10-10 12:59 UTC, dwax1324 commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/data/FakePokemon.java
> +    private FakePokemon(){
수정했습니다!

2024-10-10 12:59 UTC, dwax1324 commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/service/BufferedQueueTest.java
> +class BufferedQueueTest {
수정했습니다!

2024-10-10 12:59 UTC, dwax1324 commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/service/EvolutionContextTest.java
> +class EvolutionContextTest {
수정했습니다!

2024-10-10 13:03 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/EvolutionContext.java
> +                Collectors.mapping(Evolution::getTo, Collectors.toList())));
적용했습니다!

2024-10-10 13:10 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/EvolutionContext.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.POKEMON_NOT_FOUND));
이부분은 모든 포켓몬의 `getTo`를 먼저 찾은 후, `getFrom`을 찾아야해서 Stream.of 연산을 사용하였습니다!
(진화 가능한 포켓몬이라면 getTo의 evolution을 가져오고, 루트 포켓몬이라면 getFrom의 evolution을 가져온다.)

순서에 의존적이고 가독성이 좋은 코드는 아닌 거 같네요!
더 좋은 방법이 있을지 고민해보겠습니다😲

2024-10-10 13:12 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/TreeDepthCalculator.java
> +                .collect(Collectors.groupingBy(node -> node, Collectors.summingInt(cnt -> 1)));
훨씬 깔끔하네요 👍

2024-10-10 13:13 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/TreeDepthCalculator.java
> +                .distinct()
포매팅이 자꾸 말썽이네요 ㅠㅠ 
적용했습니다!

2024-10-10 13:21 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/TreeDepthCalculator.java
> +                .collect(Collectors.toCollection(LinkedList::new)));
역시 테코톡 java collection framework 👍 👍
궁금해서 찾아보니 캐시미스,null지원 여부,노드 생성으로 인한 jvm 로 성능이 갈리는군용.. [출처](https://stackoverflow.com/questions/6163166/why-is-arraydeque-better-than-linkedlist)
적용했습니다~!!

2024-10-10 13:31 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/TreeDepthCalculator.java
> +        allNodes.forEach(node -> depths.putIfAbsent(node, 0));
세팅하는 부분은 메서드로 따로 추출하였습니다..!

2024-10-10 13:39 UTC, dwax1324 commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/data/PokemonDataTest.java
> +}
`package com.pokerogue.helper.data` 패키지로 옮겼습니다!!

2024-10-10 13:39 UTC, dwax1324 commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/PokeomonControllerTest.java
> +
넵!!

2024-10-10 13:41 UTC, dwax1324 commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/service/EvolutionContextTest.java
> +        Assertions.assertThat(context.getDepthOf("E")).isEqualTo(4);
확실히 그렇겠네요☺️  assertAll을 추가하였습니다~

2024-10-10 13:50 UTC, dwax1324 commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/data/FakeEvolution.java
> +public class FakeEvolution extends Evolution {
Pokemon의 빈생성자의 접근제어를 해제하고 Setter를 열었습니다. 
AllArgs 하면 생성자가 매개변수가 너무 많아져서... 테스트니까 그래도 되려나요? 더 좋은 방법 있으면 알려주세요!

2024-10-10 13:55 UTC, dwax1324 commented
/noti
리뷰반영완

2024-10-10 17:55 UTC, jinchiim approved these changes
고생하셨어요 종이!
미아까지 머지 이후 테스트 작성하면서 궁금하거나 리팩토링 욕심이 나는 부분들은 따로 연락드리도록 할게요! 

130개의 코멘트 동안 수고하셨습니다 ㅋㅋㅋㅋ 🤣

2024-10-11 02:47 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/TreeDepthCalculator.java
> +                .collect(Collectors.toCollection(LinkedList::new)));
ㅋㅋㅋㅋㅋ 테코톡 덕에 알게 된 거 맞네요.. 😊 맞아요 ArrayDeque은 내부에 배열로 구현되어 있어서 CPU 캐시를 최대한 활용할 수 있고 오버헤드가 적습니다 ㅎㅎ 배열이라 크기가 한 번에 확장될 때는 LinkedList가 더 좋지 않을까 했는데 그 때 직접 실험해보니까 왠만하면 ArrayDeque이 빠르더라고요! (배열 크기 키울 때 지수적으로 증가시키고 System 함수를 사용합니다)

2024-10-11 02:50 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/EvolutionContext.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.POKEMON_NOT_FOUND));
굿! 천천히 생각해봐도 좋을 것 같아요 👍

2024-10-11 02:53 UTC, jongmee commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/data/FakeEvolution.java
> +public class FakeEvolution extends Evolution {
저도 배틀 테스트하면서 그거 때문에 약간 고민했는데 .. 사실 우리 서비스 로직에서 실수로라도 setter를 사용할 일이 거의 없다고 보기 때문에 일단 괜찮을 것 같습니다 🤔 하지만 다같이 또 논의해봐요!

2024-10-11 02:53 UTC, jongmee approved these changes
/noti 고생하셨습니다 !!! 머지 고고.

2024-10-11 03:55 UTC, merged