[BE-REFACTOR] 배틀 기능 MongoDB 사용하도록 리팩토링
woowacourse-teams/2024-pokerogue-helper pull request #338
Opened 2024-09-25 16:10 UTC by jongmee

## 🍄 PR 확인 사항
PR이 다음 요구 사항을 충족하는지 확인하세요. :

- [x] API 명세서가 업데이트 혹은 작성이 되어 있나요?

## 현재 작업은 어떤 이슈를 해결한 것인지 설명해주세요.
> Issue Number: #331

## 기존 코드에서 변경된 점이 있다면 설명해주세요. (추가 X)

- [x] 있음
- [ ] 없음

### 이 부분을 위주로 봐주세요!
이 PR은 앞선 PR들 머지되고 충돌 해결 후 머지할 예정입니다. 코드 리뷰 때문에 미리 올려요~! 
**배틀 패키지에서 패키지 분리가 된 클래스들 위주로 리뷰해주시면 됩니다 😄 + 테스트코드**

### 고민사항
1. 현재 구조에서 `도메인` 패키지가 없어서 `BattleMultiplier`를 그냥 서비스 패키지에 넣었는데 고민됩니다.. 
도메인 패키지를 만드는게 좋을까요?
2. `TypeMultiplierProvider` 이름 괜찮나요?? `TypeBattingMultiplierProvider`가 나을까요?
고민하다가 둘 다 그저 그래서 의견을 받고 싶습니다 😅

2024-09-26 05:01 UTC, jinchiim requested changes
안녕하세요 미아!

코드를 보니 계산이 들어가서 그런지 꽤나 복잡하네요 🥹 정말 수고 많으셨습니다
몇가지 의견을 달았는데 리뷰 혹은 반영 주세요!

2024-09-26 05:01 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/BattleService.java
> +        Type moveType = Type.valueOf(move.getType().toUpperCase()); // Todo
못찾는 경우 의도한 에러를 뱉어내는지 테스트 작성해야하지 않을까요?! ☺️ (Enum 제외!)

2024-09-26 05:24 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/data/TypeMatching.java
> +@AllArgsConstructor
테스트에서 필요할까봐 넣었는데 필요할 때마다 생성하는게 좋을까요?!

해당 클래스는 추후 삭제될 예정이니(폴라 작업물의 TypeMatching을 사용할 예정) 머지할 때 처리하겠습니다!

2024-09-26 05:24 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/BattleMultiplier.java
> +    }
수정했습니다 🐕

2024-09-26 05:25 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/BattleService.java
> +                .stream() // Todo
맞습니다!! 역시 다른 pr들 머지되고 없어질 Todo 들입니다 🥲

2024-09-26 05:27 UTC, jongmee commented on backend/pokerogue/src/test/java/com/pokerogue/helper/battle/repository/TypeMatchingRepositoryTest.java
> +        String from = Type.BUG.getName();
맞습니다 😅 그런데 이 테스트는 잘 못 올라갔네요 :( 삭제했습니다!

2024-09-26 05:33 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/DataInitializer.java
> +                convertToInteger(fields.get(13)), fields.get(14));
인텔리제이 리팩토링이 해준 것 같네요 😅 안 쓰는거 맞습니다! 충돌날까봐 그대로 둔다고 생각했는데 어차피 리팩토링 된거 삭제했습니다 ㅎㅎ

2024-09-26 05:38 UTC, unifolio0 reviewed
짚을 만한 건 이미 폴라가 다 짚어서 approve합니다!

구현 수고하셨습니다!

2024-09-26 05:38 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/BattleMultiplier.java
> +    }
위에 메소드 2개와 `Weather`의 메소드에도 있습니다!

2024-09-26 05:39 UTC, unifolio0 approved these changes

2024-09-26 05:41 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/BattleService.java
> +                typeMatchingMultipliers.toArray(new BattleMultiplier[0]));
아래처럼 상수화하고
```java
private static final BattleMultiplier[] EMPTY_BATTLE_MULTIPLIER_ARRAY = new BattleMultiplier[0];
```

이렇게 변경해보았습니다 :)
```java
        BattleMultiplier typeMatchingMultiplier = BattleMultiplier.multiply(
                typeMatchingMultipliers.toArray(EMPTY_BATTLE_MULTIPLIER_ARRAY));
```

2024-09-26 05:45 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/TypeMultiplierProvider.java
> +                && typeMatching.getResult() == STRONG_TYPE_MATCHING_RESULT) {
```java
    private boolean isStrongWindConditionMet(Type moveType, List<Type> rivalPokemonTypes) {
        TypeMatching typeMatching = findTypeMatchingByFromAndTo(moveType, Type.FLYING);
        return rivalPokemonTypes.contains(Type.FLYING)
                && typeMatching.getResult() == STRONG_TYPE_MATCHING_RESULT;
    }
```
분리했습니다! 가독성이 훨씬 좋아졌네요 👍

2024-09-26 05:55 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/data/Weather.java
> +        if (this == Weather.RAIN) {
`WeatherMultiplierProvider`를 만들었습니다! 다만 한 메소드에서 분기되어서 처리되는 건 여전하네요 🥲

2024-09-26 11:17 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/BattleService.java
> +        Type moveType = Type.valueOf(move.getType().toUpperCase()); // Todo
당연하다고 생각해서 놓쳤네요 😞 추가했습니다~!

2024-09-26 11:18 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/BattleService.java
> +
BattleCalculator를 생성해봤습니다 😀😀

2024-09-26 11:30 UTC, jongmee commented
/noti @폴라 리뷰 반영 및 코멘트 달았습니당!

2024-09-26 11:50 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/DataInitializer.java
> +                convertToInteger(fields.get(13)), fields.get(14));
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 좋네요!

2024-09-26 11:50 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/data/TypeMatching.java
> +@AllArgsConstructor
저는 필요할때만 생성하는걸 선호하긴 합니다!
특히 어노테이션은 사용처도 안나오다보니 헷갈려서... 🤔

2024-09-26 11:57 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/data/Weather.java
> +        if (this == Weather.RAIN) {
씁 아쉽긴 하지만 그래도 `Weather` 라는 상수 집합체에선 빼냈으니 의미가 있어 보입니다! 👍🏻

2024-09-26 11:57 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/BattleService.java
> +                typeMatchingMultipliers.toArray(new BattleMultiplier[0]));
오 훨씬 보기 좋아졌어요! 👍🏻

2024-09-26 11:58 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/TypeMultiplierProvider.java
> +                && typeMatching.getResult() == STRONG_TYPE_MATCHING_RESULT) {
`return` 문 전에 한칸만 띄어준다면 더 완벽해지겠군요! ☺️

2024-09-26 11:59 UTC, jinchiim approved these changes
리뷰 반영 고생하셨습니다!!

반영해주신 부분에 의견 두가지 달았는데 소소한거라 RC 보다는 읽고 반영해주시면 될 것 같아요!
어푸룹 하겠습니다! ☺️

2024-09-26 18:18 UTC, dwax1324 requested changes
고생하셨습니다👍
코드가 꼼꼼하네요

저는 계산 기능은 서비스보다 도메인에 있는게 자연스럽다고 생각해요
서비스 계층에 있기엔 비즈니스로직은 아니고 하나의 도메인으로 분리 될만큼 코어한 기능이라고 생각합니다.

2024-09-26 18:18 UTC, dwax1324 commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/data/PokemonTest.java
> +        );
테스트 유틸로 따로 뺴도 좋을 것 같네요

2024-09-26 18:18 UTC, dwax1324 commented on backend/pokerogue/src/test/java/com/pokerogue/helper/battle/service/BattleMultiplierTest.java
> +        assertThat(sameValueMultiplier).isSameAs(constantBattleMultiplier);
동일성비교👍

2024-09-26 18:18 UTC, dwax1324 commented on backend/pokerogue/src/test/java/com/pokerogue/helper/battle/service/BattleMultiplierTest.java
> +    }
```java
    @Test
    @DisplayName("배틀배수끼리 동등하다.")
    void hasSemanticEquality() {
        BattleMultiplier multiplier = BattleMultiplier.valueOf(0.3+0.3+0.3);
        BattleMultiplier otherMultiplier = BattleMultiplier.valueOf(0.9);

        assertThat(multiplier).isEqualTo(otherMultiplier);
    }
    
```
    
```
Expected :com.pokerogue.helper.battle.service.BattleMultiplier@f3200020
Actual   :com.pokerogue.helper.battle.service.BattleMultiplier@f320001f
```
😢

2024-09-26 22:13 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/BattleCalculator.java
> +            return (double) move.getAccuracy() * FOG_ACCURACY_EFFECT;
이전엔 `move.getAccuracy()`가 integer였어서 남아있었네요 삭제했음다

2024-09-26 22:16 UTC, jongmee commented on backend/pokerogue/src/test/java/com/pokerogue/helper/battle/service/WeatherServiceTest.java
> +    }
그렇네요 삭제했습니당!

2024-09-26 22:42 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/WeatherMultiplierProvider.java
> +    }
/noti 오호 저번에 디코에서 switch문은 별로라는 의견이 있었는데 다른분들은 어떻게 생각하시나요?!

2024-09-26 22:43 UTC, jongmee commented on backend/pokerogue/src/test/java/com/pokerogue/helper/pokemon/data/PokemonTest.java
> +        );
이것밖에 없어서 아직은 안 해도 될 거 같습니당

2024-09-26 22:44 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/BattleMultiplier.java
> +    private static final Map<Double, BattleMultiplier> CACHE = new HashMap<>();
`BattleMultiplier`의 값(value)을 `BigDecimal`로 싹 교체했습니다 👍

2024-09-26 22:44 UTC, jongmee commented on backend/pokerogue/src/test/java/com/pokerogue/helper/battle/service/BattleMultiplierTest.java
> +    }
```java
 @Test
    @DisplayName("배틀배수끼리 동등하다.")
    void hasSemanticEquality() {
        BigDecimal multiplierValue = BigDecimal.valueOf(0.3).add(BigDecimal.valueOf(0.3).add(BigDecimal.valueOf(0.3)));
        BattleMultiplier multiplier = BattleMultiplier.valueOf(multiplierValue);
        BigDecimal otherMultiplierValue = BigDecimal.valueOf(0.9);
        BattleMultiplier otherMultiplier = BattleMultiplier.valueOf(otherMultiplierValue);

        assertThat(multiplier).isEqualTo(otherMultiplier);
    }

```

2024-09-26 22:45 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/BattleMultiplier.java
> +        return Double.compare(that.value, value) == 0;
```java
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BattleMultiplier that = (BattleMultiplier) o;

        return this.value.compareTo(that.value) == 0;
    }

    @Override
    public int hashCode() {
        return this.value.stripTrailingZeros().hashCode();
    }
```
👍

2024-09-26 22:46 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/TypeMultiplierProvider.java
> +                .map(toType -> findTypeMatchingByFromAndTo(attackMoveType, toType))
좋습니다! 바꿨습니다 ⭐️

2024-09-26 22:48 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/TypeMultiplierProvider.java
> +    }
저도 불편하다고 느꼈어요 😞

2024-09-26 22:52 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/WeatherMultiplierProvider.java
> +    }
switch 문 활용하는건 좋은데 문자열은 읽기 힘들어서
```java
    public BattleMultiplier getByAttackMoveType(Weather weather, Type attackMoveType) {
        return switch (weather) {
            case SUNNY -> getSunnyAttackTypeMultiplier(attackMoveType);
            case HARSH_SUN -> getHarshSunAttackTypeMultiplier(attackMoveType);
            case RAIN -> getRainAttackTypeMultiplier(attackMoveType);
            case HEAVY_RAIN -> getHeavyRainAttackTypeMultiplier(attackMoveType);
            default -> BattleMultiplier.DEFAULT_MULTIPLIER;
        };
    }

    private BattleMultiplier getSunnyAttackTypeMultiplier(Type attackMoveType) {
        return switch (attackMoveType) {
            case FIRE -> BattleMultiplier.STRONG_MULTIPLIER;
            case WATER -> BattleMultiplier.WEAK_MULTIPLIER;
            default -> BattleMultiplier.DEFAULT_MULTIPLIER;
        };
    }

    private BattleMultiplier getHarshSunAttackTypeMultiplier(Type attackMoveType) {
        return switch (attackMoveType) {
            case FIRE -> BattleMultiplier.STRONG_MULTIPLIER;
            case WATER -> BattleMultiplier.ZERO_MULTIPLIER;
            default -> BattleMultiplier.DEFAULT_MULTIPLIER;
        };
    }

    private BattleMultiplier getRainAttackTypeMultiplier(Type attackMoveType) {
        return switch (attackMoveType) {
            case WATER -> BattleMultiplier.STRONG_MULTIPLIER;
            case FIRE -> BattleMultiplier.WEAK_MULTIPLIER;
            default -> BattleMultiplier.DEFAULT_MULTIPLIER;
        };
    }

    private BattleMultiplier getHeavyRainAttackTypeMultiplier(Type attackMoveType) {
        return switch (attackMoveType) {
            case WATER -> BattleMultiplier.STRONG_MULTIPLIER;
            case FIRE -> BattleMultiplier.ZERO_MULTIPLIER;
            default -> BattleMultiplier.DEFAULT_MULTIPLIER;
        };
    }

```

이건 어떨까요??

2024-09-26 22:52 UTC, jongmee commented
/noti

@종이 : 모두 반영 및 코멘트 남겼습니다!
@everyone : [날씨배수조건문에 대한 코멘트](https://github.com/woowacourse-teams/2024-pokerogue-helper/pull/338#discussion_r1777520094)에 대해서 어떻게 생각하시나요?

2024-09-26 23:38 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/WeatherMultiplierProvider.java
> +    }
`if`문으로 이루어진 것과 흐름은 같은데 더 간결한 것 같습니다. 어떨 때는 객체지향보다 절차지향이 더 이해하기 편한 것처럼 상황에 따라 더 이해하기 편한 코드가 있다고 생각해 전 찬성입니다!☺️☺️

2024-09-27 00:06 UTC, dwax1324 approved these changes

2024-09-27 00:35 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/WeatherMultiplierProvider.java
> +    }
사실 의도는 스의치문보다는

(weather,type)을 넣으면 특정 Multiplier가 나온다

로 단순화 시켜볼 수 읶지 안ㄹ을까 였습니다..

문자열 대신 해싱도 되고
스위치 대신 맵써도 괜찮을거 같아요
다른 좋은 방법도 있지 않을까..
방법은 요러가지일듯 🐙

2024-09-27 01:02 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/WeatherMultiplierProvider.java
> +    }
그럼 (weather,type)으로 해시코드 만들어서 Map<Integer, BattleMultiplier> 를 사용해도 되겠네용

switch문보다 이게 나으려나요 🤔

2024-09-27 01:31 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/WeatherMultiplierProvider.java
> +    }
저는 맵이 제일 괜찮아 보이긴 한데..
미아가 결정하시죠 🐶

2024-10-10 08:27 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/service/WeatherMultiplierProvider.java
> +    }
Map으로 구현했습니다~!

2024-10-11 06:56 UTC, merged