[BE-REFACTOR] MongoDB를 사용하여 Type을 연결하고 코드를 개선
woowacourse-teams/2024-pokerogue-helper pull request #341
Opened 2024-09-25 18:43 UTC by jinchiim

## 🍄 PR 확인 사항
PR이 다음 요구 사항을 충족하는지 확인하세요. :

- [x] API 명세서가 업데이트 혹은 작성이 되어 있나요?

## 현재 작업은 어떤 이슈를 해결한 것인지 설명해주세요.
> Issue Number: #330 

- [x] MongoDB JPA를 사용하여 정상 구동되도록 구현한다.
- [x] 코드가 깔쌈하도록 리팩토링 한다.
- [x] Enum Converter 를 구축한다.

## 기존 코드에서 변경된 점이 있다면 설명해주세요. (추가 X)

- [x] 있음
- [ ] 없음

## 변경점

우선 `File Changed` 를 보고 놀라서 오셨겠지만 
**대부분 `Convert`를 만들고, 테스트를 작성하고의 반복 과정이라 걱정 안하셔도 됩니다!**

- [ ] **`Entity Field` -> `Enum` 으로 변환해주는 `Converter` 생성**
        저희에게는 `Read` 밖에 없어서 `ReadingConverter`만 생성했습니다!

        그리고 해당하는 `Converter` 을 `DBTest` 에서도 사용하기 위해 `@Import` 했습니다!

```java
@DataMongoTest
@ActiveProfiles("local")
@Import(ConverterConfig.class)
public abstract class MongoRepositoryTest {
}
```

- [ ] 기존에 없던 `MoveFlag`, `MoveTarget` Enum 생성

## 궁금할 수 있는 점

**Q. 기존에 있는 메서드를 사용하지 왜 각 Enum에 `convertFrom` 메서드를 다 만들었나요?**

```
컨벤션 같은걸 만들고 싶었습니다!
사용처가 다른데, (하나는 레포지토리 레이어에서 데이터를 바인딩 해주는 컨버터, 다른 것은 서비스 메서드) 
하나의 메서드를 사용하는 것이 꺼려졌어요. 🤔

서비스 메서드에서 사용하지 않는다면 `findBy~` 같은 메서드는 없는 것이 낫겠다고 판단했습니다.

만약 저희의 id 정책이 바뀐다면 새로운 메서드를 만들기보다는 `convert`와 관련된 메서드를 바꾸거나 
`Converter`에만 변화가 있기를 바랬습니다.

(다만 여러분들이 원하신다면.... 삭제 가능! 의견 주세요)
```

2024-09-26 00:53 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/data/MoveFlag.java
> +    }
GOOD 전 매우 좋습니다 converter 관련 함수! 따로 있는게 나중에 추적하기 더 쉬울 것 같아요!

2024-09-26 01:07 UTC, jongmee requested changes
LGTM !!! 👍👍👍👍

entity 패키지 관련한 리뷰에 대해 의견을 듣고 싶어서 RC 보냅니다 ☺️

2024-09-26 01:07 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/type/entity/TypeMatching.java
> +package com.pokerogue.helper.type.entity;
entity 패키지를 만든 건 db에 저장되지 않는 data들과 구별하기 위해서 겠죠 ?!

좋은 의도 같은데, 모든 패키지에서 컨벤션으로 정하면 좋을 것 같아요 (db에 저장되는 데이터를 넣는 패키지, 그냥 data 패키지) 👍

그리고 entity는 주로 RDB에서 사용하는 용어이고 JPA를 사용할 때 `@Entity`를 많이 썼는데, 현재 MongoDB를 사용하는 우리는 entity보다 document 혹은 collection이 더 적합하지 않을까요?

2024-09-26 01:34 UTC, jongmee commented
PR description 다시 읽어보다가 별거 아니지만 추가로 남겨요!

> MongoDB JPA를 사용하여 정상 구동되도록 구현한다.

MongoDB JPA는 따로 없고 `Spring Data MongoDB`를 사용한다고 표현하는게 맞습니다! `org.springframework.data`의 하위모듈로 JPA(Spring Data JPA)와 Spring Data MongoDB가 존재한다고 이해하면 될 것 같습니다 ☺️

Spring Data에서 제공하는 Repository 인터페이스를 사용하기 때문에 Spring Data JPA와 Spring Data MongoDB를 비슷하게 사용할 수 있습니다. 👍

2024-09-26 02:03 UTC, unifolio0 approved these changes
어제 리플렉션 언급하고 그랬을 땐 결과물이 어떻게 나올까 궁금했는데 역시 객체 마스터 폴라네요! 👍 

저는 `convertFrom`을 각각 만든 거에 찬성합니다!

구현 수고하셨습니다!☺️

2024-09-26 02:13 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/type/entity/TypeMatching.java
> +package com.pokerogue.helper.type.entity;
동의합니다!
Collection 패키지를 만들어서 넣는게 더 어울릴것 같아요! 

저도 갸웃하고 있던 점이었는데 좋네요 ㅋㅋㅋ 👍👍👍

2024-09-26 04:31 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/type/entity/TypeMatching.java
> +package com.pokerogue.helper.type.entity;
패키지 위치 변경했습니다! ☺️

> MongoDB JPA는 따로 없고 Spring Data MongoDB를 사용한다고 표현하는게 맞습니다! org.springframework.data의 하위모듈로 JPA(Spring Data JPA)와 Spring Data MongoDB가 존재한다고 이해하면 될 것 같습니다

오 좋네요! ☺️ 친절한 설명 감사합니다!

2024-09-26 04:48 UTC, murjune approved these changes
뭔가 리뷰어로 지정당해서 리뷰드립니다 😎

2024-09-26 04:48 UTC, murjune commented on backend/pokerogue/src/main/java/com/pokerogue/helper/battle/MoveCategory.java
> +                .filter(category -> category.hasSameEngName(name.toLowerCase()))
오 소문자처리 해주는군여!

2024-09-26 04:48 UTC, murjune commented on backend/pokerogue/src/main/java/com/pokerogue/helper/type/data/Type.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.POKEMON_TYPE_NOT_FOUND));
코틀린에는 이거 기본적으로 지원하는데 ㅋ

2024-09-26 04:48 UTC, murjune commented on backend/pokerogue/src/main/java/com/pokerogue/helper/type/service/PokemonTypeService.java
> +    public PokemonTypeMatchingResponse findMatchingAndTypes() {
And 불편

2024-09-26 04:48 UTC, murjune commented on backend/pokerogue/src/test/java/com/pokerogue/helper/battle/MoveCategoryTest.java
> +    @ValueSource(strings = {"aaa", "polla", "po"})
odoong이도 넣어줭

백엔드는 given when then 안쓰나 보군요!

2024-09-26 04:48 UTC, murjune commented on backend/pokerogue/src/test/java/com/pokerogue/helper/biome/repository/BiomeRepositoryTest.java
> +    void findAll_AndConvertToBiome() {
테스트만 Kotlin으로 해보실 생각없나요? Kotest 맛있는데~ ㅋㅋ

2024-09-26 04:48 UTC, murjune commented on backend/pokerogue/src/test/java/com/pokerogue/helper/biome/repository/BiomeRepositoryTest.java
> +    }
```kotlin
shouldAll {
    biomes.shouldHaveSize(35)

    biomes.flatMap { it.getTypes() }
        .forEach { it.declaringClass.shouldBeTypeOf<Type>() }

    biomes.flatMap { it.getNativePokemons().map(NativePokemon::getTier) }
        .forEach { it.declaringClass.shouldBeTypeOf<Tier>() }

    biomes.flatMap { it.getTrainers().flatMap { trainer -> trainer.getTypes() } }
        .forEach { it.declaringClass.shouldBeTypeOf<Type>() }
}
```

kotest 짱짱맨~

2024-09-26 04:48 UTC, murjune commented on backend/pokerogue/src/test/java/com/pokerogue/helper/type/converter/TypeReadConverterTest.java
> +    @DisplayName("들어온 값을 Type enum으로 변화한다.")
이노옴~ 저노옴~

2024-09-26 04:56 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/type/entity/TypeMatching.java
> +package com.pokerogue.helper.type.entity;
굿 !!!!

2024-09-26 04:59 UTC, jongmee commented on backend/pokerogue/src/test/java/com/pokerogue/helper/biome/repository/BiomeRepositoryTest.java
> +    }
Junit도 이렇게 되거든요!!!!!
```java
        assertAll(() -> {
            assertThat(biomes).hasSize(35);
            assertThat(biomes.stream()
                    .flatMap(biome -> biome.getTypes().stream()))
                    .allMatch(type -> type.getDeclaringClass()
                            .equals(Type.class));
            assertThat(biomes.stream()
                    .flatMap(biome -> biome.getNativePokemons().stream()
                            .map(NativePokemon::getTier))
                    .allMatch(tier -> tier.getDeclaringClass()
                            .equals(Tier.class)))
                    .isTrue();
            assertThat(biomes.stream()
                    .flatMap(biome -> biome.getTrainers().stream()
                            .map(Trainer::getTypes))
                    .flatMap(Collection::stream)
                    .allMatch(type -> type.getDeclaringClass()
                            .equals(Type.class)))
                    .isTrue();
        });
```

2024-09-26 05:01 UTC, jongmee approved these changes
어프룹! 굿이예요 👍

2024-09-26 05:04 UTC, jinchiim commented on backend/pokerogue/src/test/java/com/pokerogue/helper/biome/repository/BiomeRepositoryTest.java
> +    }
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-09-26 05:05 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/type/service/PokemonTypeService.java
> +    public PokemonTypeMatchingResponse findMatchingAndTypes() {
참으십시오

2024-09-26 05:05 UTC, jinchiim commented on backend/pokerogue/src/test/java/com/pokerogue/helper/battle/MoveCategoryTest.java
> +    @ValueSource(strings = {"aaa", "polla", "po"})
ㅋㅋㅋㅋㅋㅋㅋㅋ 고칠거 생기면 끼워 넣어 드립니다

> 백엔드는 given when then 안쓰나 보군요!

컨벤션으로 안넣기로 했습니다!

2024-09-26 05:05 UTC, jinchiim commented on backend/pokerogue/src/test/java/com/pokerogue/helper/biome/repository/BiomeRepositoryTest.java
> +    void findAll_AndConvertToBiome() {
가르쳐줘 명예 백엔드 오둥

2024-09-26 13:49 UTC, dwax1324 approved these changes
테스트 꼼꼼히 작성하셨네요
고생하셨습니다🫥

2024-09-26 13:49 UTC, dwax1324 commented on backend/pokerogue/src/test/java/com/pokerogue/helper/type/converter/TypeReadConverterTest.java
> +    @DisplayName("들어온 값을 Type enum으로 변화한다.")
?

2024-09-27 00:35 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/data/MoveFlag.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.MOVE_FLAG_NOT_FOUND));
이게 고민이었던 부분인데 결국 `new()` 로 전부를 등록해줘야 하는 것이 같아서 인터페이스로 묶는 의미가 있나 싶더라구요. 자동으로 굴러가게 하고 싶었는데ㅜ 🥲

2024-09-27 00:45 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/data/MoveFlag.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.MOVE_FLAG_NOT_FOUND));
아하 확실히 추상화 관점에서는 그럴 필요가 없겠네요🦑

저는 위에 미아가 말했던거처럼 추적, 명시화 관점에서 마커인터페이스처럼 만들어두면 좋지 않을까 했습니다 🐡

2024-09-27 00:49 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/data/MoveFlag.java
> +                .orElseThrow(() -> new GlobalCustomException(ErrorMessage.MOVE_FLAG_NOT_FOUND));
근데 굳이라는 생각이 들기도 하고
폴라가 판단하시죠🎷

2024-09-27 02:04 UTC, merged

2024-09-27 04:03 UTC, murjune commented on backend/pokerogue/src/test/java/com/pokerogue/helper/biome/repository/BiomeRepositoryTest.java
> +    }
😳