[BE-INFRA] 서버별 CD 워크플로우 생성
woowacourse-teams/2024-pokerogue-helper pull request #351
Opened 2024-10-04 10:38 UTC by unifolio0

## 🍄 PR 확인 사항
PR이 다음 요구 사항을 충족하는지 확인하세요. :

- [x] API 명세서가 업데이트 혹은 작성이 되어 있나요?

- [x] 기존 디비 ec2에 있는 도커를 dev ec2안으로 옮긴다.

## 기존 코드에서 변경된 점이 있다면 설명해주세요. (추가 X)

2024-10-07 05:14 UTC, jongmee requested changes
비토 고생하셨습니다 👍

dev yml 파일을 보니 제가 예전에 달았던 주석도 있는데 제거하면 더 좋을 것 같아요 👍 (이제 db가 로컬호스트로 바뀌었는데 헷갈릴 거 같아서 ㅎㅎ)

2024-10-07 05:14 UTC, jongmee commented on .github/workflows/Backend-CD-Dev.yml
> +              --link pokerogue-mongo-db:mongo \
네트워크 연결을 해줬군요 👍 그런데 mongo 라는 별칭을 지정해줘도 잘 돌아가나요? yml 파일을 보니 db url이 `pokerogue-mongo-db:27017`으로 되어 있어서요! 

(잘 돌아가더라도 별칭을 사용하지 않는다면 붙여주지 않아도 되지 않을까요?!)

2024-10-07 05:14 UTC, jongmee commented on .github/workflows/Backend-CD-Dev.yml
> +          docker pull pokeroguehelper/pokerogue-helper-test-mongodb
CI 워크플로우에서 docker image caching으로 문제가 있던 걸로 기억하는데 pull 받기 전에 docker image를 지우는 과정은 필요 없을까요 ?!

2024-10-07 05:14 UTC, jongmee commented on .github/workflows/Backend-CD-Dev.yml
> +          docker run -d --name pokerogue-mongo-db pokeroguehelper/pokerogue-helper-test-mongodb
⚠️ 이미지 이름은 secrets를 활용하는 게 좋을 것 같습니다. public 이미지라 털릴 수 있어서 🥲

2024-10-07 05:14 UTC, jongmee commented
/noti 비토 리뷰 완!

2024-10-07 07:11 UTC, unifolio0 commented on .github/workflows/Backend-CD-Dev.yml
> +              --link pokerogue-mongo-db:mongo \
수정했습니다! ☺️☺️

2024-10-07 07:11 UTC, unifolio0 commented on .github/workflows/Backend-CD-Dev.yml
> +          docker pull pokeroguehelper/pokerogue-helper-test-mongodb
수정했습니다! ☺️☺️

2024-10-07 07:11 UTC, unifolio0 commented on .github/workflows/Backend-CD-Dev.yml
> +          docker run -d --name pokerogue-mongo-db pokeroguehelper/pokerogue-helper-test-mongodb
수정했습니다! ☺️☺️

2024-10-07 07:12 UTC, unifolio0 commented
/noti 미아 리뷰 반영 완!

2024-10-07 07:32 UTC, jinchiim commented on .github/workflows/Backend-CD-Dev.yml
> +            docker builder prune
개인 질문인데, docker 이미지를 지우고 다시 이미지를 빌드하는 과정을 CD에 넣으신 이유가 궁금했어요!

왜냐면 `CI`가 먼저 선행되고 , 거기서 체크 표시가 안떠서 문제가 되는 경우가 많았거든요 🥹
비토의 상황도 비슷했던 것으로 기억합니다!

CI 의 빌드속도가 느려지긴 하겠지만 개인적으로 CD가 느려지기 보다는 CI가 느린게 낫다는 생각이긴 합니다 🤔

근데 개인적인 의견이라서 지금 캠퍼스에 계신 분들끼리 판단해서 정해주셔도 될 것 같아요! 😋

2024-10-07 07:32 UTC, jinchiim approved these changes
이미 미아가 많은 리뷰를 해줬네요! 👍🏻
LGTM 입니다! 비토한테도 도커 배워야겠네요 😄

궁금한거 하나 달았습니다! 확인해주세요!

2024-10-07 07:33 UTC, jinchiim commented
/noti 비토 리뷰 한번 확인 부탁!

2024-10-07 07:45 UTC, unifolio0 commented on .github/workflows/Backend-CD-Dev.yml
> +            docker builder prune
저희 `CI`가 돌아가는 ec2랑 `CD`가 돌아가는 ec2가 달라서 해당 로직이 필요할 것 같아요!☺️☺️

2024-10-07 07:46 UTC, unifolio0 commented
/noti 폴라 리뷰 답변 완!

2024-10-09 09:05 UTC, jongmee approved these changes

2024-10-11 00:51 UTC, dwax1324 requested changes
비토! 미아 pr보고 궁금한점 코멘트 남겼습니다

2024-10-11 00:51 UTC, dwax1324 commented on .github/workflows/Backend-CD-Dev.yml
> +            echo "No containers to remove."
미아 pr보고 왔는데 인덴트 컨벤션이 다르군요.
이부분 얘기해보면 좋을거 같아요!

2024-10-11 00:51 UTC, dwax1324 commented on .github/workflows/Backend-CD-Dev.yml
>      runs-on: dev
cd태그가 따로 생겪던데 여기에 안붙여도 되는건지 궁금합니다!

2024-10-11 01:27 UTC, unifolio0 commented on .github/workflows/Backend-CD-Dev.yml
>      runs-on: dev
`timmyroom-dev` 러너에 붙어있는 태그는 dev밖에 없어서 괜찮을 것 같습니다!

2024-10-11 01:31 UTC, unifolio0 commented on .github/workflows/Backend-CD-Dev.yml
> +            echo "No containers to remove."
처음에 인덴트가 필요한 줄 알았는데 검색해보니 스크립트에선 인덴트가 영향을 안 미치네요! 원래 계속 해왔던 인덴트 없이 하는 걸로 수정했습니다!

2024-10-11 01:32 UTC, dwax1324 approved these changes
슛~

2024-10-11 08:06 UTC, merged