[BE-FEAT] 기술 관련 api 만들기
woowacourse-teams/2024-pokerogue-helper pull request #360
Opened 2024-10-13 06:20 UTC by unifolio0

## 🍄 PR 확인 사항
PR이 다음 요구 사항을 충족하는지 확인하세요. :

- [ ] API 명세서가 업데이트 혹은 작성이 되어 있나요?

## 현재 작업은 어떤 이슈를 해결한 것인지 설명해주세요.
> Issue Number: #359 

- [x] 전체 기술 리스트 반환 api
- [x] 단일 기술 정보 반환 api

## 기존 코드에서 변경된 점이 있다면 설명해주세요. (추가 X)

우선 이 정보가 들어가면 되겠지 하고 짠 코드입니다.
추가로 기존에 존재하던 api와 중복 문제 때문에 임시로 api를 대충 만들었는데 어떻게 할 지 정해야 될 것 같아요
/noti

2024-10-14 04:37 UTC, jongmee requested changes
구현 잘 해주셨네요 👍 api 엔드포인트랑 메소드명 관련해서 간단하게 리뷰 남겼어요!

2024-10-14 04:37 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/controller/MoveController.java
> +    public ApiResponse<MoveResponse> moveDetailsByBattle(@PathVariable String id) {
이 메소드들(서비스 메소드 포함) `moveDetailsInBattle` 어때요 ?!

2024-10-14 04:37 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/controller/MoveController.java
> +    @GetMapping("/api/v1/move1/{id}")
지금 사용되고 있는 `move1` 대신에 `/api/v1/move-dex/{id}`나 `/api/v1/move/dex/{id}`어떤가요

'기술 도감' 이어서 생각났어요! 배틀 관련 기술 api에 battle 붙이고 싶지만 하위호환성 때문에 그건 안될 거 같고.. 🥲

2024-10-15 00:41 UTC, jinchiim requested changes
미아가 이미 리뷰를 남겨줘서 전부 동의하기도 하고
하나만 추가로 남겨봤습니다! ☺️

고생하셨어요!

2024-10-15 00:41 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/service/MoveService.java
> +        List<String> levelMoveIdsContains = pokemonRepository.findByLevelMovesMoveId(move.getId()).stream()
이해하기로는 변수가 의미하는 것이 
이 기술을 알기술로 가지고 있는 포켓몬, 레벨 기술로 가지고 있는 포켓몬 인 것 같은데,

변수 이름이 그렇게 느껴지지 않는 것 같아요 🥹
`eggMovePokemonIds` 와 같은 이름은 어떤 가요??

2024-10-16 01:22 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/controller/MoveController.java
> +    public ApiResponse<MoveResponse> moveDetailsByBattle(@PathVariable String id) {
수정했습니다! ☺️☺️

2024-10-16 01:23 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/controller/MoveController.java
> +    @GetMapping("/api/v1/move1/{id}")
수정했습니다! ☺️☺️

2024-10-16 01:24 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/move/service/MoveService.java
> +        List<String> levelMoveIdsContains = pokemonRepository.findByLevelMovesMoveId(move.getId()).stream()
수정했습니다! ☺️☺️

2024-10-16 01:28 UTC, unifolio0 commented
/noti
폴라, 미아꺼 끝~

2024-10-16 01:32 UTC, jongmee approved these changes
굿 ~!~!~!~!

2024-10-16 07:25 UTC, jinchiim approved these changes
굿! 고생하셨어요! 👍🏻

2024-10-20 10:59 UTC, dwax1324 approved these changes
안녕하세요 비토
깔끔하게 잘 구현하셨네요!!
고생하셨어요👏👏

2024-10-20 12:50 UTC, merged