[BE-REFACTOR] 바이옴 포켓몬 티어 정렬
woowacourse-teams/2024-pokerogue-helper pull request #363
Opened 2024-10-13 12:13 UTC by jongmee

## 🍄 PR 확인 사항
PR이 다음 요구 사항을 충족하는지 확인하세요. :

- [ ] API 명세서가 업데이트 혹은 작성이 되어 있나요? -> 머지되고 작성할래요

## 현재 작업은 어떤 이슈를 해결한 것인지 설명해주세요.
> Issue Number: #362

- [x] 보스 포켓몬 희귀도 높은 순으로 티어 정렬
- [x] 요구사항에 관계 없이 동적으로 쿼리스트링을 사용해서 정렬

## 기존 코드에서 변경된 점이 있다면 설명해주세요. (추가 X)

- [x] 있음
- [ ] 없음

이건 제안인데요! 쿼리 스트링으로 보스 포켓몬과 야생 포켓몬들 티어 정렬 기준을 받도록 api를 수정하면 어떨까요? 로그를 바탕으로 정렬 순서도 고치기로 했던 걸로 기억하는데 정렬 같은 조건문은 요구사항에 따라 바뀌는 것보다 이렇게 설계하는게 더 유연해보여서 제안합니다 :)

`보스 포켓몬들에 대해 티어 높은 순으로 정렬`만 요구사항이었기 때문에 쿼리스트링 default 값을 보스 포켓몬은 desc, 야생 포켓몬은 asc로 설정해보았습니다. (하위 호환성 O)

별로라면 철회하겠읍니다..

2024-10-15 02:15 UTC, unifolio0 approved these changes
역시 고퀄로 구현하셨네요! 저는 정렬 기준을 받는 거 좋다고 생각합니다!

간단한 컨벤션 리뷰라 바로 approve합니다!

구현 수고하셨어요! 👍

2024-10-15 02:15 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/NativePokemonComparator.java
> +        return DESCENDING_COMPARATOR;
아래 `compare`과 개행 컨벤션이 안 맞는 것 같아요! 통일 부탁드려요☺️☺️

2024-10-15 09:04 UTC, jinchiim requested changes
미아 정말 고생많으셨어요! 👍🏻
몇가지 리뷰 남겼으니 편하게 반영 혹은 의견 주세요! 😋

2024-10-15 09:04 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/NativePokemonComparator.java
> +    private static final NativePokemonComparator ASCENDING_COMPARATOR = new NativePokemonComparator(ASCENDING);
`static`으로 구성되어야 할 이유가 없다면 팩토리...패턴.... ~맞나(?)~ 은 어떨까 제안드려봅니다! 😄

따로 순서 정렬 상수로 선언한 `Ascend` 와 `Descend` 를 주입받고 
그에 따라 `new NativePokemonComparator(ASCENDING)` 혹은`new NativePokemonComparator(DESCENDING)`를 주면 좋을 것 같아요!

인터페이스도 만든다면 내부 구현과는 상관 없이 `compare` 문에서 조건문을 적지 않아도 되고 상수도 따로 만들어지니 테스트나 API 에서 편하게 가져다 쓸 수 있을 것 같다는 생각이 듭니다!

슬며시 제안.. 😋

2024-10-16 01:39 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/NativePokemonComparator.java
> +        return DESCENDING_COMPARATOR;
개행 추가했습니다 !

2024-10-16 03:05 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/NativePokemonComparator.java
> +    private static final NativePokemonComparator DESCENDING_COMPARATOR = new NativePokemonComparator(DESCENDING);
현재 `BiomeService`에서는 상수를 사용하지 않고 `Comparator`의 `compare` 메소드와 `BiomeController`에서만 사용하고 있습니다! 비교하는 역할을 하는 클래스인 `Comparator`가 비교 기준을 가지고 있는게 더 낫지 않을까요?!

2024-10-16 03:13 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/NativePokemonComparator.java
> +    private static final NativePokemonComparator ASCENDING_COMPARATOR = new NativePokemonComparator(ASCENDING);
우선  팩토리 패턴을 쓰더라도 팩토리 클래스에서 Comparator를 static으로 캐싱하고 있는게 나을 것 같습니다 ☺️ 사실상 유틸 클래스라 사용할 때마다 객체를 생성하는 것보다는 싱글턴으로 사용하는게 적절할 것 같습니다!

현재 `Comparator`라는 인터페이스를 사용하고 있는데 오름차순, 내림차순인지 구분하기 위해 새롭게 인터페이스를 만드는게 적절할까요 ?? 다른 데이터에서 사용한다면 분리할 만한데 현재 추가로 정렬(오름차순 및 내림차순)할 만한 데이터가 떠오르지 않네요 (혹쉬 있을까요?!) 포켓몬(종족값 등)도 안드로이드에서 하는 걸로 알아서요!

2024-10-16 03:15 UTC, jongmee commented
/noti @jinchiim 폴라!!! 코멘트(이지만 질문) 달았어요 😄

2024-10-16 03:47 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/NativePokemonComparator.java
> +    private static final NativePokemonComparator DESCENDING_COMPARATOR = new NativePokemonComparator(DESCENDING);
밑에서 같이 의견 드릴게요!

2024-10-16 03:57 UTC, jinchiim requested changes

2024-10-16 03:57 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/NativePokemonComparator.java
> +    private static final NativePokemonComparator ASCENDING_COMPARATOR = new NativePokemonComparator(ASCENDING);
지금은 하나 뿐이니 좀 더 생각해봐도 좋겠네요!  ☺️
```
    public static final String ASCENDING = "asc";
    public static final String DESCENDING = "desc";
```

순서를 의미하는 이 상수만 분리하면 좋을 것 같습니다! 😋

2024-10-16 05:46 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/NativePokemonComparator.java
> +    private static final NativePokemonComparator ASCENDING_COMPARATOR = new NativePokemonComparator(ASCENDING);
`SortingCriteria` enum으로 분리했습니다 ! `global.constant` 패키지에 위치합니다 ☺️

2024-10-16 05:57 UTC, jongmee commented
/noti

여러분 정렬 기준 문자열을 enum으로 관리하게 되면서 컨버터 등등이 들어났는데요 😅 천천히 봐주세요.. 변경 사항이 꽤 있어서 다시 리뷰 요청합니다 🙇🏻‍♀️

제가 맡은 부분 외에 건들인게 있어서 이것만 추가 설명 적겠습니다

## ConverterConfig 변경
- ConverterConfig를 보니 `org.springframework.data.mongodb.core.convert.MongoCustomConversions` 이걸 빈으로 등록하고 있더라고요!
- PokerogueApplication에서 `@EnableMongoRepositories`를 등록해놨습니다. (제가 초기 세팅때) 그런데 어플리케이션 클래스에 바로 설정하는건 `의존성`의 관점에서 별로라고 생각합니다 😅 바이옴 컨트롤러 테스트 하면서 바로 체감했습니다. web mvc 레이어만 떼다가 테스트하고 싶은데 어플리케이션에 설정이 바로 붙어있으니 모든 Data MongoDb config를 불러오더라고요 😞
- 그래서 Data MongoDb 설정을 다룬 클래스(`@Configuration`)을 만들까하다가 `ConverterConfig`와 합쳐보았습니다. (묶어놓는게 편해서)

의견주세요!!

2024-10-20 10:51 UTC, dwax1324 approved these changes
안녕하세요 미아
테스트도 완벽해서 코멘트 드릴게 별로 없네요 ✨
고생하셨어요!!

2024-10-20 10:51 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/global/config/DataMongoDbConfig.java
> +public class DataMongoDbConfig {
네이밍 굿

2024-10-20 10:51 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/controller/BiomeController.java
> +                                                         @RequestParam(value = "wild", defaultValue = "asc") SortingCriteria wildPokemonOrder) {
지금은 `/api/v1/biome/grass?boss=asc&wild=desc` 요런 api구조가 될 거 같은데
`/api/v1/biome/grass?sort=boss-asc,wild-desc`  이런 스타일은 어떠신지..!

2024-10-20 10:51 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/NativePokemonComparator.java
> +    public int compare(NativePokemon firstPokemon, NativePokemon secondPokemon) {
null 체크 해야할 것 같아요!

2024-10-20 12:22 UTC, jinchiim approved these changes
코멘트 하나 달았는데 간단해서 apporve 남깁니다!! 👍🏻

2024-10-20 12:22 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/global/config/DataMongoDbConfig.java
> +@EnableMongoRepositories(basePackages = {"com.pokerogue"})
패키지가 조금 광범위한 것 같은데, `repoitory`가 따로 있는 것이 아니라서 쩔수 없긴 하지만
`helper` 까지만이라도 줄여볼까요?? 🤔

2024-10-21 07:24 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/global/config/DataMongoDbConfig.java
> +@EnableMongoRepositories(basePackages = {"com.pokerogue"})
좋네요! 수정했습니다 👍

2024-10-21 07:29 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/controller/BiomeController.java
> +                                                         @RequestParam(value = "wild", defaultValue = "asc") SortingCriteria wildPokemonOrder) {
대체로 그 형식을 많이 써서 후보 중 하나였는데 SortingCriteria를 전역적으로 활용하려면 value가 asc, desc가 되는게 더 유용하다고 생각했습니다 :)

2024-10-21 07:31 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/NativePokemonComparator.java
> +    public int compare(NativePokemon firstPokemon, NativePokemon secondPokemon) {
1. 예외를 던진다 
2. null이어도 비교 가능하도록 로직을 추가한다. (예를들어 firstPokemon이 null이면 secondPokemon이 더 큰 것으로 판단)

저는 null이 있는 Collection 혹은 Array를 정렬한다면 예외가 터지는게 맞는 것 같은데 null pointer exception을 custom exception으로 감쌀 필요 있을까 싶어 따로 null 추가를 하지 않았습니다 ☺️ custom exception을 활용하는게 더 유용하려나요 ?? 🤔

2024-10-21 07:56 UTC, jongmee commented
/noti 폴라 리뷰는 반영했고 종이 리뷰는 코멘트 단 게 있어서 확인부탁드림니다!! 오늘 안에 머지할까 합니당 😚

2024-10-21 08:23 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/NativePokemonComparator.java
> +    public int compare(NativePokemon firstPokemon, NativePokemon secondPokemon) {
찾아봤는데 아래와 같은api를 제공하고 있더라고요!☺️
`npe`를 던지는 것이 더 자연스러워 보이네요.
```java
Comparator.nullsFirst(NativePokemonComparator.of(wildPokemonOrder));
Comparator.nullsLast(NativePokemonComparator.of(wildPokemonOrder));
```

찾아보면서 궁금했던 점) 
api문서를 보면 comparator의 `natural order`는 equals와 일관되게 작성하라고 하는데..
equals는 반사성,대칭성,추이성,일관성, null-false 를 지키도록 하는데 왜 compare는 `npe`를 던질까요..

2024-10-21 16:29 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/biome/service/NativePokemonComparator.java
> +    public int compare(NativePokemon firstPokemon, NativePokemon secondPokemon) {
오 덕분에 배워갑니다 👍

이렇게도 사용할 수 있군요
```java
Comparator<String> comparator = Comparator.nullsFirst(Comparator.naturalOrder());
```
아마도.. Comparator에서 null을 어떻게 다룰지는 사용하는 사람이 정하라는 뜻이려나요 ?? 🤔

2024-10-22 00:51 UTC, merged