[1.1.1/AN-FEAT] 페이지 이동 로직 개선
woowacourse-teams/2024-pokerogue-helper pull request #379
Opened 2024-10-20 10:45 UTC by JoYehyun99

- closed #357 
## 작업 영상
https://github.com/user-attachments/assets/f9585a0a-767f-4892-937b-1167fef0b43b

## 작업한 내용
### 바이옴 페이지 ➡️ 배틀 페이지 상대 포켓몬 선택
- 토글로 이동 모드 설정
- 이동 모드 선택값 `datastore`에 저장
- tooltip 사용하여 안내 문구 표시

## PR 포인트
- [심지 PR](https://github.com/woowacourse-teams/2024-pokerogue-helper/pull/378) 머지 되면 `포켓몬 상세 -> 배틀  페이지` 연결 후 마무리할께요!
- 배틀 페이지 -> 포켓몬 상세 이동은 #356 할때 추가될 것 같아요!
- datastore 에 저장하기위한 localDatasource 네이밍을 LocalNavigationDataSource로 설정해놨는데 (뭔가 Biome이라고 하기에는 애매한것 같아서,,,) 그냥 localbiomeDatasource 이라고 둘까요???

## 🚀Next Feature
- #356 UI 작업이랑은 다 해놨는데, 서버 대응 관련해서 얘기해보고 올리겠습니당
- koin 적용

2024-10-20 12:15 UTC, sh1mj1 requested changes
API 이름이나 설계 측면에서 리뷰 남겼습니다.

ktlint 가 뭔가 잚못 되어 있는지, 들여쓰기만 바뀐 코드가 많네요..? 왜 이러지

현재 예니 코드에서 홈 화면에서 포켓몬 도감으로 이동하면 터져요!

### 원인: 
`->`:  의존성 방향이라고 하면,
`PokemonListActivity` -> `PokemonListViewModel` 
`PokemonListViewModel`  -> `DefaultDexRepository`
`DefaultDexRepository` -> `DefaultBiomeRepository`
`DefaultBiomeRepository` -> `LocalNavigationDataSource`
`LocalNavigationDataSource` -> `NavigationModeDataStore`

그런데 koin 에서는 `LocalNavigationDataSource` 와 `NavigationModeDataStore` 에 대한 정보를 모름.

그래서 DataSourceModule 에 
`singleOf(::LocalNavigationDataSource)`
DataStoreModule 에 
`singleOf(::NavigationModeDataStore` 추가해주어야 합니다.

```
Unable to start activity ComponentInfo{poke.rogue.helper.dev/poke.rogue.helper.presentation.dex.PokemonListActivity}: org.koin.core.error.InstanceCreationException: 
Could not create instance for '[Factory: 'poke.rogue.helper.presentation.dex.PokemonListViewModel']'
Could not create instance for '[Singleton: 'poke.rogue.helper.data.repository.DefaultDexRepository',binds:poke.rogue.helper.data.repository.DexRepository]'
Could not create instance for '[Singleton: 'poke.rogue.helper.data.repository.DefaultBiomeRepository',binds:poke.rogue.helper.data.repository.BiomeRepository]'
No definition found for type 'poke.rogue.helper.data.datasource.LocalNavigationDataSource'. Check your Modules configuration and add missing type and/or qualifier!
```

2024-10-20 12:15 UTC, sh1mj1 commented on android/app/src/main/res/layout/activity_biome_detail.xml
<img width="467" alt="image" src="https://github.com/user-attachments/assets/0c8d41a0-2c1f-423a-85e3-7ae03944413b">

뷰가 이렇게 보입니당

2024-10-20 13:36 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleViewModel.kt
> +            )
그러게요,,,? 다시 확인 해볼께용

2024-10-20 13:37 UTC, JoYehyun99 commented on android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt
> +    override suspend fun pokemon(pokemonId: String): Pokemon = pokemonRepository.pokemon(pokemonId)
해당 부분에 대해서 저도 고민이 되었는데요!
현재 `BattleRepository`에서도 `PokemonRepository` 를 가지고 있는 상황에서
`BatltleViewModel` 또한 `PokemonRepository`를  가지고 있는게 맞을까..? 라는 생각이 들더라구요!

그럼에도 뷰모델에서 `PokemonRepository`를 넣어주는게 맞을까요?_?

2024-10-20 13:40 UTC, JoYehyun99 commented on android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt
> +    override suspend fun pokemonWithRandomSkill(pokemonId: String): PokemonWithSkill {
흠 이건 어찌됬든 랜덤하게 스킬을 선택해서 부여하기 때문에  이렇게 명시했던것같아요!
첫번째 순서든 마지막 순서든 어쨌든 '랜덤하게' 임의로 우리가 부여하는 거닌깐..? 
조금 더 포괄적인 의미로 설정한건데 많이 헷갈린다는 의견이 많다면 수정하겠습니다~

2024-10-20 13:48 UTC, JoYehyun99 commented on android/gradle/libs.versions.toml
> +balloon = { module = "com.github.skydoves:balloon", version.ref = "balloon" }
앗,,,
오직 `개발 시간 단축` 을 위한 외부 라이브러리이기 때문에 거기까진 생각 못한 것 같아요 🥹

2024-10-20 13:52 UTC, JoYehyun99 commented
아 그리고 저 토글 버튼 체크 하는 부분에도 `single click` 설정 해주어야 하나요?????? 😲

2024-10-20 13:54 UTC, JoYehyun99 commented
> 그래서 DataSourceModule 에
singleOf(::LocalNavigationDataSource)
DataStoreModule 에
singleOf(::NavigationModeDataStore 추가해주어야 합니다.

엇 이미 되어있었는데,,,?????? 그래도 터지나요??? 
아니면 제가 추가 커밋하는데 시간이 겹친건가,,,,? 😲😲😲😲

2024-10-21 06:36 UTC, murjune approved these changes
고생하셨습니다! 몇 가지 리뷰 남깁니당 😉

2024-10-21 06:36 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/battle/BattleViewModel.kt
> +                fetchSavedOpponentPokemon()
흐음.. fetch 보다는 load 가 어떨까요? fetch 는 get 과 같이 무엇을 반환하는 함수에 사용하는 것으로 알고 있습니다

2024-10-21 06:36 UTC, murjune commented on android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt
> +    override suspend fun pokemon(pokemonId: String): Pokemon = pokemonRepository.pokemon(pokemonId)
BattleViewModel 에서 PokemonRepository를 호출하는게 더 좋아보입니다~  
ViewModel 이 데이터의 출처에 관심을 갖을 필요는 없을 것 같아요!  

그리고, BattleRepository 에서 포켓몬 정보를 가져오는 것은 BattleRepository 의 역할에 위배된다고 보여집니다. (SRP 위반)

2024-10-21 06:36 UTC, murjune commented on android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt
> +    override suspend fun pokemonWithRandomSkill(pokemonId: String): PokemonWithSkill {
Random ,First 둘다 함수 네이밍에 너무 세부 구현 사항을 나타내고 있습니다.   

해당 함수를 사용하는 actor(ViewModel, UseCase)입장에서는 저장된 데이터인지 아닌지 궁금해하지 않을거에여요! 따라서, 그냥 `데이터 이름`만 적어줘도 충분할 것 같습니다 ㅎㅎ

그리고, 내부 구현 로직에 바뀔 때마다 함수 네이밍을 바꿔주게 될 것 같습니다.. 😢

2024-10-21 08:36 UTC, JoYehyun99 commented on android/data/src/main/java/poke/rogue/helper/data/repository/DefaultBattleRepository.kt
> +    override suspend fun pokemonWithRandomSkill(pokemonId: String): PokemonWithSkill {
전반적인 리팩토링이 필요할 것 같아 다음 PR에 반영하도록 하겠습니다~

2024-10-21 10:58 UTC, kkosang approved these changes
고생하셨습니다 예니~ 👍

현재 바이옴 디테일에서 토글을 선택한 후, 배틀구도로 넘어오게 되면 배틀 결과가 나타나지 않아요..!
<img width="200" alt="스크린샷 2024-10-21 오후 5 56 37" src="https://github.com/user-attachments/assets/e1329820-2595-46b0-9227-cb0fcb0229af">

2024-10-21 10:58 UTC, kkosang commented on android/gradle/libs.versions.toml
> +balloon = { module = "com.github.skydoves:balloon", version.ref = "balloon" }
헉 balloon이 skydoves 님의 라이브러리였다니..

2024-10-23 04:37 UTC, JoYehyun99 commented
/noti
리뷰 반영 및 포켓몬 상세 ➡️ 배틀 페이지 연결까지 완료우 


https://github.com/user-attachments/assets/8016ac32-e921-4205-99fd-50743d68634b

2024-10-23 14:59 UTC, sh1mj1 approved these changes
반영 굳~

2024-10-24 00:53 UTC, merged