[AN-REFACTOR] 상성 화면 리팩토링
woowacourse-teams/2024-pokerogue-helper pull request #38
Opened 2024-07-18 16:53 UTC by JoYehyun99

- closed #28 
## 작업 영상
- 이전과 동일해서 PASS
- _BottomSheet 상단에 draghandleview 추가 했습니당_
<img src="https://github.com/user-attachments/assets/220e48cf-7fc0-48b8-b555-a796a48a63ad" width = 200 />

## 작업한 내용
- `데이터 바인딩` 적용
- `Flow` 적용
- 코드 리팩토링 (함수 분리 등)
- 상성 데이터 평행사변형(?) 커스텀 뷰 
   - 반복되는 이미지와 버튼 레이아웃을 줄이기 위해 합치기 작업

## PR 포인트
- 기능 수정은 하지 않았습니다! (따로 브랜치 파서 진행할 예정 🙃)
  - 데이터쪽에서 꽤나 수정이 필요할 것 같기 때문에 View, ViewModel 부분을 중심으로 봐주세요!
- Flow 처음 써봤는데 이 부분에 대해 피드백 부탁드려용 ✨

## 🚀Next Feature
- 세부적인 기능 수정 및 변경된 요구사항 적용

2024-07-19 14:44 UTC, sh1mj1 reviewed
어떻게 보면, 마이그레이션을 진행한 것 같아, 꽤 힘드셨을 것 같아요.
정말 정말로 고생많으셨어요!!!!!

낮에 같이 이야기한 부분도 리마인드 겸 코멘트 남겼습니다!

저도 flow 를 완벽히 이해하고 있지 않은데, 프로젝트 진행하면서 같이 더 배워나가 봅시다!

2024-07-19 14:44 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/result/TypeResultViewHolder.kt
> +    }
이 부분은 데이터 바인딩 사용하지 않으신 이유 궁금합니다!

2024-07-19 14:44 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/view/PokeParallelogramLayout.kt
> +                type?.let { view.bindType(it) }
이 바인딩 어댑터 함수는 `PokeParallelogramLayout` 의 동반 객체 내부에 있는 이유가 궁금합니다!

2024-07-19 15:59 UTC, murjune requested changes
작업하느라 고생하셨습니다!  
꽤나 코드리뷰 양이 많은데.. 이해가 안가거나 궁금한 점은 함께 논의해보시죠!

2024-07-19 15:59 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/type/view/PokeParallelogramLayout.kt
> +                type?.let { view.bindType(it) }
이건 제가 companion object 에 추가한 것인데요!

해당 VIew 에 대한 BindingAdapter 이니 companion object 에 작성하는 것이 좋아보여 해당 파일에 작성했습니다 ㅎ ㅎ

2024-07-20 13:01 UTC, murjune commented
도메인 공부하다가 찾았습니다 ㅋㅋㅋ

activity_type scroll view nestedScrollview로 바꿔주십쇼!!

스크롤 영역이 겹쳐서 상성이 안내려가더라구요 🫠

2024-07-21 10:40 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeViewModel.kt
> +    private val isAnyOpponentSelected
흠 저도 `boolean` 값임을 암시해주는 `is`가 앞으로 오는게 좋을것같긴 합니당 🤔

2024-07-21 10:57 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/data/repository/TypeRepository.kt
> +import poke.rogue.helper.data.model.TypeInfo
추후에 심지가 만들어놓은 type enum 모델로 변경 예정이라 분리를 위해 그대로 두었습니당~

2024-07-21 11:01 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/data/repository/TypeRepository.kt
>  class TypeRepository(private val localTypeDataSource: LocalTypeDataSource) {
넵넵 ~

2024-07-21 11:18 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/data/datasource/LocalTypeDataSource.kt
> +    fun allTypes(): List<TypeInfo> = typeData.allTypes
사실 엘레강트 오브젝트를 읽어보지 않아서 명사형 함수 네이밍에 대한 감이 없었는데요, 
블로그 정리글들을 찾아보니 어떤 느낌인건지 조금 알것같네요,,  🤔

2024-07-21 12:35 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/data/datasource/LocalTypeDataSource.kt
> +    fun allTypes(): List<TypeInfo> = typeData.allTypes
호불호가 굉장히 심하고 익숙치 않은 부분이라 우리 컨벤션 잡을 때 조심스럽긴 했어요 ㅋㅋㅋ

2024-07-21 12:40 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/selection/TypeSelectionBottomSheetFragment.kt
> +            sharedViewModel.typeEvent.collect {
`<TypeViewModel>`이렇게 뷰모델 타입을 명시적으로 지정해줘야 하는 군요,,,🫢

초반에 `activityViewModel()` 로 설정했을때 자꾸 터지길래  `ViewModelProvider` 로 구현해놓았는데 ,,, 감사합니당!!!! 🥹

2024-07-21 15:44 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeViewModel.kt
반영하여 리팩토링 해보겠슴니다ㅏ

2024-07-21 17:40 UTC, JoYehyun99 commented on android/app/src/main/res/layout/activity_type.xml
> +            type="poke.rogue.helper.presentation.type.model.TypeUiModel" />
넵 맞습니다아

2024-07-21 17:43 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/result/TypeResultViewHolder.kt
> +    }
`isMyType` 결과에 따라서 `이(가)` 혹은 `에게` 로 텍스트 내용이 변경되는데, 이에 대해 설정하는 부분을 UiModel로 매핑하는 Mapper 에 넣어야할지, 이렇게 뷰홀더에 넣어야할지 고민이 됩니다,,, 🤔

2024-07-22 06:39 UTC, murjune approved these changes
긴 작업 고생하셨습니다 😄

2024-07-22 06:42 UTC, sh1mj1 approved these changes
고생하셨습니다!!!

코멘트를 조금 남겼는데 해당 화면에서 기능 추가부터 하는 것으로 넘어가는 게 좋아보입니다!
나중에 리팩터링 필요한 부분 진행하시는 게 좋을 것 같아요!

2024-07-22 06:42 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeActivity.kt
> +            lifecycleOwner = this@TypeActivity
👍👍👍
viewmodel 을 데이터바인딩해줄 때는, lifecycleOwner 를 이렇게 해주어야 `LifecycleOwner.repeatOnStarted` 함수를 사용할 수 있네요~

2024-07-22 06:42 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeActivity.kt
> +        repeatOnStarted {
`repeatOnStarted` 단위로 함수로 뺄 수도 있을 것 같아요.

2024-07-22 06:42 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeHandler.kt
> +    fun startSelection(selectorType: SelectorType)
👍👍👍👍

2024-07-22 06:42 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeSelectionStates.kt
> +data class TypeSelectionStates(
여기에 타입 상태가 모두 모아졌군용

2024-07-22 06:42 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeSelectionStates.kt
> +fun TypeSelectionUiState.isSelected(): Boolean = this is TypeSelectionUiState.Selected
private 함수가 되어도 될 것 같아요!

2024-07-22 06:42 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeSelectionStates.kt
> +    val isMyTypeSelected: Boolean
저라면 `val myTypeIsSelected: Boolean` 라고 할 것 같긴 합니다. 
하지만 지금 네이밍도 좋아요!!! 👍👍👍

2024-07-22 06:42 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/data/repository/TypeRepository.kt
> +    fun matchedTypesAgainstMyType(myTypeId: Int): List<MatchedTypes>
리턴값이 있는 빌더 함수 네이밍 컨벤션 👍👍👍

2024-07-22 06:42 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/data/repository/DefaultTypeRepository.kt
> +            .filter { it.matchedResult != MatchedResult.NORMAL }
매치 결과가 1 배인 것이 NORMAL 이군요.
이전 회의 때 `대등한` 으로 한다고 했던 것 같아요

2024-07-22 06:47 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/data/repository/DefaultTypeRepository.kt
> +            .filter { it.matchedResult != MatchedResult.NORMAL }
넵 변경된 기능 부분들은 다음 PR에 담을 예정임니다ㅏㅏ

2024-07-22 07:45 UTC, kkosang approved these changes
리팩토링 하느라 고생하셨습니다 👍

2024-07-22 07:45 UTC, kkosang commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeHandler.kt
> +    fun removeSelection(selectorType: SelectorType)
컨벤션 좋습니다 👍
인터페이스의 이름의 경우에는 Listener,Handler에 따라 추후 변경될 수도 있겠네요 !

2024-07-22 07:45 UTC, kkosang commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeSelectionStates.kt
> +    val isMyTypeSelected: Boolean
코틀린에서 Boolean 타입의 프로퍼티를 사용할 때, 자동으로 `is` prefix를 사용해서 getter/setter를 만드는걸로 알고 있어요 !!

2024-07-22 08:50 UTC, merged