[BE-FEAT] 데이터베이스 버전 확인 API 생성
woowacourse-teams/2024-pokerogue-helper pull request #382
Opened 2024-10-21 07:35 UTC by jinchiim

## 🍄 PR 확인 사항
PR이 다음 요구 사항을 충족하는지 확인하세요. :

- [x][ API 명세서가 업데이트 혹은 작성이 되어 있나요? ](https://www.notion.so/eugenedev/ae3a3bfecca6497faeb0d7ed3aea8e07?pvs=4)

## 현재 작업은 어떤 이슈를 해결한 것인지 설명해주세요.
> Issue Number: #380 

- [x] 데이터베이스 버전 확인 API 생성
- [x]  yml 에 데이터베이스 버전 값 생성
- [ ] prod에는 1, dev에는 2로 넣어두기

## 기존 코드에서 변경된 점이 있다면 설명해주세요. (추가 X)

- [x] 있음
- [ ] 없음

기존에 배포 버전 깃허브 브랜치가 없어서 `release` 브랜치에 지금까지의 커밋을 체리픽해 가져왔습니다.
제가 올린 커밋은 하나 뿐이니

> [**코드리뷰는 여기에서 부탁드립니다~**
](https://github.com/woowacourse-teams/2024-pokerogue-helper/pull/382/commits/821f48ddf6b1a87dde41aed045b3890a12d42e07)

2024-10-21 07:36 UTC, jinchiim commented
/noti PR 올렸습니다~ 확인해주샤용

2024-10-21 07:54 UTC, jongmee requested changes
폴라 고생하셨습니다!! 간단하게 리뷰 달았어요 💝

2024-10-21 07:54 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/global/databaseversion/DatabaseVersion.java
> +    private String version;
생성자 주입으로 받는게 테스트 하기도 좋고 유지보수하기 좋은 구조가 될 수 있을 것 같아요!

2024-10-21 07:54 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/global/databaseversion/DatabaseVersionResponse.java
> +public class DatabaseVersionResponse {
요기는 record 사용 안한 이유가 있을까요?!

2024-10-21 13:05 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/global/databaseversion/DatabaseVersion.java
> +    private String version;
그렇게 한다면 결국 외부에서 값을 받을 수 있는 상태가 되지 않나요? 🥹

테스트는 `@TestPropertySource` 를 사용해도 되고요!
새로 테스트 추가했습니다!

2024-10-21 13:16 UTC, jinchiim commented
/noti 미아 리뷰에 코멘트 완료! ✔️ 확인해주세요!

2024-10-21 16:35 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/global/databaseversion/DatabaseVersion.java
> +    private String version;
<image width=300 src = "https://github.com/user-attachments/assets/6d81acd2-b496-4960-a57b-7783800305ac">

~폴라는 계획이 다 있구나..~

오 그런 의도가 있군요! 굉장히 중요한 객체니까 좋은 접근이네요 👍

2024-10-22 01:22 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/global/databaseversion/DatabaseVersionResponse.java
> +public class DatabaseVersionResponse {
`public` 생성자를 없애기 위함이었군요!! 👍

2024-10-22 01:22 UTC, jongmee approved these changes
어푸룹 😊

2024-10-22 01:27 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/global/databaseversion/DatabaseVersion.java
> +    private String version;
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-10-22 05:38 UTC, dwax1324 approved these changes
good

2024-10-22 06:04 UTC, merged