[BE-FEAT] PokeApi를 활용한 DB 업데이트 API
woowacourse-teams/2024-pokerogue-helper pull request #48
Opened 2024-07-20 11:16 UTC by unifolio0

## 🍄 PR 확인 사항
PR이 다음 요구 사항을 충족하는지 확인하세요. :

- [x] API 명세서가 업데이트 혹은 작성이 되어 있나요?

## 현재 작업은 어떤 이슈를 해결한 것인지 설명해주세요.
> Issue Number: #43 

- [x] PokeApi에서 포켓몬 정보를 받아 DB 업데이트
- [x] PokeApi에서 타입 정보를 받아 DB 업데이트
- [x] PokeApi에서 특성 정보를 받아 DB 업데이트

## 기존 코드에서 변경된 점이 있다면 설명해주세요. (추가 X)

- [x] 있음
- [ ] 없음

1. 도메인에 생성자 어노테이션 추가
2. Pokemon에 koName 필드 추가
3. PokemonType, PokemonAbility, Pokemon의 name에 unique 속성 부여

2024-07-22 05:57 UTC, jongmee requested changes
비토!!! 완전 고생하셨습니다 😊 파일 수에서 노고가 느껴집니다 🥲 변경 사항도 많아서 리뷰를 나눠서 달아볼까 합니다 ㅎㅎ.. 꼼꼼하게 잘 해주셨네용 👍

2024-07-22 05:57 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/controller/PokemonAbilityController.java
> +    @GetMapping("api/v1/update/ability")
🍄 개인적으로 꼭 바뀌었으면 하는 점
1) HTTP method: 서버에 변경을 요청하는 것이니까 `POST`가 `GET`보다 적절할 것 같아요 ! 다 삭제 했다가 새로운 버전의 데이터들을 생성하는 것이므로 `PATCH`보다도 `POST`가 적절할 것 같아요 😊
2) `/update`라는 uri: HTTP method로 행위를 표현하고 uri는 자원을 식별하는 것이기 때문에 요 표현보다는 자원만 명시하는 게 좋을 것 같아요 ! `api/v1/abilities` 에 POST method도 괜찮을 것 같고, 디비 세팅을 명시하고 싶으면 `api/v1/setting/abilities`도 좋을 것 같아용
3) `api/v1/update/ability` ➡️ `/api/v1/update/abilities` (맨 앞에 `/` 추가, `ability`를 복수로 변경)

🍄 논의해보고 싶은 점
`1) 클라이언트가 실수로 해당 api에 요청`하거나 `2) 외부에서 해당 api에 요청`할 경우 불필요하게 많은 데이터들이 삭제 및 추가될 것 같아요. 어떤 보안 조치를 취할 수 있을까요 ? 아예 api로 안 만들고 스케줄러를 쓰는 방법, Nginx나 Springboot 인터셉터로 보안 설정 추가 등이 생각나네요 !

2024-07-22 05:57 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/client/PokeClient.java
> +    public CountResponse getAbilityListSize() {
(제안) 함수 네이밍
`getAbilityListSize` ➡️ `getAbilityResponsesCount`
`getAbilityList` ➡️ `getAbilityResponses`

자료구조에 의존적이지 않은 네이밍 어떤가요 ?! 😚

2024-07-22 05:57 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +    @Transactional
`@Transactional`을 여기에만 단 이유가 있을까요 ?! 이 서비스의 모든 메소드는 다 트랜잭션이 필요해보여서 클래스 위에 한 번 다는 것도 좋을 것 같아용 😊

2024-07-22 05:57 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +    @Transactional
(제안) 조금 더 생각해보니 모든 DB 업데이트 (포켓몬, 타입, 특성)는 일관적으로 다 되거나 다 실패해야 할 것 같습니다. (제 생각) api를 다 따로 두는게 맞을까요 ?? 🤔

2024-07-22 05:57 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +        pokemonTypeMappingRepository.deleteAllInBatch();
PokemonTypeMapping 데이터들을 여기에서 삭제해주어야 하는 이유가 궁금합니다 !!

2024-07-22 05:57 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +        return pokemonAbilityRepository.saveAll(pokemonAbilities);
Id 생성 전략 때문에 batch insert를 할 수 없군요 🥲 

2024-07-22 05:57 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DtoParser.java
> +        return koName;
```java
           names.stream()
                .map(Name::language)
                .map(Language::name)
                .filter(name -> name.equals("ko"))
                .findAny()
                .orElse(NOT_EXIST_KOREAN_NAME);
```
어떤가용 ?! 😚

2024-07-22 05:57 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +        for (int i = 0; i < pokemonListSize.count(); i += 500) {
`i`보다 `offset` 어떤가요? 😉

2024-07-22 05:57 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DtoParser.java
> +public class DtoParser {
전체적으로 Stream API로 대체할 수 있는 부분들이 보입니다 ! 다 검토하기에 시간이 걸리는 거 같아서 일단 이 상태로 RC 하겠습니다 ㅎㅎ 😊

2024-07-22 05:57 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +package com.pokerogue.helper.util;
util 패키지보다 external 패키지에서 함께 관리하는게 좋지 않을까요 ?!

2024-07-22 05:57 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/client/PokeClient.java
> +package com.pokerogue.helper.external.client;
(제안) 패키지 이름 🍄
`client` vs `service` 

`service`라고 꼭 `@Service`만 들어가야 되는건 아니라고 생각합니다 ! 어떤가요 ? ☺️

2024-07-22 05:57 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/client/PokeConfig.java
> +public class PokeConfig {
`PokeConfig `보다 `PokeClientConfig`가 더 분명할 것 같아요 !

2024-07-22 05:57 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +        pokemonMapping(pokemonSaveResponse, savedPokemon);
`savePokemonMapping` 어떨까요 ?? 의미를 파악하기 더 쉬워질 것 같아요~! 😉

2024-07-22 05:57 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +            savedPokemon.getPokemonAbilityMappings().add(pokemonAbilityMapping);
`getter` 사용보다 `addPokemonAbilityMapping` 메소드를 만드는게 더 좋을 것 같네요 !

개인적으로 양방향 조회용 관계에 저장하지 않아도 될 것 같습니다 🙂 객체 수준에서도 관계를 유지하려고 하는 건데 요 서비스 전체 메소드에서 저장하고 객체를 다시 쓸 일이 없을 것 같아서요 ..!

2024-07-22 06:05 UTC, dwax1324 requested changes
안녕하세요 비토~
힘든 작업이었을텐데 빠르게 구현하신거 보니 역시 대단합니다~👏👏
전체적으로 컨벤션,상수화, 메서드 추출 등에 대한 코멘트가 많네요.

제 생각인데 외부 API를 사용한 데이터베이스 업데이트에 꼭 모두에게 노출된 http호출을 사용해야할까요?
권한 제어도 설정해야 하고 그에 대한 리소스가 더 드는 것 같아서요.

그리고 DTO나, Util, Global 등의 폴더에 `DataSettingService`와 같은 외부 API관련한 파일들이 섞이지 않는게 좋을 것 같아요!
외부 API를 이용해서 데이터베이스를 업데이트할 때, 하나의 모듈처럼 사용할 수 있으면 좋지 않을까요? 기존의 파일과 섞이지 않고 external 폴더 안에만 있으면 더 좋을 것 같습니다!

2024-07-22 07:44 UTC, jinchiim requested changes
우선 1차 리뷰 달았습니다!
엄청난 코드 길이에... 고생했다고 말씀드리고 싶어요! ☺️

정말 포황비토!

2024-07-22 07:44 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/dto/ListResponse.java
> +public record ListResponse(List<NameAndUrl> results) {
이것도 이름 고민해보면 좋겠네요!
집단 지성 도와줘...

2024-07-22 07:44 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/client/PokeClient.java
> +    public CountResponse getTypeListSize() {
해당 부분의 역할을 보니 `API`를 부를때 `limit`를 정하기 위해서 만든 `API`로 여겨졌습니다!
그렇다면 해당 메서드처럼 `ListSize`를 쓴 이름들은 `getMaxTypeCount`는 어떨런지요? 🤔 
구린것 같기도..

2024-07-22 07:44 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +                String[] tokens = nameAndUrl.url().split("/");
`split`이 자주 나오는데 , 내부에 메서드를 정의하거나 비슷한 역할을 하는 객체로 빼는건 어떨까요? ☺️

2024-07-22 07:52 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DtoParser.java
> +        return koName;
해당 로직 Stream으로 수정했습니다!
그런데 `Name`의 필드로 `Language`와 `name`을 가지고 있습니다.
그리고 `Language`의 필드로 `name`을 가지고 있습니다.

이때, `return`해야 될 값이 `Name`의 `Language`의 `name`이 `"ko"`인 것의 `Name`의 `name`값을 필요로 하는 것이어서

```
return names.stream()
                .filter(Name::isKorean)
                .map(Name::name)
                .findAny()
                .orElse(NOT_EXIST_KOREAN_NAME);
```
위 처럼 구현했습니다!

`Name`안에 필드로 `name`이 들어있고 `Language`안에도 `name`이 들어있으니 제가 봐도 헷갈리네요...😭😭

2024-07-22 07:58 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DtoParser.java
> +        }
Stream으로 수정했습니다! ☺️☺️

2024-07-22 07:59 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/client/PokeClient.java
> +package com.pokerogue.helper.external.client;
> 이번 S3 PR에서 저는 Service와 Client를 구분짓고 있어서 저는 패키지를 따로 나누고 싶어요! 🤔

[동의합니다!](https://github.com/woowacourse-teams/2024-pokerogue-helper/pull/52#discussion_r1686109144)

> 그와 별개로 저도 한가지 제안이 있는데요.
패키지를 나누는 것은 좋습니다! 두 가지 방법을 생각해봤는데 지금처럼 `external.pokemon`와 `external.s3`로 하거나 다른 패키지들과 depth를 동등하게 해서 `pokeapi`와 `image`로 해도 좋을 것 같아요 !

2024-07-22 08:06 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DtoParser.java
> +        return new PokemonAbility(null, abilityResponse.name(), koName, description, "자세한 설명입니다.",
`null`, `빈 리스트`를 주입하는 것보단 필요한 필드만 주는게 좋을 것 같네요! 수정했습니다! ☺️☺️

> +) 우리 1차 배포 때는 자세한설명(detailDescription)을 기본설명(description)으로 하기로 했던 것 같아용 (혹시 아니라면 아무나 댓글 달아주셔요 .. 😅)

api문서를 확인해보니 `description`을 사용하는 것 같아요! 자세한 설명은 한국어 버전이 없어서 따로 번역 라이브러리로 하게 될지도...😭😭

2024-07-22 08:12 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/controller/PokemonAbilityController.java
> +    @GetMapping("api/v1/update/ability")
api에 대해 계속 고민했었는데 `setting/abilities`와 같은 형식이 좋을 것 같네요! 수정했습니다!☺️

2024-07-22 08:14 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/controller/PokemonAbilityController.java
> +    @GetMapping("api/v1/update/ability")
논의해보고 싶은 점에 대해선 저도 폴라 의견에 한 표입니다. 확인해보니 포켓몬이 새로 추가되는게 3~4년 주기로 추가된다고 하네요...
그래서 스케쥴러 보다는 api로 한 건데 보안 문제는 생각 못 했습니다 😭😭

이후에 다 같이 고민해보는 게 좋을 것 같아요

2024-07-22 08:14 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/client/PokeClient.java
> +    public CountResponse getAbilityListSize() {
수정했습니다! ☺️☺️

2024-07-22 08:15 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +        pokemonMapping(pokemonSaveResponse, savedPokemon);
수정했습니다! ☺️☺️

2024-07-22 08:39 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +        for (int i = 0; i < pokemonListSize.count(); i += 500) {
그편이 더 의미 전달에 좋을 것 같네요.
수정했습니다!😊

2024-07-22 08:42 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/client/PokeClient.java
> +    public CountResponse getTypeListSize() {
아쉽지만 `getMaxTypeCount`는 우리와 함께 갈 수 없습니다...😭😭

2024-07-22 08:45 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/dto/ability/FlavorTextEntry.java
> +public record FlavorTextEntry(String flavor_text, Language language) {
해당 부분은 만약 CamelCase로 쓰게 되면 RestClient로 외부 Api에서 받아온 JSON을 파싱할 때 동일한 변수명으로 인식하지 못 해 `null`이나 기본 값이 들어오게 됩니다...😭😭

주말에 위의 이유로 오류 터졌을 때 이유를 찾아봤지만 못 찾았네요...😭😭

2024-07-22 08:45 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/dto/ability/AbilityResponse.java
> +public record AbilityResponse(List<FlavorTextEntry> flavor_text_entries, String name, List<Name> names,
https://github.com/woowacourse-teams/2024-pokerogue-helper/pull/48#discussion_r1686194094
링크의 코멘트에 적었습니다...😭😭

2024-07-22 08:53 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/controller/PokemonController.java
> +        return new ApiResponse<>("포켓몬 저장 완료", savedPokemons);
습관적으로 컨트롤러의 메서드에서 결과 값을 반환하도록 했었네요...
수정했습니다! ☺️☺️

2024-07-22 08:53 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/controller/PokemonAbilityController.java
> +    }
습관적으로 컨트롤러의 메서드에서 결과 값을 반환하도록 했었네요...
수정했습니다! ☺️☺️

2024-07-22 08:57 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/type/controller/PokemonTypeController.java
> +        return new ApiResponse<>("타입 정보 업데이트", savedPokemonTypes);
https://github.com/woowacourse-teams/2024-pokerogue-helper/pull/48#discussion_r1686204505
수정했습니다! ☺️☺️

2024-07-22 08:59 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/client/PokeConfig.java
> +public class PokeConfig {
수정했습니다! ☺️☺️

2024-07-22 09:01 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/client/PokeConfig.java
> +                .withReadTimeout(Duration.ofSeconds(30));
수정했습니다! ☺️☺️

2024-07-22 09:03 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/dto/pokemon/PokemonDetail.java
> +                            List<String> abilityNameList, List<String> typeNameList) {
수정했습니다! ☺️☺️

2024-07-22 09:11 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +                String[] tokens = nameAndUrl.url().split("/");
해당 로직을 객체로 빼는 것보단 메서드로 정의하는 게 좋을 것 같아 메서드로 추출했습니다! ☺️☺️

2024-07-22 09:14 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +        pokemonTypeMappingRepository.deleteAllInBatch();
삭제할 필요가 없는데 막판에 급하게 하다가 놓쳤나봅니다 😭😭

수정했습니다! 😊😊

2024-07-22 09:16 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +        pokemonTypeRepository.deleteAllInBatch();
해당 부분은 타입, 특성, 포켓몬 별로 초기화 해야 될 테이블이 다르도록 수정해서 하나의 메서드로 추출하긴 힘들 것 같아요 😭😭

2024-07-22 09:26 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DtoParser.java
> +        }
Stream으로 수정했습니다! ☺️☺️

2024-07-22 09:26 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DtoParser.java
> +        stats.put("total-stats", totalStats);
Stream으로 수정했습니다! ☺️☺️

2024-07-22 15:10 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/controller/PokemonAbilityController.java
> +    @GetMapping("api/v1/update/ability")
> 이후에 다 같이 고민해보는 게 좋을 것 같아요

좋습니다 👍

2024-07-22 23:29 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DtoParser.java
> +        for (int i = flavorTextEntries.size() - 1; i > -1; i--) {
api에서 한 개의 특성에 대한 설명을 포켓몬 버전별로 전부 보내주는데 버전 발매순으로 정렬해서 보내주고 있습니다.
그래서 가장 최신 버전을 가져오기 위해 역순으로 조회를 했습니다 ☺️☺️

2024-07-22 23:32 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DtoParser.java
> +            }
for loop는 역순으로 조회할 방법을 모르겠네요... 추가로 스트림은 한번 reverse하는 과정이 들어가야 되는데 그게 더 의도가 잘 드러날 지는 모르겠네요...

종이의 의견을 좀 더 자세히 말해주세요 😮

2024-07-22 23:40 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +
수정했습니다! ☺️☺️

2024-07-22 23:52 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +            savedPokemon.getPokemonAbilityMappings().add(pokemonAbilityMapping);
확인해보니 굳이 필요한 작업이 아니었네요. 너무 무의식적으로 코드를 짰나봅니다.😭😭

수정했습니다!

2024-07-22 23:58 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DtoParser.java
> +public class DtoParser {
전체적으로 검토해서 Stream으로 수정했습니다!😊😊

```
for (int i = flavorTextEntries.size() - 1; i > -1; i--) {
            if (flavorTextEntries.get(i).language().name().equals("ko")) {
                description = flavorTextEntries.get(i).flavor_text();
                break;
            }
        }
```
다만 위의 로직은 최신 버전을 찾기 위해 역순으로 for문을 도는데 저는 Stream으로 reverse를 하는 것보단 위의 방식이 더 잘 들어온다고 판단해 수정하지 않았습니다.

미아는 어떻게 생각하시나요? 😮

2024-07-23 00:12 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/dto/ListResponse.java
> +public record ListResponse(List<NameAndUrl> results) {
우선 `InformationLinks`라고 네이밍 했는데 크게 맘에 들진 않네요.😭😭

리더 폴라의 네이밍 실력 좀 보여줘요

2024-07-23 00:15 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/dto/NameAndUrl.java
> +}
우선 `InformationLink`라고 네이밍 했어요.

하지만 폴라 리더의 네이밍 실력으로 더 좋은 이름 지어주세요☺️☺️

2024-07-23 00:18 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +package com.pokerogue.helper.util;
수정했습니다!😊😊

2024-07-23 00:36 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +    @Transactional
> `@Transactional`을 여기에만 단 이유가 있을까요 ?! 이 서비스의 모든 메소드는 다 트랜잭션이 필요해보여서 클래스 위에 한 번 다는 것도 좋을 것 같아용 😊

다른 곳에 없는 이유는 아마 까먹었던 것 같습니다😭😭 아마 Pokemon에서 더티 체킹을 사용해서 그곳에만 단 것 같아요.
추가로 저는 RequestMapping이나 Transactional을 클래스 상단에 다는 것은 해당 어노테이션이 있는 지 확인하기 위해선 항상 위를 올려봐야 한단 점 때문에 선호하지 않습니다.

미아는 어떻게 생각하시나요?😮

2024-07-23 00:39 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +    @Transactional
> (제안) 조금 더 생각해보니 모든 DB 업데이트 (포켓몬, 타입, 특성)는 일관적으로 다 되거나 다 실패해야 할 것 같습니다. (제 생각) api를 다 따로 두는게 맞을까요 ?? 🤔

확인해보니 Type을 업데이트 할 때 PokemonTypeMapping 테이블까지 초기화하는데 만약 Type 테이블만 새로 세팅하고 Pokemon 테이블을 세팅하지 않으면 PokemonTypeMapping 테이블은 빈 상태로 존재하네요.😱

일괄적으로 세팅하도록 수정했습니다!😊😊

2024-07-23 00:44 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +        for (int i = 0; i < pokemonListSize.count(); i += 500) {
상수화 했습니다!☺️☺️

2024-07-23 00:47 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +            pokemonTypeMappingRepository.save(pokemonTypeMapping);
수정했습니다!☺️☺️

2024-07-23 00:57 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +        return pokemonAbilityRepository.saveAll(pokemonAbilities);
batch insert에 대해 모두의 의견을 들을려고 했었는데 물어보는 걸 깜빡했네요😭😭

오늘 다같이 의견 들어보겠습니다!

2024-07-23 01:08 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +    public List<PokemonAbility> savePokemonAbilities() {
도와줘요 폴라 리더 🚀🚀

2024-07-23 01:25 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/controller/PokemonAbilityController.java
> +        return new ApiResponse<>("특성 정보 업데이트", savedPokemonAbilities);
멘트 전달이 필요하다고 생각해요!
간혹 프론트와 소통할때 "어떤 `API`를 말씀하시는 걸까요?" 라고 하는 경우가 있는데
저 같은 경우는 `API` 경로를 말하게 되면 프론트도, 백엔드도 소통과 인지에 시간이 생기더라고요 😮

전달하는 `data`는 `null` 이어도 된다고 생각하는데 비토는 어떻게 생각하실까요 ☺️

2024-07-23 01:53 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/client/PokeClient.java
> +                .body(ListResponse.class);
고민해봤는데 만약 위의 방식을 사용하게 되면 매개 변수로 `getBody(CountResponse.class, "/ability")`와 같이 `CountResponse.class`를 전달해줘야 하는데 이는 객체지향에 어울리지 않는 것 같아요.(제 착각일 수도 있습니다😓)

그리고 같은 구조가 반복되어도 크게 가독성이 떨어진다고 생각되지 않네요. 그래서 아직 적용하진 않았습니다.

종이는 어떻게 생각하나요?😮

2024-07-23 02:00 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +            }
수정했습니다! ☺️☺️
그런데 메서드 네이밍이 맘에 안 드네요😭

종이가 적절한 메서드 이름 추천해주세요☺️☺️

2024-07-23 02:20 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/dto/ListResponse.java
> +// https://pokeapi.co/api/v2/{type, ability, pokemon}/?offset=0&limit={count}
우선 주석으로 설명을 추가했습니다!☺️☺️

그런데 javadoc은 아직 필요성을 느끼진 못 했습니다.

혹시 javadoc을 작성하고자 하는 이유를 좀 더 설명해 줄 수 있나요?😮

2024-07-23 04:44 UTC, jongmee requested changes
비토 리뷰 반영 수고하셨습니다 리뷰가 정말 많..네요 🥲 헷갈려서 해결된 리뷰들은 resolved 해놨습니다 ~!

2024-07-23 04:44 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/service/DataSettingService.java
> +    private void savePokemonAbilities() {
메소드 순서가 컨벤션에 맞지 않는 것 같아요!

```java
public void dataSetting() {

private void dataReset() {

private void savePokemonTypes() {

// savePokemonTypes에서 사용하는 private 메소드들

private void savePokemonAbilities() {

// savePokemonAbilities에서 사용하는 private 메소드들

private void saveAllPokemons() {

// saveAllPokemons에서 사용하는 private 메소드들

// 여러 메소드에서 공통으로 사용하는 private 메소드들
```

2024-07-23 04:44 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/service/DataSettingService.java
> +    private String extractIdFromUrl(InformationLink informationLink) {
여러 메소드에서 공통으로 쓰는건 아래로 내리기로 했던 것 같은데 위키에 빠져있네요 ㅎㅎ.. 제가 기억하게 있는게 맞을까요 ? 🙂

2024-07-23 04:44 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/service/DataSettingService.java
> +    private void saveAllPokemons() {
얘도 역시 `savePokemons()` 어떤가용 😉

밑에 offset이 증가하며 저장하는 `savePokemons`은 `savePokemonsByOffset`처럼 offset이 포함된 메소드명으로 바꾸고요 !

2024-07-23 04:44 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/service/DataSettingService.java
> +            String name = typeInformationLink.type().name();
다른 dto들을 보니 `getter`의 `getter`를 쓰지 않고 메소드를 생성해준 것 같은데 생성한 기준이 어떻게 되나요 ?! 😲

DtoParser에도 이런 `getter`들이 있는 것 같아요!

2024-07-23 04:44 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/infrastructure/DtoParser.java
> +            if (flavorTextEntries.get(i).language().name().equals("ko")) {
1) `Language`의 `isKorean` 메소드를 여기에서도 쓸 수 있겠네요 !
2) `break` 안 걸고 바로 return해도 될 것 같아요!

2024-07-23 04:44 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/infrastructure/DtoParser.java
> +                        StatDetail::getStatName,
(제안) 사소한 거지만.. 저는 개행 안하는게 더 읽기 편한 것 같은데 ..! 어떤가요 😚

2024-07-23 04:44 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +    @Transactional
메소드 위에 바로 쓰는 것 좋습니다 !

2024-07-23 04:44 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DtoParser.java
> +public class DtoParser {
Stream은 가독성 때문에 사용하는 것도 있지만, 행위에 집중하기 위해서 사용하는 것이기 때문에 개인적으로 대부분의 상황에서는 Stream을 더 선호합니다 ☺️ 저라면 해당 부분도 아래처럼 사용할 것 같아요 ! 읽는 사람은 `sorted`, `reversed`, `filter`, `map` 위주로 행위를 바로 파악할 수 있습니다 😊
```java
    return flavorTextEntries.stream()
        .sorted(Comparator.comparingInt(flavorTextEntries::indexOf).reversed())
        .filter(entry -> entry.language().name().isKorean())
        .map(FlavorTextEntry::flavor_text)
        .findFirst()
        .orElse(description);
```

2024-07-23 04:44 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/dto/NameAndUrl.java
> +}
`DataUrl` 어떤가요 ? 아니면 `InformationUrl` ? 개인적으로 `Link`에서 바로 `Url`이 떠오르지 않아서  `Url`이 더 좋은 것 같아요 . 😅 그리고 전체적으로 데이터 저장할 때 `Information`보다 `Data`라는 단어를 더 많이 사용해서 `Data`가 더 좋습니다 ㅎㅎ..

2024-07-23 04:44 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/dto/pokemon/AbilityInformationLink.java
> +public record AbilityInformationLink(InformationLink ability) {
`AbilityInformationLink`와 `TypeInformationLink`는 필드에 `InformationLink`만 가지고 있는데 `InformationLink`를 사용하지 않고 새로운 dto를 사용한 이유가 무엇인가요 ?? 😲

2024-07-23 04:44 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/infrastructure/DtoParser.java
> +package com.pokerogue.helper.external.infrastructure;
패키지 이름을 infrastructure로 한 이유가 무엇일까요 ? DDD의 infrastructure일까요 ?? 😲

2024-07-23 06:21 UTC, jinchiim requested changes
고생하시네요ㅜ
엄청난 코드양에 또 놀랐습니다. 

코멘트 추가로 드렸으니 확인해주세요!
ps) 점점 변수 이름이 깔끔해지는 것 같아 보기 좋습니다! 👍🏻

2024-07-23 06:21 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/external/service/DataSettingService.java
> +        typeNames.remove("다크");
스텔라는 타입 이미지도 있고, 제가 포켓몬을 좋아해서 그런지 스텔라 반짝거리고 이뻐서
이후에도 나올 것 같다는 생각이 듭니다. 제일 최근 신작(스텔라& 바이올렛)에서도 언급이 되기도 했고요?? ☺️

그래서 개인적으로는 18이라는 숫자를 집어넣기 보다는, 
전체 개수에서 `-2`를 하는 식으로 코드를 짜거나 해당 숫자를 가지고 있게 된다면 좀 더 유연하게 새로운 세대에 대처할 수 있는 
코드가 되지 않을까 생각합니다! 🤔

2024-07-23 06:22 UTC, dwax1324 approved these changes
지금 단계에서는 너무 완벽하게 리팩토링하기보다는
1차 배포가 우선이라고 생각해서 approve드립니다! 
고생하셨어요!👍👍

2024-07-23 06:22 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/infrastructure/DtoParser.java
> +package com.pokerogue.helper.external.infrastructure;
저도 궁금합니다 🤔

2024-07-23 06:22 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/dto/NameAndUrl.java
> +}
오 DataUrl 좋아요

2024-07-23 06:28 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +                .map(tokens -> pokeClient.getAbilityResponse(tokens[tokens.length - 1]))
가장 마지막 인덱스가 필요하다니... 어렵네요 🥹

해당 부분이 특정 무언가의 API를 위한 `id`를 찾는 것이라면 그런걸 의미할 수 있지 않을까 싶긴 한데,
한번 해당 메서드를 `nameAndUrl` 객체 안으로 옮겨볼까요?

2024-07-23 06:28 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/dto/ListResponse.java
> +public record ListResponse(List<NameAndUrl> results) {
`DataUrl`!

2024-07-23 06:34 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +    public List<PokemonAbility> savePokemonAbilities() {
요 친구는 다같이 고민이 필요할 것 같으니 1차 데모데이 보다는 2차 데모데이로 넘깁시다.

2024-07-23 06:35 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/controller/PokemonAbilityController.java
> +        return new ApiResponse<>("특성 정보 업데이트", savedPokemonAbilities);
좋아요 👍 👍

2024-07-23 06:35 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DataSettingService.java
> +                .map(tokens -> pokeClient.getAbilityResponse(tokens[tokens.length - 1]))
좋아요 👍 👍

2024-07-23 06:36 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/service/DataSettingService.java
> +    private String extractIdFromUrl(InformationLink informationLink) {
제 기억에는 없긴 한데 이참에 추가해도 좋을 것 같네요. 저는 동의합니다! ☺️

2024-07-23 06:40 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/dto/ListResponse.java
> +// https://pokeapi.co/api/v2/{type, ability, pokemon}/?offset=0&limit={count}
자바클래스나 인터페이스, 생성자, 메서드 등을 설명할 `javadoc`을 사용한다고 하네요.

그냥 제안이었습니다. 😄

> 우선 주석으로 설명을 추가했습니다!

👍👍👍

2024-07-23 06:40 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/infrastructure/DtoParser.java
> +                        StatDetail::getStatName,
디토 입니다!

2024-07-23 08:28 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/service/DataSettingService.java
> +        dataReset();
`setData`, `deleteAll`로 수정했습니다!😊😊

2024-07-23 08:32 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/service/DataSettingService.java
> +    private void savePokemonAbilities() {
수정했습니다!😊😊

2024-07-23 08:36 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/infrastructure/DtoParser.java
> +            if (flavorTextEntries.get(i).language().name().equals("ko")) {
수정했습니다!😊😊

2024-07-23 08:37 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/infrastructure/DtoParser.java
> +                        StatDetail::getStatName,
수정했습니다!😊😊

2024-07-23 08:42 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/dto/NameAndUrl.java
> +}
수정했습니다!☺️☺️

2024-07-23 08:47 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/external/service/DataSettingService.java
> +        typeNames.remove("다크");
전체 개수에서 -2 하는 방향으로 수정했습니다☺️☺️

2024-07-23 08:48 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/external/service/DataSettingService.java
> +        return pokeClient.getTypeResponses(18);
https://github.com/woowacourse-teams/2024-pokerogue-helper/pull/48#discussion_r1687678167

해당 코멘트로 수정한 부분에서 2를 상수화했습니다☺️☺️

2024-07-23 08:53 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/external/service/DataSettingService.java
> +        saveAllPokemonTypeMatching(typeInformationLinks);
수정했습니다☺️☺️

2024-07-23 10:34 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/external/service/DataSettingService.java
> +            String fromKoName = pokemonTypeRepository.findByName(informationLink.name()).orElseThrow().getKoName();
수정했습니다!☺️☺️

2024-07-23 10:37 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/service/DataSettingService.java
> +    private String extractIdFromUrl(InformationLink informationLink) {
수정했습니다!😊😊

2024-07-23 10:39 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/service/DataSettingService.java
> +    private void saveAllPokemons() {
수정했습니다!😊😊

2024-07-23 10:49 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/service/DataSettingService.java
> +            String name = typeInformationLink.type().name();
가급적 생성해주려고 하는데 놓친 것 같습니다😭😭

전체적으로 확인하고 수정했습니다!😊😊

2024-07-23 11:03 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/dto/pokemon/AbilityInformationLink.java
> +public record AbilityInformationLink(InformationLink ability) {
우선 `InformationLink`를 `DataUrl`로 수정해서 이에 맞춰 이유를 적겠습니다.

`AbilityDataUrl`을 만든 이유는 API에서 JSON 형식을 복잡하게 줘서 입니다😭😭
pokemon정보를 받는 API에서 타입이나 특성 정보를 아래와 같이 전달합니다.
```json
"abilities": [
        {
            "ability": {
                "name": "overgrow",
                "url": "https://pokeapi.co/api/v2/ability/65/"
            },
            "is_hidden": false,
            "slot": 1
        },
        {
            "ability": {
                "name": "chlorophyll",
                "url": "https://pokeapi.co/api/v2/ability/34/"
            },
            "is_hidden": true,
            "slot": 3
        }
    ]
```
이때 
1. 전체 포켓몬 정보를 받을 Dto -> `PokemonSaveResponse`
2. `PokemonSaveResponse` 안의 `abilities`를 받을 필드 -> `List<AbilityDataUrl>`
3. `abilities` 필드를 구성하여 안의 `ability`를 받을 Dto -> `AbilityDataUrl`
4. `AbilityDataUrl` 안에서 `ability`를 구성하는 `name`과 `url`을 받을 Dto -> `DataUrl`

이렇게 구성되어 있습니다.
간단히 요약하면 `AbilityDataUrl`을 만들지 않으면 `DataUrl`만으론 json에서 `abilities`안에 있는 `ability`를 받을 수가 없어서 중간 매개체로 만들었습니다.

2024-07-23 11:44 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/util/DtoParser.java
> +public class DtoParser {
> 읽는 사람은 sorted, reversed, filter, map 위주로 행위를 바로 파악할 수 있습니다 😊

이 부분을 읽으니 확 이해되네요
수정했습니다!☺️☺️

2024-07-23 11:59 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/infrastructure/DtoParser.java
> +package com.pokerogue.helper.external.infrastructure;
사실은 정 생각나는 이름이 없어서 `infrastructure`로 네이밍 했습니다😭😭

다시 고민하다가 결국 `parser`로 네이밍 했는데 괜찮은가요?

2024-07-23 12:34 UTC, jinchiim approved these changes
훠우 141개의 리뷰라니... 정말 고생많으셨습니다ㅜㅜ
이후는 다같이 고민해보고 리팩토링 해봐요!! 최고입니다!

2024-07-23 14:28 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/dto/pokemon/AbilityInformationLink.java
> +public record AbilityInformationLink(InformationLink ability) {
> AbilityDataUrl을 만든 이유는 API에서 JSON 형식을 복잡하게 줘서 입니다😭😭

헉쓰 ......... 열심히 설명해주셔서 감사합니다 🥺 고생하셨습니다 !!

2024-07-23 14:36 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/infrastructure/DtoParser.java
> +package com.pokerogue.helper.external.infrastructure;
오 infrastructure 보다 좋습니다 👍 이 클래스는 util도 괜찮을 것 같네요 !

2024-07-23 14:39 UTC, jongmee approved these changes
정말 고생하셨습니다 🥲 아자아자 화이팅 !!

2024-07-23 14:39 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/external/pokemon/service/DataSettingService.java
> +public class DataSettingService {
캬 정말 깔끔해졌네요 👍

2024-07-23 14:39 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/external/infrastructure/DtoParser.java
> +package com.pokerogue.helper.external.infrastructure;
오 infrastructure 보다 좋습니다 👍 이 클래스는 util도 괜찮을 것 같네요 !

2024-07-24 00:41 UTC, merged