[1.2.0AN-FIX] 포켓몬 상세의 진화 정보에서 동일한 포켓몬 클릭 시 토스트 메시지
woowacourse-teams/2024-pokerogue-helper pull request #483
Opened 2024-12-06 12:47 UTC by sh1mj1

- closed #453 
## 작업 영상
[포켓몬 진화 이동.webm](https://github.com/user-attachments/assets/650f45b5-9a2b-496d-ac67-abc899790fdb)

## 작업한 내용
- 포켓몬 상세-진화 프래그먼트에서 현재 화면의 포켓몬을 클릭했을 때 이동하지 않고 토스트 메시지를 보여줍니다.
  - 예: 꼬부기 상세 화면의 진화체 정보에 가면 꼬부기, 어니부기, 거북왕이 있다. 꼬부기 클릭 시에 이동하지 않고 토스트 메시지
- 추가로 포켓몬 상세 화면의 이벤트들을 하나로 병합했습니다.
- 홈 화면/특성 상세 화면/바이옴 상세 화면으로 이동 이벤트 테스트를 추가했습니다.

## PR 포인트
- 뷰모델 테스트에서 포켓몬 상세와 배틀로 이동하는 테스트는 통과가 안 되어서 지웠습니다..
- 원인 아시는 분~~
```kotlin
@Test
fun `포켓몬 상세로 이동한다`() =
    runTest {
        // when
        viewModel.navigateToPokemonDetail("1")

        // then
        val event =
            viewModel.navigationEvent.first {
                it !is PokemonDetailViewModel.NavigationEvent.NONE
            }.also(::println)
        (event is PokemonDetailViewModel.NavigationEvent.ToPokemonDetail) shouldBe true
    }

After waiting for 10s, the test coroutine is not completing
kotlinx.coroutines.test.UncompletedCoroutinesError: After waiting for 10s, the test coroutine is not completing
	at app//kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$2$1.invoke(TestBuilders.kt:349)
	at app//kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$2$1.invoke(TestBuilders.kt:333)
	at app//kotlinx.coroutines.InvokeOnCancelling.invoke(JobSupport.kt:1431)
	at app//kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1477)
	at app//kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:799)
	at app//kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:759)
	at app//kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:675)
	at app//kotlinx.coroutines.JobSupport.cancelCoroutine(JobSupport.kt:662)
	at app//kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:159)
	at app//kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:501)
	at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at app//kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:109)
	at java.base@21.0.3/java.lang.Thread.run(Unknown Source)
```

## 🚀Next Feature

포켐손 상세 스탯바(프로그레스 바)  애니메이션

2024-12-11 11:32 UTC, murjune requested changes
동일 클릭 방지 좋은데요~ 고생하셨습니다 심지  
테스트가 실패하는 이유는 코멘트로 남겨두었어요!!    
추가로, 테스트가 실패해도 일단 코드를 남겨주시면 좋을 것 같아요 ㅋㅋㅋ

2024-12-11 11:32 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
>              .first().pokemon
이 부분 때문에 테스트가 통과하지 않는 것입니다.    
first() 도 collect와 같은 종단 연산자입니다.  
따라서, `PokemonDetailUiState.Success`에 해당하는 uiState가 들어오지 않는 이상 무한정 대기하는데요.  

아래 테스트 환경에서는 uiState 가 Loading 상태이기 때문에 계속 대기하다 10초 timeout에 걸려 테스트를 실패하는 것입니다.

로직 수정이 필요해보입니다~

```kotlin
@Test
fun `포켓몬 상세로 이동한다`() =
    runTest {
        // when
        viewModel.navigateToPokemonDetail("1")

        // then
        val event =
            viewModel.navigationEvent.first {
                it !is PokemonDetailViewModel.NavigationEvent.NONE
            }.also(::println)
        (event is PokemonDetailViewModel.NavigationEvent.ToPokemonDetail) shouldBe true
    }
```

2024-12-11 11:32 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
> +    sealed interface NavigationEvent {
오 다 합치셨군요~ ㅋㅋㅋ 굿

2024-12-11 11:32 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
> +        data object NONE : NavigationEvent
얘는 왜 다 대문자인가요?? 🤔

2024-12-11 14:49 UTC, JoYehyun99 approved these changes
굳굳 👍 수고하셨습니당~~~

2024-12-11 14:49 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
> +    private val _navigationEvent = MutableEventFlow<NavigationEvent>()
깔꼼해졌군뇨  👍

2024-12-13 07:09 UTC, kkosang approved these changes
고생하셨습니다 심지~~! 
오둥이가 이야기 해준 테스트 부분만 수정하면 될 것 같아요 굿 👍

2024-12-13 07:09 UTC, kkosang commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailActivity.kt
> +                toast(
중복 화면이동 토스트메시지 표현 굿입니다 ~!

2024-12-13 08:19 UTC, sh1mj1 commented
/noti 🕯️

오둥이가 말한 부분 잘 보고 수정했습니다!

다시 보니 제가 실수한 부분이 있었네요.
viewModel 에서 update 를 해주어야 uiState 가 업데이트 됩니다.
그런데 제가 이걸 호출하지 않아 놓고서 안 된다고 했네요 🥲

추가로 `updatePokemonDetail` 의 코루틴 스코프 내에서 delay 를 아주 약간 걸어보니 테스트가 터지는 경우가 있었습니다.
현재는 FakeRepository 에서 가져오는 속도가 빨라서 괜찮지만, FakeRepository 의 더미 데이터가 추가되었을 때 테스트가 터질 수도 있다고 판단했습니다.
그래서 테스트에서 `updatePokemonDetail`를 호출 직후에 `advanceUntilIdle()` 호출하도록 했습니다.

2024-12-13 13:05 UTC, murjune requested changes
@sh1mj1 작업 고생하셨습니다 심지 👍  

몇 가지 함께 논의해보면 좋을 것 같은 코드에 comment를 남겨두었어요!

2024-12-13 13:05 UTC, murjune commented on android/app/src/test/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModelTest.kt
> +            advanceUntilIdle()
실제로 서버통신을 하는 환경이라면 `advanceUntilIdle()`이 필요하겠지만, 현재 FakeRepo 에서는 `delay()`를 넣어주고 있지 않아서 동기 처리를 해줄 필요가 없긴 합니다.  

이유는 현재 환경이 단일 스레드 +  suspend 될일 이 없기 때문입니다.  

 해당 `updatePokemonDetail` 코루틴이 작업을 완수하기 전까지`navigateToPokemonDetail` 코루틴은 dispatch될 일이 없을 것이에요

2024-12-13 13:05 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
> +
viewModel 에서 공격적인 프로그래밍 방식하는 것은 위험하다 생각합니다.  
예외가 발생한다면 바로 App이 터져버리기 때문인데요.  

심지는 어떻게 생각하시나요?🤔

2024-12-14 07:48 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
> +            delay(100)
아이고 이걸 남겼네요

2024-12-14 08:28 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModel.kt
> +
오둥이 말이 맞네요!
nullable 하게 하고 successUiState 사용하는 곳에서 success 가 아니면 동작을 안하게 하는 게 낫겠네요.
고맙습니다

2024-12-14 08:31 UTC, sh1mj1 commented on android/app/src/test/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailViewModelTest.kt
> +            advanceUntilIdle()
그렇군요.
단순히 불러오는 속도가 느려질 경우에 문제가 생길 줄 알았어요. 
그래서 delay 를 걸어보고 `advanceUntilIdle` 을 추가했었는데, 싱글 스레드 + suspend 될 일이 없어 괜찮겠네요.

advanceUntilIdle 은 없어도 되겠군요!

2024-12-14 20:40 UTC, murjune approved these changes
작업 고생하셨습니당 심지! 머지 고고링~~

2024-12-15 08:02 UTC, merged