[BE-FEAT] 단일 꿀팁 상세 정보를 불러오는 API
woowacourse-teams/2024-pokerogue-helper pull request #57
Opened 2024-07-22 09:39 UTC by dwax1324

## 🍄 PR 확인 사항
PR이 다음 요구 사항을 충족하는지 확인하세요. :

- [ ] API 명세서가 업데이트 혹은 작성이 되어 있나요?

## 현재 작업은 어떤 이슈를 해결한 것인지 설명해주세요.
> Issue Number: #56 

- [x] 단일 꿀팁 상세 정보를 불러오는 기능

## 기존 코드에서 변경된 점이 있다면 설명해주세요. (추가 X)

- [] 있음
- [x] 없음

2024-07-22 15:29 UTC, jongmee approved these changes
굿 👍

2024-07-23 05:15 UTC, jinchiim requested changes
작은 코멘트 하나만 달았습니다!
수고하셨어요!!

2024-07-23 05:15 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/article/dto/ArticleDetailsResponse.java
> +    public static ArticleDetailsResponse from(final Article article) {
이번 파라미터에 다 final을 붙이신 특별한 이유가 있을까요?? 🤔

2024-07-23 05:18 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/article/dto/ArticleDetailsResponse.java
> +    public static ArticleDetailsResponse from(final Article article) {
인텔리제이 자동 설정을 깜빡했네요 ㅠㅠ
설정 바꾸었습니다 🙂

2024-07-23 05:39 UTC, jinchiim approved these changes
☺️ 수고 많으셨어요~!!

2024-07-23 05:56 UTC, unifolio0 approved these changes
구현 수고하셨습니다 👍 👍

2024-07-23 06:14 UTC, merged