[BE-FEAT] 단일 특성 정보를 불러오는 API
woowacourse-teams/2024-pokerogue-helper pull request #61
Opened 2024-07-22 12:22 UTC by dwax1324

## 🍄 PR 확인 사항
PR이 다음 요구 사항을 충족하는지 확인하세요. :

- [ ] API 명세서가 업데이트 혹은 작성이 되어 있나요?

## 현재 작업은 어떤 이슈를 해결한 것인지 설명해주세요.
> Issue Number: #58 

- [x] 단일 특성 정보를 불러오는 기능

## 기존 코드에서 변경된 점이 있다면 설명해주세요. (추가 X)

- [] 있음
- [x] 없음

2024-07-22 12:24 UTC, dwax1324 commented
그냥 무식하게 포켓몬 싹 다 긁어오고 거기서 같은 특성인 포켓몬들을 걸러냈습니다..
저장되는 데이터를 알 수 있으면 개선이 가능할 것 같습니다..

2024-07-23 05:20 UTC, jinchiim requested changes
사소한 코멘트 하나만 달았습니다!
API 3개 다 수고하셨어요! 👍🏻

2024-07-23 05:20 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
> +                        pokemon.getPokemonAbilityMappings()
이 사이에 한칸 띄워주신 이유가 있을까요?? ☺️

2024-07-23 06:39 UTC, unifolio0 approved these changes
구현 수고하셨습니다 👍 👍

2024-07-23 06:41 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
> +                        pokemon.getPokemonAbilityMappings()
파이리....꼬부...기

파일이 사라졌군요 확인입니다!

2024-07-23 06:42 UTC, unifolio0 requested changes
approve 취소요 😭😭

2024-07-23 06:42 UTC, unifolio0 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
> +                pokemonResponses
아마 정의하는 부분만 각 변수마다 개행을 주고 실제로 사용하는 곳에선 각 변수마다 주는 건 아니였던 것 같은데 아니였나요?🤔

2024-07-23 06:44 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
> +                pokemonResponses
저는 그런 얘기 들은적이 없는데요?🤔

2024-07-23 07:53 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
> +        PokemonAbility ability = pokemonAbilityRepository.findById(id)
(제안) 쿼리 최적화는 개발이 끝나고 나서 해도 되지만 이 부분은 어렵지 않아 보여서 제안해요 !

PokemonAbility의 PokemonAbilityMapping는 지연 로딩 설정이 되어 있어서 밑에서 `ability.getPokemonAbilityMappings()`를 호출하는 순간 쿼리가 한 번 더 날아갑니다.
```sql
    select *
    from pokemon_ability pa
    where pa.id=?

    select *
    from pokemon_ability_mapping pam
    left join pokemon p on p.id=pam.pokemon_id 
    where pam.pokemon_ability_id=?
```

그래서 아래처럼 fetch joing하는게 (`@EntityGraph` 쓰는게 ) 좋을 것 같아요! 
```java
    @Override
    @NonNull
    @Query("""
    select a from PokemonAbility a
    join fetch a.pokemonAbilityMappings m
    join fetch m.pokemon p
    """)
    Optional<PokemonAbility> findById(@NonNull @Param("id") Long id);
```
쿼리를 여러 번 날리면 그만큼 네트워크를 타기 때문에 이 경우에서는 join하는게 더 좋다고 생각합니다 (성능면에서 ) 😊

2024-07-23 08:23 UTC, jongmee requested changes
여러 api 개발하느라 고생하셨읍니다 👍 리뷰 몇 개만 남겼어요 !

2024-07-23 08:23 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/dto/SameAbilityPokemonResponse.java
> +        List<PokemonTypeResponse> pokemonTypeResponses = pokemon.getPokemonTypeMappings().stream()
PokemonService처럼 `  List<PokemonTypeResponse>`를 생성하는건 서비스 클래스에서 하는게 어떤가요 ?? 연관객체가 조회(로딩)되는 것도 여기에서 발생할 수 있기 때문에 일단 서비스 코드에 놓는 게 좋을 것 같아요! 😚

2024-07-23 08:35 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
> +                pokemonResponses
(다 같이) 회의 결과 일단 줄을 넘어가면 개행하기로 했습니다. 🙂

2024-07-23 08:44 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/dto/SameAbilityPokemonResponse.java
> +        List<PokemonTypeResponse> pokemonTypeResponses = pokemon.getPokemonTypeMappings().stream()
코드를 작성하면서 연관객체까지 생각을 못했네요. 😅
피드백 적용했습니다!

2024-07-23 08:50 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
> +        PokemonAbility ability = pokemonAbilityRepository.findById(id)
자세한 리뷰 감사합니다!
지연 로딩.. 쿼리 호출 횟수.. N+1.. 다시 한번 공부해봐야겠네요.
쿼리 최적화 적용했습니다! 🙂

2024-07-23 09:01 UTC, dwax1324 commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
> +        PokemonAbility ability = pokemonAbilityRepository.findById(id)
특성을 불러올 때 `findById`를 사용하고 포켓몬과 같이 불러올 때는 `findByIdWithPokemons`를 사용하도록 바꾸었습니다! 😇

2024-07-23 14:00 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/ability/service/PokemonAbilityService.java
> +        PokemonAbility ability = pokemonAbilityRepository.findById(id)
좋습니다 👍  👍  포켓몬 특성은 포켓몬 목록 없이 찾을 때 (`findById`)도 있을 수 있겠네요!

(추가로, 현재는 OSIV가 켜져 있어서 예외가 발생하지 않지만 영속성 컨텍스트 밖(`@Transactional` 미사용)에서는 `LazyLoadingException`이 발생할 수 있습니다 !! 중요한 포인트인 것 같아서 ..)

2024-07-23 14:02 UTC, jongmee approved these changes
어뿌룹!! 🎉

2024-07-24 02:52 UTC, merged