[AN-FEAT] 상성 화면 세부적인 기능 수정 및 추가
woowacourse-teams/2024-pokerogue-helper pull request #69
Opened 2024-07-24 02:26 UTC by JoYehyun99

- closed #40 
## 작업 영상
[Screen_recording_20240724_111905.webm](https://github.com/user-attachments/assets/c161b270-2b0e-4727-ab02-bb6e921205e9)

## 작업한 내용
- 초기 화면 이미지 적용
- 동일한 상대 타입 선택 금지하도록 설정
- 강한, 약한, 무효한, 대등한 순서로 결과 보여주도록 설정
- 상성 결과 정렬
  - 일단 그리드 레이아웃으로 4개씩 나오도록 설정 해놓았습니다! 나중에 화면 크기별 대응하도록 수정할께요~

## PR 포인트
-  수정해야할 기능이 더 있다면 코멘트 남겨주세요!

## 🚀Next Feature
- 상성 네트워크 통신 준비? (1차 배포에서는 안들어감)

2024-07-24 03:21 UTC, sh1mj1 requested changes
로직과 코드 양이 점점 많아지면서 기능을 추가하는 데도 오래 걸렸을 것 같아요.
그에 따라 코드 리뷰하기도 쉽지 않네요...

양이 많아지면서 조금씩 객체지향에서 멀어지는 듯한 느낌도 어쩔 수 없는 것 같네요.
하지만 기능이 잘 동작하는 것 같아 대단하다고 생각합니다!

정말 고생 많았습니당~ 👍👍👍👍👍

궁금한 점 코멘트 남겨두었습니다.

2024-07-24 03:21 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/data/repository/DefaultTypeRepository.kt
> +        )
`matchedTypes` 함수에서는
기존: 
  나의 타입과 상태 타입들에 대해  레포지토리에서 데이터소스의 mathedTpes 함수를 map 블록 안에서 여러번 호출한다.
현재:
   나의 타입과 상태 타입들에 대해 데이터 소스에서 미리 매핑한다. 레포지토리에서는 단순히 데이터 소스의 함수를 호출하기만 한다.

제가 이해한 게 맞나요?

맞다면, 레포지토리와 데이터 소스에 있던 로직을 전부 데이터 소스로 옮기신 이유가 있으실까요?

2024-07-24 03:21 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/mapper/MatchedResultMapper.kt
> +fun MatchedTypes.toUiModel(
다른 곳의 함수들은 예니가 `toUi()` 라는 함수로 바꾸었던데 이곳은 `UiModel` 이네요. 
통일성을 줄 필요가 있어보여용

2024-07-24 03:21 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/mapper/MatchedResultMapper.kt
> +    ;
👍👍👍👍

2024-07-24 03:21 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/selection/TypeSelectionViewHolder.kt
>      ) {
👍👍👍👍

나중에는 뷰홀더가 하나의 uiModel 이 `TypeUiModel`, `SelectorType`, `Set<TypeUiModel>`, 을 가지도록 바꿀 수 있겠네요.

하지만 지금도 충분히 괜찮습니다.

2024-07-24 04:12 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/mapper/MatchedResultMapper.kt
> +fun MatchedTypes.toUiModel(
`toUi()` 로 땅땅땅

2024-07-24 04:13 UTC, JoYehyun99 commented on android/app/src/test/java/poke/rogue/helper/presentation/type/TypeViewModelTest.kt
> +            }
왜 그런건지는 차차 알아가보도록 하겠슴니다

2024-07-24 04:15 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/data/model/Type.kt
> +enum class Type(val id: Int) {
상성 매칭을 2차원 배열로 구현해놔서 인덱스 값을 통해 가져오도록 하기위해 id 값이 필요합니다!
아이디값으로 상성 결과를 가져오는게 그닥 좋은 방법은 아니지만 우선은 수정하진 않았습니다!

조금 더 좋은 방식으로 고민해볼께용!

2024-07-24 04:57 UTC, kkosang approved these changes
고생하셨습니다 예~~ ㄴㅣ👍

2024-07-24 04:57 UTC, kkosang commented on android/app/src/main/java/poke/rogue/helper/data/model/MatchedResult.kt
> +    NORMAL,
`NORMAL`타입도 있어서 약간 헷갈리긴 한데 좋은 네이밍이...

`NEUTRAL`..?

2024-07-24 04:57 UTC, kkosang commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeViewModel.kt
> +    private val _typeSelectionStates = MutableStateFlow(TypeSelectionStates())
👍👍

2024-07-24 04:58 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/data/repository/DefaultTypeRepository.kt
> +        )
넹 맞슴니다!
현재 data 반환 값은 `결과(강한, 약한 등) : 타입 리스트` 로 되어있는데요, 내타입과 상대 두 타입을 모두 입력했을 때 같은 결과값이 나올때도 다른 MatchedTypes 을 반환하는 문제점을 해결하다 보니 이렇게 구현하게 되었습니다 🙃

다시 시도해보니 기존 방식에서도 현재 결과물을 낼수 있을 것 같아서 기존 방식으로 수정하는게 좋을것같네요!
매핑 로직을 레포지토리에 두는게 더 좋을것같네요!!

2024-07-24 05:06 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/data/repository/DefaultTypeRepository.kt
> +        )
앗 제가 여쭈어본 이유는 정말 궁금해서 여쭈어본 것이었어요!!!

저희 프로젝트에서 저 스스로도 데이터 소스와 레포지토리가 로직을 얼마나 가져가야 할지 궁금해서 여쭈어봤습니다!

2024-07-24 06:55 UTC, JoYehyun99 commented
투표 결과 `NORMAL` 로 땅땅땅 🔔

2024-07-25 08:19 UTC, murjune approved these changes
작업량이 상당했을텐데 진짜 고생하셨습니다 👍👍👍  

코멘트는 네이밍이나 객체지향 관점으로 남겨봤어용

2024-07-26 00:55 UTC, merged

2024-07-26 07:52 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeViewModel.kt
> +                .sortedAndMappedToUi(selectedTypeId = selectedTypeId, isMyType = false)
결론) sort는 ViewModel 에서 해주자?