[AN-FEAT] 여백 없는 이미지로 리사이징하는 Transformation 구현
woowacourse-teams/2024-pokerogue-helper pull request #71
Opened 2024-07-24 03:15 UTC by murjune

- closed #이슈넘버
## 작업 영상

## 작업한 내용
- CropTransformation

## PR 포인트
-

## 🚀Next Feature

2024-07-26 17:16 UTC, murjune commented
@sh1mj1  @kkosang @JoYehyun99 깃 충돌 해결! 리뷰좀요

2024-07-27 10:21 UTC, sh1mj1 requested changes
수고하셨슴둥 오둥!~

그런데 스크롤을 쭉 내리면, 이미지가 로드가 정확히 안되는 포켓몬들이 몇몇 있네요.
아직 정확히 어떤 이유인지는 모르겠어요.
스크롤을 내렸다가 다시 올리면, 정상적으로 이미지가 출력되기도 합니다.

### 시연 영상
시연 환경 API: 30
[왜 깨지는 게 있을까.webm](https://github.com/user-attachments/assets/69340197-4413-4382-aa1b-f82cc2578a9a)

### 로그
- 로그 메시지
    
    Request threw uncaught throwable
    java.lang.IllegalArgumentException: width and height must be > 0
    at android.graphics.Bitmap.createBitmap(Bitmap.java:1113)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:952)
    at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:807)
    at poke.rogue.helper.presentation.util.view.CropTransformation.transform(CropTransformation.kt:18)
    at com.bumptech.glide.load.resource.bitmap.BitmapTransformation.transform(BitmapTransformation.java:83)
    at com.bumptech.glide.load.resource.bitmap.DrawableTransformation.transform(DrawableTransformation.java:61)
    at com.bumptech.glide.load.engine.DecodeJob.onResourceDecoded(DecodeJob.java:578)
    at com.bumptech.glide.load.engine.DecodeJob$DecodeCallback.onResourceDecoded(DecodeJob.java:642)
    at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:60)
    at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:76)
    at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:57)
    at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:539)
    at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:503)
    at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:489)
    at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:434)
    at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:399)
    at com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(DataCacheGenerator.java:100)
    at com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(ByteBufferFileLoader.java:62)
    at com.bumptech.glide.load.engine.DataCacheGenerator.startNext(DataCacheGenerator.java:77)
    at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
    at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:277)
    at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:421)
    at java.lang.Thread.run(Thread.java:923)
    at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run(GlideExecutor.java:380)

2024-07-27 10:21 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/util/view/CropTransformation.kt
> +    private fun noMarginBitmap(original: Bitmap): Bitmap {
오, 네이밍 좋은데요? 👍👍

2024-07-27 15:50 UTC, murjune commented
> Request threw uncaught throwable
java.lang.IllegalArgumentException: width and height must be > 0

흐음 이건 진짜 뷰를 recycle 하는 과정에서 발생하는 문제 같네요..  
정확한 이유는 모르겠습니다 😨   

Scale 하는 작업을 없앴습니다. Scale 작업을 없애니 더 이쁜 것 같기두?

2024-07-27 16:11 UTC, sh1mj1 approved these changes
굉장히 빨리 고쳐주셨네요!! 
고생하셨슴둥 오둥~  리사이클러뷰가 정말 어렵네요..

스케일이을 빼버리니 이미지가 더 나아보이네요.
딱충이처럼 세로로 길죽하거나 꼬마돌처럼 가로로 길쭉한 포켓몬들의 경우에 확실히 이뻐 보이는 것 같습니당

2024-07-29 12:16 UTC, kkosang approved these changes
굿굿 고생하셨습니둥~ 👍

paddingVertical까지 추가하니까 더 예뻐졌네요~~

2024-07-29 12:16 UTC, kkosang commented on android/app/src/main/res/layout/item_pokemon_list_pokemon.xml
> +        android:paddingVertical="8dp"
👍👍

2024-07-30 01:27 UTC, JoYehyun99 approved these changes
굳굳~ 수고하셨습니당~

2024-07-30 01:32 UTC, merged