[AN-UI] 상성 페이지 UI 구현
woowacourse-teams/2024-pokerogue-helper pull request #8
Opened 2024-07-13 08:03 UTC by JoYehyun99

- closed #3
## 작업 영상
[Screen_recording_20240713_165855.webm](https://github.com/user-attachments/assets/8388caf3-2c32-4fb3-9cef-c22c0f8fc4b4)

## 작업한 내용
- 상성 화면 xml 구현 및 연결
- 상성 선택 화면 Bottom Sheet xml 구현 및 연결

## PR 포인트
- 데이터 부분은 화면 확인을 위한 더미용으로만 제작해놓았습니다.
- 색상이나 폰트, 이미지 같은 부분은 추후에 반영할 예정이라 기본 색상 및 이미지로만 설정했습니다. (오둥이 작업 후 합칠 예정!)
- 아직 홈 화면이 없어서 홈화면 텍스트 클릭 시 상성 화면으로 이동하도록 설정해놨습니다.

- 아직 미반영된 사항 
    - spannable 로 글자 색상 지정하는 부분 (강한, 약한, 무효) 

## 🚀Next Feature
- 상성 데이터 로직 구현

2024-07-13 10:23 UTC, murjune commented
@JoYehyun99 

## 예시
```kotlin
class MainActivity {
     override fun onCreate(..) {
        binding.textView.text = buildSpannedString {
            append("에스퍼가 강한 타입")
            setSpan(
                ForegroundColorSpan(Color.RED),
                5,
                7,
                Spanned.SPAN_EXCLUSIVE_EXCLUSIVE
            )
        }
    }
}
```
![image](https://github.com/user-attachments/assets/d60b38ed-fe77-4251-9187-2cc14cd5a8c8)  

[androidx.core.text.SpannableStringBuilder](https://developer.android.com/reference/kotlin/androidx/core/text/package-summary#extension-functions-summary)에서 다양한 함수들을 제공하니 살펴보시길 바라요

[SpannableString 공식문서](https://developer.android.com/develop/ui/views/text-and-emoji/spans?hl=ko#java)

2024-07-13 11:52 UTC, murjune requested changes
고생하셨습니다!! 코멘트를 꽤 많이 남겼는데, 논의해보고 싶은 부분이 있다면 언제든지 comment 달아주세요!

2024-07-13 11:52 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeActivity.kt
> +    }
전역으로 fragment 를 들고 있는 것은 매우 위험할 수 있습니다.  
tag 를 통해 fragment manager에 해당 fragment 가 등록되어있는지 확인하는 절차를 갖거나 매번 생성하는 것이 적절할 것 같습니다

2024-07-13 11:52 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeActivity.kt
> +    }
```suggestion   TypeSelectionBottomSheetFragment().show(supportFragmentManager, TypeSelectionBottomSheetFragment.TAG)
    }
```
위에 제가 남긴 코멘트와 동일합니다.  
 혹은 tag를 통해 해당 프래그먼트가 존재하는지 확인하고 생성하는 것이 바람직할 것입니다.

버튼을 빠르게 클릭하면 앱이 crash 납니다.

https://github.com/user-attachments/assets/897d045c-04f4-4c8c-a0d7-14483ba93a4f


![image](https://github.com/user-attachments/assets/5243e3fb-6f5c-4207-9291-de3d2bf1e86a)

2024-07-13 11:52 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeResultCustomView.kt
> +class TypeResultCustomView(context: Context, attrs: AttributeSet) :
```suggestion
class TypeResultView(context: Context, attrs: AttributeSet) :
```
Custom은 빼도 되지 않을까요?

2024-07-13 11:52 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeResultCustomView.kt
> +}
```suggestion
private fun bind(typeResult: TypeMatchedResultUiModel) {
        binding.typeResult = typeResult
        binding.ivResultMyType.setImageResource(typeResult.typeIconResId)

        binding.rvResultMatchedTypes.layoutManager = flexboxLayoutManager
        binding.rvResultMatchedTypes.adapter = TypeResultAdapter(typeResult.matchedItem)
    }

    companion object {
        @JvmStatic
        @BindingAdapter("typeResult")
        fun setTypeResult(view: TypeResultCustomView, typeResult: TypeMatchedResultUiModel) {
            view.bind(typeResult)
        }
    }
```

BindingAdapter 를 활용해서 dataBinding 을 적용해보시죠!
추후 viewModel 을 binding 시킬 때 편할 것입니다 ㅎ ㅎ
```xml
<poke.rogue.helper.presentation.type.TypeResultCustomView
                    android:id="@+id/included_type_strong"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="32dp"
                    app:layout_constraintEnd_toEndOf="@id/gl_end"
                    app:layout_constraintStart_toStartOf="@id/gl_start"
                    app:layout_constraintTop_toBottomOf="@id/tv_type_result_title"
                    app:typeResult="@{typeResult}" />
```

2024-07-13 11:52 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeResultViewHolder.kt
> +        binding.ivTypeNameIcon.setImageResource(typeItem.iconResId)
제가 imageRes 는 바인딩 어뎁터를 추가 설정을 안했군요..

```kotlin
// CommonBIndingAdapter
@BindingAdapter("imageRes")
fun ImageView.setImageRes(imageRes: Int) {
    setImageResource(imageRes)
}
```

추가하도록 하겠습니다

2024-07-13 11:52 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/type/typeselection/TypeSelectionAdapter.kt
> +    RecyclerView.Adapter<TypeSelectionViewHolder>() {
ViewModel 작업할 때 ListAdapter 로 바꿔주시는건가요?!

2024-07-13 11:52 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/type/typeselection/TypeSelectionBottomSheetFragment.kt
> +    private val binding get() = _binding!!
`!!` 보다는 예외를 정의해 넘겨주는건 어떨까요?
```suggestion
    private val binding get() = _binding ?: error("error msg..")
```

2024-07-13 11:52 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/type/typeselection/TypeSelectionBottomSheetFragment.kt
> +            GridSpacingItemDecoration(spanCount = 4, spacing = 19.dp, includeEdge = false)
👍 👍 👍

2024-07-13 11:52 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/type/typeselection/TypeSelectionViewHolder.kt
> +        binding.tvTypeChoiceName.text = typeItem.name
이것도 나중에 commonBindingAdapter 추가하게되면 databinding으로 바꿔주세요!

2024-07-13 11:52 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/data/mapper/TypeMapper.kt
> +fun TypeInfo.toSelectionUiModel(): TypeUiModel {
UiModel 로 매핑해주는 작업은 `data` 에서 할 작업이 아닙니다.  
해당 매퍼에서는 `entity, dto`를 `data`로 매핑해주는 공간입니다.

uimodel 로 매핑해주는 것은 presentation 영역에서 해주세요!

2024-07-13 11:52 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/data/mapper/TypeMatchedResultMapper.kt
> +fun MatchedResult.toString(): String {
1. 네이밍이 toString() 인 경우 `Any` 의 toString() 과 네이밍이 겹쳐 예상치 못한 동작을 할 가능성이 보입니다. 다른 네이밍으로 바꿔주세요

2. 해당 로직은 presentation으로 가야하지 않을까요? String의 경우 Ui 영역이라 판단 됩니다.

3. 만약, 해당 함수를 추가할지라도 class 내에 선언하는 것이 아닌 확장함수로 만드신 이유가 궁금합니다

2024-07-13 11:52 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/data/mapper/TypeMatchedResultMapper.kt
> +        else -> ""
1. INVALID 대신 `Void` 는 어떨까요? INVALID 는 `유효하지 않은` 이란 느낌이 강해서요!

2. enum class 를 사용할 때 `else` 문은 지양해야합니다. 
```suggestion
    return when (this) {
        MatchedResult.STRONG -> "강한"
        MatchedResult.WEAK -> "약한"
        MatchedResult.VOID -> "무효한"
        NORMAL -> "일반"
```

3. 개인적으로 `""` 가 넘어왔을 경우는 논리 에러라 판단됩니다. 빈 문자열로 넘어왔을 경우에 개발자가 에러가 발생했다는 것을 인지하기 힘들지 않을까요??

2024-07-13 11:52 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/local/dao/TypeDao.kt
> +    val allTypes =
추가하느라 고생하셨습니다 👍

2024-07-14 07:56 UTC, sh1mj1 reviewed
고생하셨습니다. 예니!!!
오늘 생일 정말로 축하합니다!!!!!
오늘 즐거운 시간 보내세요!,
피드백 확인 후에 궁금한 점이 있으시면 편하게 DM 주십쇼!!!!

2024-07-14 07:56 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeResultAdapter.kt
> +    RecyclerView.Adapter<TypeResultViewHolder>() {
ListAdapter 가 아닌 RecyclerView.Adapter 를 사용한 이유가 따로 있을까요?
리사이클러뷰가 필요한 다른 화면에서는 대부분 ListAdapter 를 사용할 것 같아요

2024-07-14 07:56 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeResultCustomView.kt
> +        binding.rvResultMatchedTypes.adapter = TypeResultAdapter(typeResult.matchedItem)
`binding.apply{ ... }` 를 사용하면 반복되는 binding 이 줄어들어 코드 작성 시 편할 것 같아요!

2024-07-14 07:56 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/model/TypeMatchedResultUiModel.kt
> +    val isMyType: Boolean,
`isMyType` 이 필요한 이유가 있나요?

2024-07-14 07:56 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/typeselection/TypeSelectionBottomSheetFragment.kt
> +            GridSpacingItemDecoration(spanCount = 4, spacing = 19.dp, includeEdge = false)
아하 spacing 에 `Int.dp` 확장함수를 이렇게 작성해야 하는군요!!! :)

2024-07-14 07:56 UTC, sh1mj1 commented on android/app/src/main/res/values/themes.xml
오 style 과 theme 로 바로 지정해주셨네요! :D

2024-07-14 07:56 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeActivity.kt
> +            TypeMatchedResultUiModel("페어리", R.drawable.img_property_tmp_2, true, "강한 타입", TypeDao.allTypes.map { it.toResultUiModel() })
사소한 부분이지만, 저는 개인적으로 멤버 참조를 사용하는 게 읽기 좋아서 그렇게 사용하고 있기는 합니다.
`TypeDao.allTypes.map(TypeInfo::toResultUiModel)`

2024-07-14 07:56 UTC, sh1mj1 commented on android/app/src/main/res/layout/activity_type.xml
> +                    app:layout_constraintGuide_begin="24dp" />
가이드 라인을 사용하면 뷰를 그리는 동안 실제로 편함이 느껴지시나요?
제가 가이드라인을 거의 사용하지 않았어서 궁금하네요~

2024-07-14 07:56 UTC, sh1mj1 commented on android/app/src/main/res/layout/item_type_choice.xml
> +            android:id="@+id/tv_type_choice_name"
텍스트 색이 흰색이 되어야 할 것 같아요

2024-07-14 07:56 UTC, sh1mj1 commented on android/app/src/main/res/layout/item_type_result.xml
> +        <androidx.recyclerview.widget.RecyclerView
![image](https://github.com/user-attachments/assets/fe716549-5b32-4d9c-b7eb-e4fdc298bc7b)
위 이미지처럼 상성 결과 화면이 사진처럼 열과 행이 잘 맞춰줘서 나오지 않는데, 
대책을 이야기해봐야 할 것 같아요.

1. 저는  `item_type_name.xml` 에서 아이콘이 먼저 나오도록 한 후에 
텍스트뷰에
```
android:ellipsize="end"
android:maxLines="1"
```
을 주고,
2. 
```kotlin
val gridLayoutManager = GridLayoutManager(context, 4)
        binding.rvResultMatchedTypes.layoutManager = gridLayoutManager
        binding.rvResultMatchedTypes.adapter = TypeResultAdapter(typeResult.matchedItem)
```

3. 디바이스 크기에 맞춰 텍스트 크기를 결정하도록 하는 것 정도 밖에 생각이 안나네요.
아래 이미지는 3은 적용하지 않아서 페어리 타입이 `페..` 로 나타나는 모습입니다.
![image](https://github.com/user-attachments/assets/b77f4932-8393-4560-b06b-28e6766c6d42)

2024-07-14 07:56 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeResultCustomView.kt
> +    }
init 블록 내부가 아닌 아닌, lazy 하게 binding 과 flexboxLayoutManager 를 선언하는 것과는 무슨 차이가 있나요?

```kotlin
private val binding: ItemTypeResultBinding by lazy {
        ItemTypeResultBinding.inflate(LayoutInflater.from(context), this, true)
    }
    private val flexboxLayoutManager: FlexboxLayoutManager by lazy {
        FlexboxLayoutManager(context).apply {
            flexWrap = FlexWrap.WRAP
            flexDirection = FlexDirection.ROW
            justifyContent = JustifyContent.FLEX_START
        }
    }
```

2024-07-14 09:59 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/data/mapper/TypeMatchedResultMapper.kt
> +        else -> ""
`INEFFECTIVE` 도 좋네용

2024-07-14 10:02 UTC, murjune commented on android/app/src/main/res/layout/activity_type.xml
> +                    app:layout_constraintGuide_begin="24dp" />
저도 궁금하네용 (순수하게)

2024-07-14 10:04 UTC, murjune commented on android/app/src/main/res/layout/item_type_choice.xml
> +            android:id="@+id/tv_type_choice_name"
디자인 디테일한 부분은 제가 #7 이 부분 작업이 끝나고 추가해달라고 요청했습니다 :D

2024-07-14 10:06 UTC, murjune commented on android/app/src/main/res/layout/item_type_result.xml
> +        <androidx.recyclerview.widget.RecyclerView
`ellipsize` 의 경우는 전 반대입니다. 부정확한 정보를 주는 것 같아서요!  
이 부분은 디자이너 센세 @jinchiim  의 의견 및 전체 팀원들의 의견이 중요해보입니다.

2024-07-14 16:13 UTC, kkosang commented
고생하셨습니다~~🤓
앞에서 남긴 피드백을 보고 저도 학습이 되네요 !
오둥이와 심지가 남겨준 피드백만 반영해주시면 될 것 같습니다 !!

2024-07-14 16:13 UTC, kkosang approved these changes

2024-07-14 16:13 UTC, kkosang commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeActivity.kt
> +    }
왜 위험한 것인지 찾아봤는데 액티비티와 프래그먼트의 생명주기가 달라서 그런 것 같군요 !

2024-07-15 04:24 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeActivity.kt
> +    }
@JoYehyun99 답변좀..

2024-07-15 05:20 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeResultCustomView.kt
> +}
우왕 커스텀뷰 처음 사용해보는데 좋은 정보 감사합니당 👍 👍

2024-07-15 05:23 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/typeselection/TypeSelectionAdapter.kt
> +    RecyclerView.Adapter<TypeSelectionViewHolder>() {
흠
데이터에 변화(추가, 삭제 등)가 있는 부분도 아니고, 바텀 시트를 매번 생성하게 되면 어차피 Adapter도 새로 생성되는 거라
굳이 `ListAdapter`를 사용하지 않아도 될 거라고 생각했었는데 어떻게 생각하시나요!

2024-07-15 05:24 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/typeselection/TypeSelectionBottomSheetFragment.kt
> +    private val binding get() = _binding!!
넵 `!!` 대신 `requireNonNull` 이런식으로 수정해보겠습니다~

2024-07-15 05:55 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/data/mapper/TypeMatchedResultMapper.kt
> +fun MatchedResult.toString(): String {
1,2 : 넴 🫡
3 : Ui 데이터로 매핑해주는 작업이라고 생각해서 mapper 형식으로 따로 분리했습니다! 지정 색상또한 이러한 방식으로 구현할 예정이었습니다!

2024-07-15 05:56 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/data/mapper/TypeMatchedResultMapper.kt
> +        else -> ""
넵 `INEFFECTIVE `로 변경할께용

2024-07-15 06:00 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeResultAdapter.kt
> +    RecyclerView.Adapter<TypeResultViewHolder>() {
https://github.com/woowacourse-teams/2024-pokerogue-helper/pull/8#discussion_r1677323000
해당 코멘트와 동일합니다!

2024-07-15 06:02 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/model/TypeMatchedResultUiModel.kt
> +    val isMyType: Boolean,
내 타입만 선택 or 상대 타입만 선택에 따라서 보여지는 텍스트의 위치가 달라지는데, 이를 처리하기 위해서 넣었습니다! 
네이밍을 수정해도 좋을 것 같다는 생각이 드네요 🙃

2024-07-15 06:03 UTC, JoYehyun99 commented on android/app/src/main/res/layout/activity_type.xml
> +                    app:layout_constraintGuide_begin="24dp" />
앗 저는 가이드 라인 쓰는게 습관이 되어서,,, 해당 레이아웃에서는 딱히 편리함이 안보이긴 한데, 
패딩 값으로 해결하기 까다로울 경우에는 편리하답니다 🤓

2024-07-15 06:04 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/presentation/type/TypeResultCustomView.kt
> +    }
흠 
취향 차이일 것 같네요! 그런데 심지의 의견 코드가 더 깔끔해보이는 것 같아서 한번 수정해볼께요~

2024-07-15 06:37 UTC, merged