An/feat/dex detail ability
woowacourse-teams/2024-pokerogue-helper pull request #87
Opened 2024-07-26 00:22 UTC by sh1mj1

- closed #86 
## 작업 영상
[포켓몬 상세에서 특성 상세로 이동.webm](https://github.com/user-attachments/assets/184d0d4b-74a1-4081-80de-d52fcf146203)

## 작업한 내용
- 포켓몬 상세 화면에서 특성 이름을 보여준다.
- 포켓몬 상세 화면에서 특성을 누르면 특성 상세 화면으로 이동한다.
- 변경된 포켓몬 상세 api 에 맞춰 `PokemonDetailResponse` 를 변경한다.

## PR 포인트
- 포인트들이 꽤 있는데 이것은 코멘트에 남길게요.
- #81 이 PR 이후에 보시면 될 것 같아요.

## 🚀Next Feature
- 데모데이 피드백과 회의 이후에 결정하겠습니다

2024-07-26 00:32 UTC, sh1mj1 reviewed
PR 포인트 코드에 남겼습니다.

2024-07-26 00:32 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/remote/dto/response/pokemon/PokemonDetailResponse.kt
> +    val abilities: List<AbilityResponse>,
이 부분이 바뀌었어요.
포켓몬 상세 화면에서 특성을 눌러서 특성 상세로 이동하려면 특성 id 가 필요합니다.

현재 서버에서 따로 DTO 만들지 않고 `description` 이 포함된 DTO 로 넘겨줍니다.
그래서 저도 기존에 만들어져있던 `AbilityResponse` 를 사용했습니다.

2024-07-26 00:32 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/model/AbilityTitleUiModel.kt
> +fun Ability.toPokemonDetailUi(): AbilityTitleUiModel =
포켓몬 상세 화면에서 쓰이는 특성 데이터는 ui 에서는 id 와 이름만 필요합니다.
`description` 은 필요 없지요.
`Response` 와 `Ability` 라는 데이터는 기존의 것을 사용했지만, uiModel 은 새로 만들었습니다.

2024-07-26 00:32 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/AbilityTitleAdapter.kt
> +class AbilityTitleAdapter(private val onClickAbility: AbilityUiEventHandler) :
포켓몬 상세 화면에서 특성을 눌렀을 때 특성 상세로 이동합니다.
@kkosang 이 작업했던 내용 중 특성 목록 화면에서 특성을 눌렀을 때 특성 상세로 이동하는 인터페이스가 `AbilityUiEventHandler` 입니다. 
일단 이것을 그대로 사용했는데 올바른 사용일지 팀원들의 의견 궁금합니다.
@JoYehyun99 @murjune

2024-07-26 16:50 UTC, murjune requested changes
작업 고생하셨습니다! 이 부분만 추가적으로 수정해주시면 감사하겠습니다 😁

https://github.com/woowacourse-teams/2024-pokerogue-helper/pull/81#discussion_r1691280839

2024-07-26 16:50 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/data/model/PokemonDetail.kt
> +                Stat("total", totalStats),
리마인드~

https://github.com/woowacourse-teams/2024-pokerogue-helper/pull/81#discussion_r1691280839

2024-07-26 16:50 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/AbilityTitleAdapter.kt
> +class AbilityTitleAdapter(private val onClickAbility: AbilityUiEventHandler) :
뭔가 Navigator 가 따로 존재했으면 좋겠다는 생각이드네요..  
Ability와 dex는 서로 다른 feature 이기에 서로의 presentation 코드를 가져가는 것이 확장성면에서는 좋지는 않거든요..  

예시)

```kotlin
interface PokeNavigator{
    fun navigateToPokeDetail(..)
    fun navigateToPokeList(..)
}
```

생각을 조금 더 해보겠습니당

2024-07-26 16:50 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailFragment.kt
> +    private fun binPokemonDetail(pokemonDetail: PokemonDetailUiState.PokemonDetailUiModel) {
```suggestion
    private fun bindPokemonDetail(pokemonDetail: PokemonDetailUiState.PokemonDetailUiModel) {
```

오타네요!

2024-07-26 16:50 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailFragment.kt
> +            ivPokemon.setImage(pokemonDetail.pokemon.imageUrl)
bindingAdpater 이름 setImageUrl 로 바꿔주실 수 있을까요 ㅋㅋㅋㅋ 제가 만들 때 네이밍 실수 했네요  

아니면 `setImageRes` 도 `setImage`로 바꿔 오버로딩된 함수 형태로 바꿔도 좋을 것 같네요!  

```kotlin
// commonBindingAdapter
@BindingAdapter("imageUrl")
fun ImageView.setImage(imageUrl: String?) {
    Glide.with(context)
        .load(imageUrl)
        .placeholder(R.drawable.icon_poke)
        .error(R.drawable.icon_error)
        .into(this)
}

@BindingAdapter("imageRes")
fun ImageView.setImage(imageRes: Int) {
    setImageResource(imageRes)
}

```

2024-07-26 16:50 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailUiState.kt
> +    data class PokemonDetailUiModel(
Success 는 어떨까요?
```suggestion
    data class Success(
```

2024-07-26 16:50 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/model/AbilityTitleUiModel.kt
> +fun Ability.toPokemonDetailUi(): AbilityTitleUiModel =
저는 Ability를 그냥 사용해도 좋다는 생각이 들지만  
uiModel 을 만들겠다는 심지의 취향 존중합니다 👍

2024-07-26 16:50 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/model/StatUiModel.kt
> +    }
이 부분도 리마인드!

https://github.com/woowacourse-teams/2024-pokerogue-helper/pull/81#discussion_r1691280839

2024-07-26 16:50 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/util/fragment/FragmentExtension.kt
> +) = getString(resId, *formatArgs)
뭔가 저번에 봤던 코드같은데.. 제 착각일까요?  
머지가 꼬였나?

2024-07-27 00:36 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/data/model/PokemonDetail.kt
> +                Stat("total", totalStats),
옹 리마인드 메시지 고맙습니다!~

2024-07-27 00:36 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailFragment.kt
> +    private fun binPokemonDetail(pokemonDetail: PokemonDetailUiState.PokemonDetailUiModel) {
앗 놓쳤네요 ㅋㅋ 꼼꼼히 봐주셔서 감사합니당

2024-07-27 00:36 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailFragment.kt
> +            ivPokemon.setImage(pokemonDetail.pokemon.imageUrl)
넵 제가 두 개 수정하겠습니당

2024-07-27 00:37 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailUiState.kt
> +    data class PokemonDetailUiModel(
넵, 꼬상 작업에서도 `Success` 로 했더라구요. 
그렇게 수정하겠습니당

2024-07-27 00:37 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/model/StatUiModel.kt
> +    }
고맙습니당

2024-07-27 00:38 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/util/fragment/FragmentExtension.kt
> +) = getString(resId, *formatArgs)
이전에는 `formatArgs` 가 `vararg` 가 아니었어요!
여러 `formatArgs` 를 사용하기 위해서 이렇게 했습니다!

2024-07-28 04:19 UTC, sh1mj1 commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/PokemonDetailFragment.kt
> +            ivPokemon.setImage(pokemonDetail.pokemon.imageUrl)
오버로딩된 함수 형태로 바꿀게요!!

2024-07-28 11:48 UTC, sh1mj1 commented
충돌 해결했습니다.
오둥이가 남겨준 피드백 반영했습니다.
https://github.com/woowacourse-teams/2024-pokerogue-helper/pull/81#discussion_r1691280839  딱 이 부분은 빼고 리팩토링 마쳤습니다. 

포켓몬의 `Stat` 은 현재 포켓몬 상세 화면에서만 쓰이고, 다른 곳에서는 쓰이지 않습니다.
그래서 일단 이슈로 남겨두고 조금 나중에 작업해도 될까요?

2024-07-28 11:52 UTC, sh1mj1 commented
충돌 해결했습니다.
오둥이가 남겨준 피드백 반영했습니다.
https://github.com/woowacourse-teams/2024-pokerogue-helper/pull/81#discussion_r1691280839  딱 이 부분은 빼고 리팩토링 마쳤습니다. 

포켓몬의 `Stat` 은 현재 포켓몬 상세 화면에서만 쓰이고, 다른 곳에서는 쓰이지 않습니다.
그래서 일단 이슈로 남겨두고 조금 나중에 작업해도 될까요?

추가로  
기존에 util 에 있던 bindingAdapter 와 쿼리 핸들러는 각각, 포켓몬 검색과 특성 검색을 위한 BindingAdapter 와 쿼리 핸들러로 나누었습니다.
@kkosang 

이름은
-  `android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilitySearchViewBindingAdapter.kt`
- `android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonQueryHandler.kt`
- `android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilitySearchViewBindingAdapter.kt`
- `android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonSearchViewBindingAdapter.kt`

입니다.

2024-07-28 15:18 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/detail/AbilityTitleAdapter.kt
> +class AbilityTitleAdapter(private val onClickAbility: AbilityUiEventHandler) :
저도 분리하는게 좋을것같다는 생각입니다~
dex에서의 기능과 특성에서의 기능은 독립적이어야 할 것 같습니다!

2024-07-28 15:28 UTC, JoYehyun99 approved these changes
수고하셨습니당~

2024-07-28 15:28 UTC, JoYehyun99 commented on android/app/src/main/res/layout/fragment_pokemon_detail.xml
> +                    android:layout_width="0dp"
width 가 `wrap_content`가 되면 좋을것같네용! 현재는 왼쪽으로 치우쳐지게 됩니당!

<img width="200" alt="image" src="https://github.com/user-attachments/assets/2469a4ff-2328-464b-a78a-5e10ba6786e7">

2024-07-28 16:14 UTC, murjune commented
> 포켓몬의 Stat 은 현재 포켓몬 상세 화면에서만 쓰이고, 다른 곳에서는 쓰이지 않습니다.
> 그래서 일단 이슈로 남겨두고 조금 나중에 작업해도 될까요?

넵! 이슈로 남겨두고 다음에 작업해도 좋을 것 같네요 👍

2024-07-28 16:15 UTC, murjune commented on android/app/src/main/res/layout/fragment_pokemon_detail.xml
> +                    android:layout_width="0dp"
치코리타 귀엽네요 ㅋㅋㅋ

2024-07-29 15:51 UTC, kkosang approved these changes
고생하셨습니다 심지~~ 굿굿 👍

2024-07-29 15:51 UTC, kkosang commented on android/app/src/main/java/poke/rogue/helper/presentation/ability/AbilitySearchViewBindingAdapter.kt
> +package poke.rogue.helper.presentation.ability
심지가 미리 이야기 해줬던 부분이 여기군요 !👍

2024-07-29 15:51 UTC, kkosang commented on android/app/src/main/java/poke/rogue/helper/presentation/dex/PokemonListViewModel.kt
> +        if (query.isEmpty()) {
이부분의 경우 `query.isEmpty()` 조건이 필요 없을 것 같네요 !

`text.contains("")`의 경우 항상 true값이 나오기 때문에, 빈 문자열이면 filter되지 않고 전부 다 나와서 따로 조건이 필요 없을 것 같아요 !

2024-07-30 01:29 UTC, murjune approved these changes

2024-07-30 01:29 UTC, merged