[BE-FEAT] 포켓몬 리스트 불러오는 API
woowacourse-teams/2024-pokerogue-helper pull request #9
Opened 2024-07-13 13:47 UTC by jinchiim

## 🍄 PR 확인 사항
PR이 다음 요구 사항을 충족하는지 확인하세요. :

- [x] API 명세서가 업데이트 혹은 작성이 되어 있나요?

## 현재 작업은 어떤 이슈를 해결한 것인지 설명해주세요.
> Issue Number: #1 

- 이슈에 있는 태스크 들을 붙여넣어주세요.

- [x] 포켓몬 도메인 생성
- [x] 타입 도메인 생성
- [x] 포켓몬 타입 도메인 생성
- [x] 포켓몬 리스트 불러오는 API

## 기존 코드에서 변경된 점이 있다면 설명해주세요. (추가 X)

- [ ] 있음
- [x] 없음

```
```

2024-07-14 08:58 UTC, jongmee requested changes
어제 페어하면서 발견하지 못한 몇 가지들에대해 리뷰 달아두었습니다 ! 

확신이 안 서서 로컬에서 테스트 코드로 확인했는데 (`@OneToMany` 부분) 월요일에 테스트 환경도 같이 맞춰보면 좋을 것 같네요 😚

2024-07-14 08:58 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/Pokemon.java
> +    @OneToMany(mappedBy = "pokemon")
포켓몬을 조회할 때 (거의) 항상 타입도 함께 조회해야 하므로 양방향을 추가했었죠!

그런데 생각해보니 `@OneToMany`의 기본 fetchType이 Lazy라 요렇게 해놓으면 join으로 조회되지 않겠네요 😂 `fetch = FetchType.EAGER` 이 옵션을 설정해주어야 합니다 !

2024-07-14 08:58 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +public class PokemonService {
지금 당장은 괜찮지만 추후 다같이 `@Transactional`과 OSIV 설정도 고민해보면 좋겠네요 ☺️

2024-07-14 08:58 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +
개행 기준도 맞춰보는게 좋으려나요 ? 🤔 저는 개행을 잘 하지 않는 편이라서 (제 기준 가독성 때문에 있으면 좋겠다고 생각되는 부분은 넣고) 남겨봅니다 ㅎㅎ

2024-07-14 08:58 UTC, jongmee commented on backend/pokerogue/src/main/java/com/pokerogue/helper/type/domain/Type.java
> +@Table(name = "type")
생각해보니 MySQL 예약어에 `type`이 있습니다.. yml 파일에 
```
spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
```
이걸 추후에 추가하거나 테이블 이름을 바꾸는게 좋겠네요 !

만약 이름을 바꾼다면,
(의견) 이 테이블 이름을 pokemon_type으로 하고 pokemon과 pokemon_type 간의 다대다 관계 테이블 이름을 pokemon_type_mapping으로 하는 게 어떨까요? 테이블 이름을 바꾼다면 엔티티 클래스 이름도 함께 바꾸고요!

2024-07-14 09:06 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/domain/Pokemon.java
> +    @OneToMany(mappedBy = "pokemon")
아 그렇네요 ㅋㅋㅋㅋㅋㅋㅋㅋ
리뷰 전부 다 읽었는데 월요일에 다같이 논의해보아요!

2024-07-15 05:51 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +public class PokemonService {
추후 고민을 다같이 한번 더 하기 위해 resolve 안하고 남겨두겠습니다!

2024-07-15 05:54 UTC, jinchiim commented on backend/pokerogue/src/main/java/com/pokerogue/helper/pokemon/service/PokemonService.java
> +
해당 부분 오늘 논의한대로 개행 컨벤션 `wiki`에 추가하고 앞으로 이렇게 사용합시다!

2024-07-15 06:03 UTC, jongmee approved these changes
첫 PR 머지 👍

2024-07-15 06:03 UTC, unifolio0 approved these changes

2024-07-15 06:03 UTC, dwax1324 approved these changes

2024-07-15 06:04 UTC, merged