[AN-FEAT] 특성 상세 네트워크 연결
woowacourse-teams/2024-pokerogue-helper pull request #96
Opened 2024-07-28 14:43 UTC by kkosang

- closed #83 
## 작업 영상
[an:feat:특성상세(네트워트연결).webm](https://github.com/user-attachments/assets/29728ef0-9af3-4bb1-931b-1ef89350ffb1)

## 작업한 내용
- 해커톤에서 사용하던 코드 `MVVM` 패턴 적용
- `repository` & `datasource`
- dummy data에서 `네트워크` 연결

## PR 포인트
- 아직 특성 디테일에서 -> 포켓몬 디테일로 이동은 하지 않습니다. (추후 Fragment로 변경하면서 이동하도록 수정할게요 !)

## 🚀Next Feature
Detail Fragment로 변경 후 화면 이동

2024-07-28 15:52 UTC, JoYehyun99 approved these changes
수고하셨슴니당~~~ 👍

2024-07-28 15:52 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewModel.kt
> +    suspend fun updateAbilityDetail(abilityId: Long) {
해당 함수를 `suspend` 로 지정한 이유가 있나용?

2024-07-28 15:52 UTC, JoYehyun99 commented on android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewHolder.kt
> +    private val onClickPokemonItem: AbilityDetailUiEventHandler,
`onClickPokemonItem` 
이름에서 `onClick`은 들어가지 않도록 결정했던 것 같습니당!

2024-07-28 16:44 UTC, murjune requested changes
코루틴을 활용하여 서버 통신하는 것이 처음이실 텐데 고생하셨습니다 🎉  

코멘트 확인 부탁드려요~

2024-07-28 16:44 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/data/datasource/RemoteAbilityDataSource.kt
>      suspend fun abilities() = abilityService.abilities().data.map { it.toData() }
return 타입을 명시해주세요!
```suggestion
    suspend fun abilities(): List<Ability> = abilityService.abilities().data.map { it.toData() }
```

2024-07-28 16:44 UTC, murjune commented on android/app/src/main/AndroidManifest.xml
> +        android:usesCleartextTraffic="true"
아마 localHost 로 연동해서 위와 같은 옵션을 준거 겠죠??  
`networkSecurityConfig` 를 지정해주었으니 해당 옵션은 삭제해주세요!!  
HTTP 통신은 쉽게 해킹당할 위험이 있는 것으로 알고 있기에 해당 옵션은 지양해야합니다 😁

2024-07-28 16:44 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/data/datasource/RemoteAbilityDetailDataSource.kt
> +}
RemoteAbilityDataSource 가 있는데 따로 datasource 를 추가적으로 만드신 이유가 있을까요?? 

전 Ability, AbilityDetail 를 제공하는 DataSource 는 같아야한다고 생각해요 🤔

2024-07-28 16:44 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/data/repository/DefaultAbilityDetailRepository.kt
> +}
마찬가지입니다.  
AbilityRepository 면 충분한 것 같습니다.  

지금보니 Poke 도 동일하게 Detail 로 분리되어있네요 😨  
전에 코드리뷰를 꼼꼼히 못본게 아쉽게 됐네요 ㅜㅜ

@sh1mj1 심지는 어떻게 생각하시나요?

2024-07-28 16:44 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewModel.kt
> +    suspend fun updateAbilityDetail(abilityId: Long) {
불필요한 `suspend` 키워드 삭제 요청드립니다!

2024-07-28 16:44 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailActivity.kt
> +            val id = intent.getLongExtra(ID, -1)
id가 -1 이라면 에러를 발생시켜야하지 않을까요?

2024-07-28 16:44 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewModel.kt
> +    suspend fun updateAbilityDetail(abilityId: Long) {
id 가 -1 일 때 예외 처리를 부탁드립니다

2024-07-28 16:44 UTC, murjune commented on android/app/src/main/java/poke/rogue/helper/presentation/ability/detail/AbilityDetailViewHolder.kt
> +    private val onClickPokemonItem: AbilityDetailUiEventHandler,
> 이름에서 onClick은 들어가지 않도록 결정했던 것 같습니당!    

@JoYehyun99 저희 parameter 이름에 대한 컨벤션은 정하지 않았던 것으로 기억합니다!

전 ViewHolder 도 View 이기에 parameter 정도는 `onClickXXX`으로 네이밍 해도 괜찮다고 봅니다.  

다만, 이 부분도 일관성을 가져가는 것이 좋아보이네요! @kkosang @JoYehyun99 @sh1mj1 다들 어떻게 생각하시나요?

2024-07-29 12:07 UTC, kkosang reviewed
코멘트 방식을 잘 못 한듯..😂

2024-07-29 13:01 UTC, murjune approved these changes
그거야~ 👍

2024-07-29 15:25 UTC, merged